### ISSUE TITLE
SyncLists call twice on Client / 3x on Host when first connecting

### ISSUE THREAD

**Issue by gresc574** [FirstGearGames/FishNet#10]
When first connecting as a local player Synclist Adds OnChanged call 2x for the local client only (when IsClientOnly)

When host Synclist Adds are called 3x for all player objects.

Nightly 1.1.4

**Comment by FirstGearGames** [comment]
Will be looking at this today.

**Comment by gresc574** [comment]
` public override void OnStartServer()
    {
        Debug.Log("On Start Server");
        for (uint i = 0; i < InventoryCapacity; i++)
        {
            SlotItemData data = new SlotItemData(i);
            InventorySlotDatas.Add(data);
        }
        base.OnStartServer();
    }

    private void Awake()
    {
        Debug.Log($"Awake. Adding hook");
        InventorySlotDatas.OnChange += InventoryDataChanged;
    }

    private void InventoryDataChanged(SyncListOperation op, int index, SlotItemData olditem, SlotItemData newitem, bool asserver)
    {
        Debug.Log($"On Changed - {op}, server - {asserver}");
        switch (op)
        {
            case SyncListOperation.Add:
                SlotItemView slotView = new SlotItemView(newitem);
                ClientInventorySlotViews.Add(slotView);
                break;
            case SyncListOperation.Insert:
                break;
            case SyncListOperation.Set:
                ClientInventorySlotViews[index].SlotItemData = newitem;
                break;
            case SyncListOperation.RemoveAt:
                break;
            case SyncListOperation.Clear:
                break;
            case SyncListOperation.Complete:
                break;
            default:
                throw new ArgumentOutOfRangeException(nameof(op), op, null);
        }
    }`

**Comment by FirstGearGames** [comment]
Resolved in 1.1.5
