### ISSUE TITLE
FishNet 2.4.5Pro Can't build dedicated server only work in editor

### ISSUE THREAD

**Issue by Arderku** [FirstGearGames/FishNet#110]
Hi I found out that in new version I can't build dedicated server anymore.
`Assets\FishNet\Runtime\Managing\NetworkManager.cs(199,17): error CS0246: The type or namespace name 'ObjectPool' could not be found (are you missing a using directive or an assembly reference?)
`
I think is related that NetworkManager has FishNet.Utility.Performance namespace in #if UNITY_EDITOR.

As bonus bug FishNet 2.4.5Pro  VERSION.txt still shows 2.4.4Pro version

**Comment by Arderku** [comment]
![image](https://user-images.githubusercontent.com/11285378/191558024-61780497-eadd-4873-80c7-ac95768a426b.png)
if I move  FishNet.Utility.Performance namespace from #if UNITY_EDITOR the builds works, but probably I should not do it as you guys put this there for a reason I assume.

**Comment by FirstGearGames** [comment]
Sorry about that, it seems the WIP Pro version was uploaded instead of the release branch. I've re-uploaded; please download again and you should be good.
