### ISSUE TITLE
Custom Serializer Breaks Prediction If Used by Replicate/Reconcile Structs

### ISSUE THREAD

**Issue by TsFreddie** [FirstGearGames/FishNet#12]
Already discussed in Discord, posting for tracking.

**Info**
* Unity Version: 2020.3.23f
* FishNet Version: 1.1.4.Nightly.3
* Environment: Editors

**Steps To Reproduce:**
1. Open rigidbody prediction examples.
2. Add a custom writer in `RigidBodyPredicion.cs`:
```C#
    public static class BrokenMoveDataWriter
    {
        public static void WriteMoveData(this Writer writer, MoveData data)
        {
            writer.Write(data.Jump);
            writer.Write(data.Horizontal);
            writer.Write(data.Vertical);
        }
        
        public static MoveData ReadMoveData(this Reader reader)
        {
            return new MoveData(reader.ReadBoolean(), reader.ReadFloat(), reader.ReadFloat());
        }
    }
```
3. Launch example, observes that server won't move client's rigidbody.

**Possible solutions:**
* Sync the generated tick field in codegen if a custom serializer exists if possible.
* Emit warning/error and direct user to a documentation with possible workarounds.

**Comment by FirstGearGames** [comment]
An article has been added for this. Closing the issue until the code-gen warning/error option is on the table.
https://fish-networking.gitbook.io/docs/manual/guides/custom-serializers-guides/prediction-serializers
