### ISSUE TITLE
The type or namespace name 'PostProcessorAssemblyResolver' could not be found

### ISSUE THREAD

**Issue by CodeSmile-0000011110110111** [FirstGearGames/FishNet#128]
I get three of these errors after importing Fish-Net from the Asset Store (v2.5.3) in a Unity 2020.3.40 project that already has Netcode for GameObjects 1.0 in it. 

I noticed upon installing the package that FN wants to overwrite files in the Netcode package:
![image](https://user-images.githubusercontent.com/42713966/195104569-4c609e08-f9e8-42a8-82b5-347f043a7d70.png)

I tried with and without importing these three files. But since the Netcode package is "read-only" Unity will revert any changes to these files immediately.

Full log:
```
Assets\FishNet\CodeGenerating\ILCore\ILCoreHelper.cs(18,13): error CS0246: The type or namespace name 'PostProcessorAssemblyResolver' could not be found (are you missing a using directive or an assembly reference?)

Assets\FishNet\CodeGenerating\ILCore\ILCoreHelper.cs(18,66): error CS0246: The type or namespace name 'PostProcessorAssemblyResolver' could not be found (are you missing a using directive or an assembly reference?)

Assets\FishNet\CodeGenerating\ILCore\ILCoreHelper.cs(24,50): error CS0246: The type or namespace name 'PostProcessorReflectionImporterProvider' could not be found (are you missing a using directive or an assembly reference?)
```

**Comment by FirstGearGames** [comment]
Yeah, you have to remove Netcode entirely before importing FN.
