### ISSUE TITLE
Codegen not importing types in other asms in auto serialized types

### ISSUE THREAD

**Issue by FirstGearGames** [FirstGearGames/FishNet#13]
eg:
AsmA
public struct ABC
{
    public DEF Deff; //This will cause codegen break because it's in a different assembly from ABC.
}

AsmB
public struct DEF {}

**Comment by FirstGearGames** [comment]
Issue resolved locally. Awaiting feedback.

**Comment by NickMercer** [comment]
I was the one who reported in Discord. Can confirm that your fix to that method fixed it in my code base as well.

**Comment by FirstGearGames** [comment]
Thanks. Resolved in 1.1.5.Nightly.2
