### ISSUE TITLE
Spawning error, parent not found under specific conditions.

### ISSUE THREAD

**Issue by FirstGearGames** [FirstGearGames/FishNet#136]
Pazzaar
 — Today at 1:01 PM
I've actually found the issue, it was to do with spawning!
My spawn on parent logic was being performed within the dropped weapon object
```
    public class DroppedItem : NetworkBehaviour
{
    [SerializeField]
    private GameObject holdableItemPrefab;

    [ServerRpc(RequireOwnership = false)]
    public void ClientTryToPickUpWeapon(EquippedItems inventoryAttemptingPickUp, NetworkConnection conn = null)
    {
        GameObject go = Instantiate(holdableItemPrefab);
        go.transform.SetParent(inventoryAttemptingPickUp.transform);
        base.Spawn(go, conn);
        Despawn();
    }
}
 ```
I figured I would spawn the weapon as a child on the picking up object, and then remove the dropped weapon on the same tick with a Despawn()
turns out that breaks it if there are two or more children

**Comment by pazzaar** [comment]
To reproduce this, I think the trick is despawning the first dropped weapon
then picking up the 2nd dropped weapon, and despawning that
and it blows up
if you pick up both weapons, and then despawn them both (after they have both been picked up)
the client doesn't have an error

**Comment by pazzaar** [comment]
```
public class DroppedItem : NetworkBehaviour
{
    [SerializeField]
    public GameObject holdableItemPrefab;

    public bool DespawnNow;

    [ServerRpc(RequireOwnership = false)]
    public void ClientTryToPickUpWeapon(EquippedItems inventoryAttemptingPickUp, NetworkConnection conn = null)
    {
        GameObject go = Instantiate(holdableItemPrefab);
        go.transform.SetParent(inventoryAttemptingPickUp.transform);
        base.Spawn(go, conn);
    }

    public void Update()
    {
        if (DespawnNow)
        {
            base.Despawn();
        }
    }
}
```

If you run the server, and pick up DroppedWeapon01, despawn it using the checkbox in editor, then pick up DroppedWeapon02, despawn it, then connect with an external client, it breaks.

If you run the server, pick up both weapons, then despawn both dropped instances, and connect with the external client, it works!

**Comment by pazzaar** [comment]
[CharacterControllerExampleFromFishnet257pro.zip](https://github.com/FirstGearGames/FishNet/files/9847488/CharacterControllerExampleFromFishnet257pro.zip)

Example project reproducing the bug in 2.5.7 - run and spawn as the host -> spawn a nob by pressing 'R', then despawn the existing object with 'E', then spawn another object with 'R' again. Then, connect with another client. It should blow up!

**Comment by FirstGearGames** [comment]
I want to look into this soon but want to make sure this is still a problem on 2.6.2?

**Comment by FirstGearGames** [comment]
Do you happen to know if this is still an issue on 2x LTS?
