### ISSUE TITLE
UWP Build failing in Unity 2021.3.12f1

### ISSUE THREAD

**Issue by AaronTaube** [FirstGearGames/FishNet#137]
Fishnet version 2.5.2 (had it in 2.5.8 as well, but currently in .2).
Error happening at line 131 of 
Believe the error had said something to the effect of subtarget invalid on platform (WSAPlayer). 
Adding && !UNITY_WSA to the conditional seems to fix it on initial build, but the AppX still fails.

**Comment by FirstGearGames** [comment]
Resolved in 2.6.1, thanks.
