### ISSUE TITLE
SyncVar issue

### ISSUE THREAD

**Issue by SnaiperoG3D** [FirstGearGames/FishNet#139]
If start variable value is equals as new one, hook method will not called, even if start value is a default variable type value.
Example. I need to sync clientid, its an int type, default value is 0, first player connection will be 0 as well, as a result when i will set parentNi to conn.ClientId (which will be 0 as a first client, onParentNiChange never called)
    [SyncVar(OnChange = nameof(onParentNiChange))]
    public int parentNi;
To prevent it i need to change start parentNi value to -1 in Inspector in my prefab.

This issue ofcource will present only with first client connection. Plus its happend only on client.

**Comment by FirstGearGames** [comment]
The clientId is a unique situation but none the less it's intended behavior to only send and invoke on change.
BTW you can send NetworkConnection even from client.
