### ISSUE TITLE
Execution order docs

### ISSUE THREAD

**Issue by SnaiperoG3D** [FirstGearGames/FishNet#141]
This page really need improvements. It contains only info about fishnet order, but how it will work with unity methods? Where will be called onStart, onEnable, Awake, etc.
https://fish-networking.gitbook.io/docs/manual/guides/network-behaviour-guides

It should be done like this i think: https://mirror-networking.gitbook.io/docs/faq/execution-order

**Comment by FirstGearGames** [comment]
For network initialization users should never use unity callbacks. We don't guarantee their order in relation to network callbacks because that's Unity things. If they don't already mention something of this sort I'll add it in.
