### ISSUE TITLE
Add OnClientLoadedNewScenes and OnClientChangedScene in scenemanager or servermanager

### ISSUE THREAD

**Issue by EiTaNBaRiBoA** [FirstGearGames/FishNet#144]
### The current
Right now when a client joins to the server and loads the first scene the event ` public event Action<NetworkConnection, bool> OnClientLoadedStartScenes;` is invoked but it doesn't invoke later when replacing or adding scene.
### The issue
As for someone who works with multiple scenes, i need to know when the client has finished to load the new scene as a server and when his gameobject player is actually moved. Because i am using additive scenes and replacing scenes i want to avoid several race conditions when working with XRtoolkit, so there are two events that could be added to help avoid that issue.

#### OnClientLoadedNewScenes - when the client finished loading the new scene (Before moved to the new scene)
` public event Action<NetworkConnection, bool> OnClientLoadedNewScenes ;` 
When i am using Additive scenes , for example: new map is loading in the background to all clients, and I want to know when all clients have finished loading the scene/scenes before they were moved (Use cases: to know when to spawn the enemies or updating their parameters to start the match).
#### OnClientChangedScene - when the client finished loading the new and after moved to the new scene
` public event Action<NetworkConnection, bool> OnClientChangedScene ;` 
When i want to give the player an item to his hand (VR) , [XRtoolkit ](https://docs.unity3d.com/Packages/com.unity.xr.interaction.toolkit@2.2/manual/images/interaction-update.svg)makes plenty of execuations and validations to make the player actually hold the item. I got several race conditions from CanSelect (XR Validating system) and OnSelectEnter/Exit (Interaction System). This method will tell me when the client (The sld.MovedObjects) has been transfered successfully to the new scene with the client synced.

Thank you for reading and i hope you would consider it.

**Comment by FirstGearGames** [comment]
Do you need this info on the server side or client?

**Comment by EiTaNBaRiBoA** [comment]
> Do you need this info on the server side or client?

I need it in serverside

**Comment by FirstGearGames** [comment]
You should be using OnClientPresenceChangeStart/End.
See events on scene manager for more information on these.
