### ISSUE TITLE
IL2CPP in build error - Delegate to an instance method cannot have null 'this'.

### ISSUE THREAD

**Issue by Ko0z** [FirstGearGames/FishNet#150]
After installing a fresh 2020 LTS editor with IL2CPP support, empty scene with FishNet NetworkManager and Player prefab. Apparently if any NetworkBehaviour has a [ServerRpc] method it will throw and error when starting Server and Client in a build.

Error if any NetworkBehaviour has a [ServerRpc] of any kind.
"Delegate to an instance method cannot have null 'this'."

The error is NOT present in Unity 2020.3.18f1.

Steps to reproduce:

1. Install fresh unity 2020.3.41f1 LTS version with IL2CPP support for windows.
2. Create a new project, set scripting backend to IL2CPP with .NET 4.x API and import FishNet v2.5.10.
3. Use the FishNet NetworkManager prefab and put the FIshNet Player prebab in the PlayerSpawner.
4. Build the project with Development Build to see log and watch the error happen when starting server and then client.

![FishNet_error](https://user-images.githubusercontent.com/9639004/200182369-973ed479-4457-457e-915d-81181f6a43ba.png)

**Comment by FirstGearGames** [comment]
I would try updating your editor. No issues in 2020.3.30f1.

**Comment by Ko0z** [comment]
Alright yes I also tried 2020.3.30f1 and just like 3.18f1 there are no error on these editors. 

I wonder why the newer editors break it though.

**Comment by FirstGearGames** [comment]
I read that you were on 3.18 the first go around. That's just Unity for you, the IL2CPP builds are often different between versions some reason. Usually it's fine on LTS but yeah.

**Comment by Ko0z** [comment]
I know you closed this but I did some digging and found that the error came in 2020.3.35f1 release. Reading in the release note of that release, we can find:

"IL2CPP: Improved error messaging by throwing an ArgumentException when an delegate is created on an instance method with a null this parameter. ([1412320](https://issuetracker.unity3d.com/issues/memory-corruption-on-macos-slash-ios-slash-tvos))"

Just letting anyone interested know. 
Cheers!

**Comment by FirstGearGames** [comment]
Well crud I may have to reopen it then. We do this, intentionally.

**Comment by FirstGearGames** [comment]
I do not have that unity version installed but I have this fixed if you want to save me some time and test it out.

**Comment by Ko0z** [comment]
Sure thing, I'll test it asap

**Comment by FirstGearGames** [comment]
Will send you discord DM.
