### ISSUE TITLE
CSP - Input Data Default Value Not Being Set Properly

### ISSUE THREAD

**Issue by LiamBoog** [FirstGearGames/FishNet#151]
I have the following InputData struct which just contains the results from polling InputActions each frame.
![image](https://user-images.githubusercontent.com/48077738/200193504-d232cb68-5bdd-4473-bc85-ff75d1eb1c40.png)

This is how I'm passing it to the Move function for client and server.
![image](https://user-images.githubusercontent.com/48077738/200193561-ffff8a19-1ce9-4740-8720-3b2feedec5a0.png)

When using a WEBGL client along with a headless server, occasionally, the InputData passed into Move on the server is the actual default value of InputData (i.e., throttle, steering = 0, handbrake = false). This only happens for one frame on the server and it happens while performing inputs (it might also happen when not performing inputs but I don't think there's a way to find out). 

It doesn't happen in the editor. I haven't tested other platforms as I have no easy way of debugging those and I don't care about them for my project.

**Comment by FirstGearGames** [comment]
Maybe the buffer is being cleared out on the server, in which there would be no values. This could be possible due to fluctuations in latency.

**Comment by FirstGearGames** [comment]
This will be closed in 5 days if no follow-up is received.
