### ISSUE TITLE
Add ability for SyncVars to only replicate once

### ISSUE THREAD

**Issue by shohnwal** [FirstGearGames/FishNet#152]
Maybe I have not seen it in the documentation, but just in case : 

I feel the current way of having a SendRate might be rather wasteful when you have a SyncVar that should never change or only change on demand, because either way you'd have a redundant timer running in the background, comparing the SyncVar over and over even thought it shouldn't change for a long time, if ever, such as player names, character outfit data or positions for rarely moving environment objects.

For some cases it would be very useful to have a SyncVar option "InitialOnly" or make a special case for SendRate = 0, so in this case the SyncVar does not get a SendRate timer and only gets sent to a client during the first replication of that object. Any other changes of that SyncVar would have to be done via RPCs.

**Comment by FirstGearGames** [comment]
SyncTypes only send on change and the properties are not polled. The only time any work is done is after you change a value or modify the sync type.
