### ISSUE TITLE
Assembly will not be loaded due to errors: Reference has errors 'FishNet.Runtime'.

### ISSUE THREAD

**Issue by MetelskyVsevolod** [FirstGearGames/FishNet#156]
I am using Unity version 2021.3.13f1.
I imported the Fish networking package from the asset store and got a following error:

Assembly 'Library/ScriptAssemblies/FishNet.Example.dll' will not be loaded due to errors:
Reference has errors 'FishNet.Runtime'.

I have tried reimporting the project but it didn't help. If you have any ideas on how to fix this issue, please let me know!

<img width="698" alt="Error1" src="https://user-images.githubusercontent.com/21962408/201513471-d6229ade-1e1d-4165-8628-3c029264956d.png">
<img width="1280" alt="error2" src="https://user-images.githubusercontent.com/21962408/201513473-fd2754a8-e055-42bb-a36b-8e9138f435ea.png">

**Comment by alexsaaf** [comment]
Same here with 2021.3.2f1. 
Also seems the package manager can't handle setting a specific version of a package if the package could not be loaded, so can't try with another version 😑

**Comment by FirstGearGames** [comment]
You just have to restart unity and it shouldn't be an issue going forward.

**Comment by alexsaaf** [comment]
Thanks for the quick response, feeling a bit dumb for not trying that. Works like a charm now 🙏

**Comment by FirstGearGames** [comment]
Np!

**Comment by duyca** [comment]
How I can fix this for older version bellow 2.6.0.
Bug will show if I reimport other dll on my project.

**Comment by FirstGearGames** [comment]
Restart Unity. This is also fixed in 2.6.0
