### ISSUE TITLE
Write begginner friendly step-by-step guide

### ISSUE THREAD

**Issue by grascm** [FirstGearGames/FishNet#159]
Like mirror's getting started guide, that tells "do that" and "do this":
https://mirror-networking.gitbook.io/docs/general/getting-started

It's much more helpful for understanding how to use library than analyzing complete example projects.

**Comment by FirstGearGames** [comment]
Check this out https://fish-networking.gitbook.io/docs/manual/tutorials

There are a ton of step by steps in there for starter devs.
