### ISSUE TITLE
Scene NetworkObjects don't spawn when server starts using 'Reload Scene', but not 'Reload Domain'.

### ISSUE THREAD

**Issue by FirstGearGames** [FirstGearGames/FishNet#16]
Astrobinary
Unity Version: 2021.2.7f1
FN Version: 1.2.0 Nightly.1
Client/Host is editor.

Enter play mode settings: "Reload Scene" is checked AND "Reload Domain" is unchecked. It fails to enable network objects in the scene. I tried this on FN 1.1.2 without any issue, so I am not sure what exact build broke it.

Steps to reproduce:
Clean FN, open any sample scene with networked scene objects. Make sure "Reload Scene" is checked and "Reload Domain" is unchecked. Start server and you'll see server objects do not enable (this will happen after 2nd attempt if project was just opened). Also throws other errors if you try to connect client.

**Comment by FirstGearGames** [comment]
Fixed in 1.2.0.Nightly.3

**Comment by hesham-akmal** [comment]
Looking forward downloading this, tired of waiting 2 seconds for each play test :p
