### ISSUE TITLE
Rigidbody2D CSP possibly disrupting animations with Rigidbody Pauser

### ISSUE THREAD

**Issue by mkirkpatrick** [FirstGearGames/FishNet#161]
Setup:
Player objects are using Rigidbody2D set to Kinematic with Predicted Object. Movement is using the RigidbodyPrediction script in Examples except with all 3D things removed (jump, rotation, velocity, etc.) Only position is set and reconciled. IsMoving and FacingVector are states set based on this movement. These states have OnChange functions that trigger the animator.

Issue:
Other clients beside owner stop animating a short time after stopping their movement. When this happens RigidbodyPauser_Kinematic shows up in the hierarchy. Upon inspecting the animator for these stopped clients, it appears that the animator parameters are rapidly set to 0 as if resetting every frame. Attempt to manually change them just sets them back. Moving the client breaks them out of this pause until shortly after they stop moving again and then the cycle repeats.

Testing Done:
1. Attempted writing animation scripts using both Network Animator and custom animator + SyncVars.
2. Placed debug logs in the animator set functions to ensure changes were happening as intended. They were correct for both client and server, never showing the 0 values or spamming logs every frame.
3. Removed Predicted Object script from player object and animations started working perfectly (Of course then the player didn't move.)

Demo:
Left player is other client and shows the resetting of values in inspector. Right player is owner and shows setting values and animation working.
https://user-images.githubusercontent.com/7445753/202377924-25b34ffa-4ee6-44a9-8429-d86c32fbfa9c.mp4

**Comment by FirstGearGames** [comment]
Confirmed.

**Comment by FirstGearGames** [comment]
Resolved in 2.6.3
