### ISSUE TITLE
Bug with Coroutines running in NetworkBehaviours

### ISSUE THREAD

**Issue by hudmarc** [FirstGearGames/FishNet#163]
Currently this code (inside of a NetworkBehaviour derived class) does not execute to completion, because the Coroutine seemingly stops during the yield statement:
```
public override void OnOwnershipServer(NetworkConnection prevOwner)
        {
            base.OnOwnershipServer(prevOwner);
            if (autoRegister)
            {
                InitializeOnServer();
                Debug.Log("Initializing on Server");//This logs correctly
                StartCoroutine(TeleportToHost());//This doesn't run
            }  
        }
        IEnumerator TeleportToHost()
        {
            Debug.Log("Initialized...");
            yield return new WaitForSeconds(3);
            Debug.Log("Teleporting...");
            manager.TeleportTo(this, manager.localObserver);
        }
```
The "Initialized..." is logged correctly (presumably because it is running synchronously) but the "Teleporting..." after the yield statement is not logged, and the method after the log is not called either.

On the other hand the following code (using a Task instead of a Coroutine) works as it should.
```
public override void OnOwnershipServer(NetworkConnection prevOwner)
        {
            base.OnOwnershipServer(prevOwner);
            if (autoRegister)
            {
                InitializeOnServer();
                Debug.Log("Initializing on Server");//This logs correctly
                var task = TeleportToHost();
            }  
        }
        async Task TeleportToHost()
        {
            Debug.Log("Initialized...");
            await Task.Delay(3000);
            Debug.Log("Teleporting...");
            manager.TeleportTo(this, manager.localObserver);
        }
```
Since the problem only occurs when using a Coroutine, and not when using a C# Task, I assume the coroutine is being cancelled by some built-in Unity mechanism. Here's a list of things that cancel Coroutine asynchronous execution, according to the Unity forum. Could any of the following apply in this situation?

- The MonoBehaviour that started the coroutine was disabled
- The GameObject that the MonoBehaviour is attached to was deactivated
- Either of the above was destroyed
- Timescale was modified (if using a WaitForSeconds or similar)
- A WaitUntil condition was not met (doesn't apply in this situation as far as I can tell)

**Comment by FirstGearGames** [comment]
FN version please.

**Comment by FirstGearGames** [comment]
Can you please update to 2.6.3 and confirm this still is a problem.

**Comment by RP1Nate** [comment]
I can confirm that version 2.6.3 does not fix this

**Comment by RP1Nate** [comment]
Just updated to version 3.1.5 and tested. This is not fixed here either

**Comment by FirstGearGames** [comment]
I tried on 3.2--- experimental and was not able to replicate. I received the 'Teleporting...' text three seconds after the player object spawned. 3.2 is coming out soon, but I suspect there are no differences between it and 3.1 which would cause different behavior in this area.

![image](https://user-images.githubusercontent.com/27169134/215335584-4afc6afd-60d1-4a7d-ae23-144d3a94e16c.png)

Script added to the player object
```

public class Whatever2 : NetworkBehaviour
{
    private void OnEnable()
    {
        Debug.Log("Enabled");
    }
    private void OnDisable()
    {
        Debug.Log("Disabled");
    }

    public override void OnOwnershipServer(NetworkConnection prevOwner)
    {
        base.OnOwnershipServer(prevOwner);
        StartCoroutine(TeleportToHost());
    }
    private IEnumerator TeleportToHost()
    {
        Debug.Log("Initialized...");
        yield return new WaitForSeconds(3);
        Debug.Log("Teleporting...");        
    }
}
```

**Comment by cakeslice** [comment]
I have the same issue on 3.1.6. Will try a newer one

**Comment by cakeslice** [comment]
Still not working on `3.2.010.Pro`

I made a repro scene (will send on Discord in DM since it uses the pro version).

The issue seems to be when you start the coroutine on `Awake()`. On `Start()` works fine.

**Comment by TrustNoOneElse** [comment]
You do not need to recreate a scene for it, its normal Unity behaviour, you see the coroutine is cancled when the gameobject is getting deactivated and will not continue once it is activated again, while Tasks don't care about it.

**Comment by FirstGearGames** [comment]
If the object is being instantiated then disabled this is expected **Unity** behavior as TNOE said. I'll double check when able though.

**Comment by FirstGearGames** [comment]
Scene objects will disable immediately when the scene is loaded then re-enable after getting spawn message.
Instantiated objects stay enabled.

**Comment by hesham-akmal** [comment]
> Scene objects will disable immediately when the scene is loaded then re-enable after getting spawn message. Instantiated objects stay enabled.

Would be awesome if CodeGen could throw an error for this? Sooner or later devs will do a whoopsie and forget about this. Should I open a suggestion?
