### ISSUE TITLE
Renderers that are disabled in the prefab get enabled when spawned

### ISSUE THREAD

**Issue by maxkratt** [FirstGearGames/FishNet#170]
There seems to be a problem in recent versions where renderers (such as mesh renderer) that are disabled in their prefab are incorrectly enabled once spawned in. I suspect this is caused by the observer system, I have tested it on version 2.6.4 and it has been reported on 2.6.2 too. Version 1.5.2 did not have this behaviour.

As a test I simply opened the "CharacterControllerPrediction" prefab from the CharacterController example. Added a cube, disabled the mesh renderer, and started the game and server + client. In the newer versions the cube's mesh renderer is automatically enabled once the object is spawned in.

**Comment by lordubbe** [comment]
Just want to add that this has been an issue for quite a while (at least 3-4 months) as I remember removing unused mesh renderers way back when I started integrating FN
