### ISSUE TITLE
CSP - Lagging OfflineRigidbody or maybe PredictedObject too?

### ISSUE THREAD

**Issue by Xelopie** [FirstGearGames/FishNet#171]
In OfflineRigidbody.cs, the rigidbody is getting unpaused when OnPostTick which is after the physics simulation. That makes it completely skip the simulation on the tick where reconciliation for any CSP object is happening.

Changing back to "unpausing when OnPostReconcile" should solve the problem. I remember back in 2.5.x version it was working fine with OnPostReconcile. Same code issue in PredictedObject but I can't tell if it is bug or not because it seems fine visually.

**Comment by FirstGearGames** [comment]
OnPostReconcile sounds correct. Perhaps the change was a mistake in recent versions. Thank you.

**Comment by FirstGearGames** [comment]
Reverted in 3.1
