### ISSUE TITLE
Predicted Object overriding rotation although smooth rotation disabled

### ISSUE THREAD

**Issue by Stormhound** [FirstGearGames/FishNet#172]
I have a problem where predicted object overrides graphical objects rotation. I'm trying to change it manually because I'm building a FPS game and I want my player model rotate using client auth. Overriding rotation values stops after I disable Predicted Object. So I think that this might be a problem.

**Comment by lordubbe** [comment]
It is essential functionality of the PredictedObject, so there’s no way around this. What you could do is have another graphics parent below that and then have the rotation if that be client auth

**Comment by FirstGearGames** [comment]
I realized after our talk that you are having issues with owner smoothing. The "dont smooth" option is for spectators. I can definitely make an option for owner too but it will be a at least a week. I'm also a little confused. You said you're making a FPS but you need to rotate the player model with client auth. Generally in FPS the model is on the camera.

**Comment by Stormhound** [comment]
You said server auth rotation could be tricky so I tried client auth. I wanted to rotate other client's model to where their cameras look, but predicted object prevents me to change models rotation even though smooth rotation is disabled. I don't have many experiences in FPS but couldn't it be weird if player model placed in camera because of X axis ? Also I have a question, separating camera from player root is better than leaving it as a child?

**Comment by FirstGearGames** [comment]
This requires additional features to be added to PredictedObject. I'll try to get these in by 3.1 for you.

**Comment by FirstGearGames** [comment]
Moved to here https://github.com/FirstGearGames/FishNet/discussions/198

**Comment by FirstGearGames** [comment]
Added in 3.3.0. Please see #198 for files.
