### ISSUE TITLE
PrefabCollectionGenerator Settings are stored in Library

### ISSUE THREAD

**Issue by Nigel-C** [FirstGearGames/FishNet#174]
PrefabCollectionGenerator Settings are stored in `Library/FishNet.Runtime.Editor.PrefabObjects.Generation.Settings.json`:

https://github.com/FirstGearGames/FishNet/blob/893566e52e9467da68213ce996eea46dfb2c39a3/Assets/FishNet/Runtime/Editor/PrefabCollectionGenerator/Settings.cs#L63

This causes a couple of issues:
1. Most .gitignore files will exclude all of Library, including the default one provided at https://github.com/github/gitignore/blob/main/Unity.gitignore
This can be fixed by modifying .gitignore, but Library files aren't generally expected to be tracked.
2. ParrelSync does not sync this file. This isn't critical as the cloned instance can't modify any files anyway, but it does cause some console spam when FishNet attempts to process prefabs that should have been excluded.

Ideally this file would be stored somewhere in the project. It looks like maybe that's the plan for FN config?

**Comment by FirstGearGames** [comment]
This is on the road map. It's something that will be done soon enough.
