### ISSUE TITLE
Missing Correct Writer and Reader For UnloadOptions and UnloadQueueData - SceneManagement

### ISSUE THREAD

**Issue by Katerlad** [FirstGearGames/FishNet#175]
https://discord.com/channels/424284635074134018/1054425498928816268

!!! I believe that UnloadQueueData needs to be fixed as well to include the ScopeType !!! 

Per our Discord Conversation in FishNet..

**Comment by Katerlad** [comment]
Looked into LoadSceneOptions as well, and I see that the writer and reader are not sending any load options as well just constructing a new one. 

I believe the client will need to know the Options.AutomaticallyUnload to handle properly unloading or loading global scenes if the client host.

I would ask that all of this data be carefully examined to catch anything else that I am missing as well.

**Comment by FirstGearGames** [comment]
Resolved in 3.1.

**Comment by Katerlad** [comment]
Hey Hey, I checked 2.6.6 and it doesnt appear that the SceneReadersWriters.cs contains the fix yet. Just wanted to make sure it didnt slip by in 3.1 as well. Unless I am missing something.
