### ISSUE TITLE
IsLocalClient giving incorrect value on host

### ISSUE THREAD

**Issue by maxkratt** [FirstGearGames/FishNet#180]
It would appear that `base.Owner.IsLocalClient` is returning false in OnStartNetwork when running from the host client. This is occurring on the player object spawned by the PlayerSpawner component.
This happens in FishNet 2.6.5 while in FishNet version 2.5.10 it returns true as expected.

**Comment by FirstGearGames** [comment]
Resolved and released in 2.6.6
