### ISSUE TITLE
Custom Network Pool for player nobs workaround example [Example Request]

### ISSUE THREAD

**Issue by SnaiperoG3D** [FirstGearGames/FishNet#181]
Hi, its a example request how to work with pool and ownership. There are many questions what hard to find how it works without tests. If the moment with giving ownership easy to find but how to remove it i hard to understand, cuz there is no info when fishnet callbacks are calling, onRemoteConnectionState, OnPreDestroyClientObjects, started, stopped, etc... is object already despawned when these method are called or not, is ownership will removed by fishnet or not. As i found when OnPreDestroyClientObjects, arg conn.FirstObject is null, so i cant remove ownership here. When onRemoteConnectionState called [server] method not work, fishnet tells me that server is not active, so i just can understand where and when i need to remove ownership from player nob before it goes into pool and where and when i need to reset all my scrips variables before it will goes into pool. Also resets need to do on clients too. Its good to have some sort of example with custom network pool, lets say custom pool with pre spawned objects count, and all this workaround. Reset player variables on server before pool, reset player variables on clients before pool, remove ownership from player nob, etc...

**Comment by FirstGearGames** [comment]
With pooling assume everything will behave exactly as it were a new object. The only difference is at the end instead of destroying it's disabled. Otherwise, everything is reset fresh when pooled.
