### ISSUE TITLE
Global Scenes are Stacking When using Host Setup or Dedicated Server Setup

### ISSUE THREAD

**Issue by Katerlad** [FirstGearGames/FishNet#209]
Unity version:
Fish-Networking version: 2.6.6

**Describe the bug**
When Loading Scenes Globally, and AllowStacking = true, the server will stack a global scene. (You will see two of the same scene loaded in the hierarchy in unity on the Host or Server) The client will still only have the one global instance loaded.

**To Reproduce**
Trigger this code twice:
```csharp
        SceneLoadData sld = new SceneLoadData("GameScene");
        sld.ReplaceScenes = ReplaceOption.All;
        sld.Options.AllowStacking = true;
        InstanceFinder.SceneManager.LoadGlobalScenes(sld);
```

**Expected behavior**
I Expect that the Server/Host will not load a second global scene when allow stacking is true. 
I also expect a Debug warning that states "You tried to stack a global scene, and this is not allowed"

Inspecting the code it seems that it may be simple enough to add this check to CanLoadScene() to check if already loaded and a global scene. currently it is not doing so. 

Updating documentation to be direct that global scenes cannot be stacked as well.

**Comment by FirstGearGames** [comment]
Blocked in 3.1.1
