### ISSUE TITLE
Errors when importing Mirror and Fishnet together

### ISSUE THREAD

**Issue by maxkratt** [FirstGearGames/FishNet#214]
Unity version: 2021.3.16f1
Fish-Networking version: 2.6.6
Mirror version: 71.0.0

**Describe the bug**
When attempting to convert a Mirror project to FishNet and when FishNet and Mirror are both imported, there are these errors:
- `Assets\FishNet\Upgrading\MirrorUpgrade.cs(17,68): error CS0234: The type or namespace name 'NetworkTransformBase' does not exist in the namespace 'Mirror.Experimental' (are you missing an assembly reference?)`

- `Assets\FishNet\Upgrading\MirrorUpgrade.cs(18,69): error CS0234: The type or namespace name 'NetworkTransformChild' does not exist in the namespace 'Mirror.Experimental' (are you missing an assembly reference?)`

**To Reproduce**
1. Import Mirror v71.0.0
2. Import FishNet v2.6.6

**Expected behavior**
No errors :)

**Comment by FirstGearGames** [comment]
This is indeed caused from Mirror breaking things. It will be resolved in 3.1.1
