### ISSUE TITLE
Feature request: move NetworkBehaviour to another NetworkObject

### ISSUE THREAD

**Issue by player1serg** [FirstGearGames/FishNet#22]
Useful when using DistanceCondition and NetworkBehaviour was moved far away from it NetworkObject.

**Comment by FirstGearGames** [comment]
Can you please elaborate more? I'm not quite understanding what your use is for this recommendation.

**Comment by player1serg** [comment]
Sorry for the misunderstanding. I am not native English.
In short, I need a function for NetworkBehaviour where i can change current NetworkObject to another.

I have Room1(NetworkObject) and Room2(NetworkObject). Each of them has an Observer with DistanceCondition.
Ball(NetworkBehaviour) is now owned by Room1 and is located next to it.
Player1 (NetworkObject) is object owned by NetworkConnection1 and is located next to Room2.

DistanceCondition(NetworkConnection1, Room1) returns false.
DistanceCondition(NetworkConnection1, Room2) returns true.

Now NetworkConnection1 only receives changes from NetworkBehaviours in Room2.
Ball starts moving from Room1 to Room2. At some point, Ball will be within the radius of Room2, but it still send changes only to Room1!
So NetworkConnection1 will not receive changes from Ball although it should.
To fix this, I need to change NetworkObject for Ball when it leaves Room1 radius and enters Room2 radius.

**Comment by FirstGearGames** [comment]
Okay, I think I understand. I'm not sure this needs a new feature to be plausible, fairly sure it can be done already. Can you message me on Discord? FirstGearGames#0001

**Comment by player1serg** [comment]
Yeah, I have already done this, but I'm not sure that I checked everything and it will work after future updates.

I removed My object from NetworkBehaviours array of old NetworkObject and added it to the new one. To do this, I changed the type of NetworkBehaviours from an array to a list. Also I call NetworkBehaviour.PreInitialize on it after the move. Does anything else need to be done?
