### ISSUE TITLE
Spawn Nested Network Objects at Runtime? 

### ISSUE THREAD

**Issue by Katerlad** [FirstGearGames/FishNet#224]
Unity version:
Fish-Networking version:3.1.3 & 2.6.6

**Describe the bug**
Cannot Spawn a Network Object as Nested under an Already Spawned Network Object.

**To Reproduce**
Spawn a Parent prefab. 
```csharp
NetworkObject parentNob = Instantiate(parentPrefab);
Spawn(parentPrefab);
```
Spawn a prefab as child under parentPrefab.

```csharp
NetworkObject nestedNob = Instantiate(nestedPrefab, parentNob) // <= assigned parentNob as Parent
Spawn(nestedNob);
```

**Expected behavior**
I cannot tell if this is suppose to be possible and its a bug, or if this is a feature request.

I expected this to Spawn my nested NOB as a child of the parent nob on the client. Instead it spawns it as a root. 

## Deep Dive

I noticed that in the Spawn() mehod on the serverobjects class, It does not check if any of its parents up the hierarchy, is a network object, and it does not assign the isNested bool, or assign the parent.

In my case the direct parent was not a NetworkObject, it was 2 Parents up the chain.

Is this a bug? or a feature not yet implemented?

**Comment by FirstGearGames** [comment]
This should work. Can you try instantiating alone, then use SetParent before spawning?

**Comment by Katerlad** [comment]
Tried using SetParent today and still the same behaviour, as far as I can tell nothing in Fishnet sets the IsNested bool when setting the parent manually on the server, but I could be missing it.

**Comment by AaronTaube** [comment]
We are also running into the exact same thing.

**Comment by FirstGearGames** [comment]
Sorry it's taken so long to revisit this. I'll at the very least check into it before I release 3.5.2.

**Comment by FirstGearGames** [comment]
Couldn't replicate on 3.5.1, but the spawning is the same for 3.4.3.

Code used...
```cs
using FishNet.Object;

namespace FishNet.Testing.UserReported
{

    public class SpawnerTest : NetworkBehaviour
    {
        public bool SpawnParent;
        public bool SpawnChild;
        public bool SpawnBoth;

        public NetworkObject ParentPrefab;
        public NetworkObject ChildPrefab;

        private NetworkObject _parentSpawned;
        private NetworkObject _childSpawned;

        private void Update()
        {
            if (SpawnParent)
            {
                SpawnParent = false;
                SpawnParentLocal();
                return;
            }

            if (SpawnChild)
            {
                SpawnChild = false;
                SpawnChildLocal();
                return;
            }


            if (SpawnBoth)
            {
                SpawnBoth = false;
                SpawnParentLocal();
                SpawnChildLocal();
                return;
            }

            void SpawnParentLocal()
            {
                if (_parentSpawned != null)
                    base.Despawn(_parentSpawned);

                _parentSpawned = Instantiate(ParentPrefab);
                base.Spawn(_parentSpawned);
            }

            void SpawnChildLocal()
            {
                if (_parentSpawned == null)
                    return;
                if (_childSpawned != null)
                    base.Despawn(_childSpawned);

                _childSpawned = Instantiate(ChildPrefab, _parentSpawned.transform);
                base.Spawn(_childSpawned);
            }

        }


    }
}
```
