### ISSUE TITLE
Scene Objects with Observer Conditions seem to have issues

### ISSUE THREAD

**Issue by hudmarc** [FirstGearGames/FishNet#238]
Unity version:
2.x ~ 3.0.0

**Describe the bug**
It's hard to tell what's causing the bug because it seems to happen at random, but it could potentially be related to saving the scene or changing prefabs and then saving the scene.

It happens with scene objects with NetworkObjects which get a NetworkObserver component automatically added to them. It might be related to however FN indexes scene objects - maybe it is relying on an internal index Unity provides, but this internal index can change under certain conditions?

**To Reproduce**
It's difficult to know exactly what causes this bug. When I've experienced it though it's always caused by scene objects with the Network Object component which then get an ObserverCondition automatically added to them on start.

**Expected behavior**
That ObserverConditions on scene Objects would behave similarly to ObserverConditions on Prefabs

**Comment by FirstGearGames** [comment]
This could be related to the observer fixes for timed conditions on nested prefabs or scene objects.
If you have access to the closed-testing channel you can find a release there with fixes. Otherwise, an official release is expected within a week.
