### ISSUE TITLE
Scene switching and distance condition used together do not disable scene child networkObjects

### ISSUE THREAD

**Issue by FREEZX** [FirstGearGames/FishNet#239]
Unity version: 2022.2.2f1
Fish-Networking version: 3.1.5 Pro

**Describe the bug**
Child scene NetworkObjects not getting disabled if using DefaultScene scene switching and DistanceCondition together. 

**To Reproduce**
Here is a reproduction project:
https://nextcloud.dark-1.com/s/qqswELW5d6oyGsX
1. Open Scenes/ReproOfflineScene
2. Start server and start client quickly in succession
3. Observe that only 2 of the 3 boxes are getting disabled after a 10s delay.
4. Remove SceneCondition in networkManager
5. Observe that all boxes are getting disabled after a 10s delay.
6. Open StandaloneScene
7. Start server and client
8. Observe that all boxes are getting disabled after a 10s delay

**Expected behavior**
All boxes should be getting disabled regardless of conditions

**Comment by FirstGearGames** [comment]
Have not taken a look at your project yet but I'm curious about the 'start quickly in succession' part. That should have no bearing on the outcome.

Is this happening as separate client/server or clientHost?

Objects will be disabled if client meets observer conditions as well. I tried removing all conditions and things were appropriate visible.


On a scene object I added a SceneCondition w/ ignore manager. Child, no conditions but ObserverManager added Scene and DistanceCondition. Both appeared / disappeared properly.

**Comment by FREEZX** [comment]
The project is a very minimal reproduction case, I suggest you take a look. For quickly in succession, I mean quick enough so the object doesn't disappear by itself as it has a 10s timer that disables itself.

**Comment by FREEZX** [comment]
The issue seems to happen if you are a host only. I had tried debugging and there is a piece of despawn code that expects to execute as both server and client, but in this circumstance is called only on the server, which skips disabling the object because the server is also a client.

**Comment by FREEZX** [comment]
I debugged while trying to figure out the culprit and I think the issue is that `ManagedObjects.Despawn` is only getting called once on the host with `isServer = true` in this case, which does not disable the object.

**Comment by FREEZX** [comment]
Something even more interesting is happening if connecting through another unity instance as a client, this child object does not even get spawned.

**Comment by FirstGearGames** [comment]
Resolved in 3.2.1 (currently in closed testing)
