### ISSUE TITLE
Not used variable in SyncObject example

### ISSUE THREAD

**Issue by kamyker** [FirstGearGames/FishNet#241]
What's the point of asClientAndHost if it's not used, I guess it can be used for something that isn't shown in the example?
https://github.com/FirstGearGames/FishNet/blob/bef7bd71ec2bcfdbf6d1068885230a2c4c2eff5f/Assets/FishNet/Example/All/CustomSyncType/Custom%20Struct%20Sync/StructySync.cs#L201

https://github.com/FirstGearGames/FishNet/blob/bef7bd71ec2bcfdbf6d1068885230a2c4c2eff5f/Assets/FishNet/Example/All/CustomSyncType/Custom%20Struct%20Sync/StructySync.cs#L193-L231

**Comment by FirstGearGames** [comment]
That was probably copied from one of the existing syncobject types, I used them as a template.
I'm going to actually rework the custom sync example to be easier to use/follow.

**Comment by FirstGearGames** [comment]
Closing out since this is being reworked anyway.
