### ISSUE TITLE
Error in Unity Version 2022.2 using .NET Framework

### ISSUE THREAD

**Issue by phillipreagan** [FirstGearGames/FishNet#249]
Unity version: 2022.2.5f1
Fish-Networking version: 3.1.6 and 3.2.1 

**Describe the bug**
When using Unity version 2022.2.* and switching to .NET Framework (from .NET Standard 2.1) an error occurs when Unity processes the FishNet.Example assembly. I have tracked the "cause" of this error down to a specific method in GeneralHelper.cs called GetGenericQueues. There seems to be something about the reflection going on with the Queue type that causes the errors I'm seeing in other parts of the code. If I change the below line in GetGenericQueues, the errors will go away.
_Original:_
`TypeReference queueDataTr = base.ImportReference(typeof(Queue<>));`
_Modified to List type:_
`TypeReference queueDataTr = base.ImportReference(typeof(List<>));`

Granted, I don't fully understand what all this code is doing so the problem may originate even deeper than this. I was simply trying to fix the error and stumbled upon this. I'm hoping this can give some insight into an actual fix.

**To Reproduce**
1. Create a new empty project in 2022.2.5f1
2. Import Fish-Networking package (it will import without error).
3. Switch the "Api Compatability Level" in Project Settings->Player from ".NET Standard 2.1" to ".NET Framework" 
![API](https://user-images.githubusercontent.com/879769/216670811-2080df7a-e5bd-41e5-ad1a-442ecd4faaac.png)
4. Observe the error in the console that now appears
![Error](https://user-images.githubusercontent.com/879769/216670946-ff5ea630-7803-45ad-9a1f-611a56a805db.png)

**Expected behavior**
Switching to .NET Framework should not cause errors.

**Comment by FirstGearGames** [comment]
Possibly another Unity bug. I'll keep this in mind and try to repo.

**Comment by FirstGearGames** [comment]
Confirmed not a FN bug. My hands are tied until I get more feedback from Cecil. Seems Unity broke something good, hoping Cecil team can resolve.

**Comment by bitmammoth** [comment]
It seems Unity version 2022.2.11f fixes this or something along those lines happened because it works in my project now.

**Comment by FirstGearGames** [comment]
Well that is fantastic. What version of FN did you import?

**Comment by phillipreagan** [comment]
When I tried, I was still seeing the error with Unity 2022.2.11f. However, I updated to FN 3.6.0 Experimental Pro version and the error is now gone. Looks like the GetGenericQueues method that was causing the error has been replaced by GetGenericBasicQueue and is using the BasicQueue type instead of Queue like before. Everything seems to be working fine now!
