### ISSUE TITLE
FN Configuration editor/window freezes editor

### ISSUE THREAD

**Issue by viliwonka** [FirstGearGames/FishNet#255]
Unity version:
Fish-Networking version: 3.3.1

**Describe the bug**
Opening FishNet Configuration sometimes freezes editor, sometimes.

**To Reproduce**
1. Fish-Networking
2. Configuration

OR

1. Inside Unitys Project Settings
2. Fish-Networking
3. Configuration

**Expected behavior**
No freeze

**Screenshots**
![image](https://user-images.githubusercontent.com/4028544/218119356-37e1b54f-fbc0-4a0f-9fc8-c2b733b64b07.png)

**Temp Fix**
Disabling Configuration window via return function

**Comment by FirstGearGames** [comment]
What do you mean disable via return function?

**Comment by viliwonka** [comment]
I meant disabling the "config" function, so that the FN editor config code doesn't ever run.

This one:
![image](https://user-images.githubusercontent.com/4028544/218408922-dadbdcb0-831a-4997-a12e-c760137d4c90.png)

**Comment by viliwonka** [comment]
Hi - this might have been a lie - a FN prefab config editor window also caused same freeze to me right now.

**Comment by viliwonka** [comment]
Ok, I tried it again, and watched Editor.log while the Loading Bar "froze the editor"

This at the end of the Editor.log:

> Skipping module "C:\Program Files\Unity\Hub\Editor\2022.2.5f1\Editor\Data\Resources\PackageManager\ProjectTemplates\libcache\com.unity.template.universal-2d-2.1.1\BurstCache\JIT\c929b2f20ad5fb885fcf42465f53bcbc.dll" (BadImageFormat: probably not a .NET dll)
Could not load image C:\Program Files\Unity\Hub\Editor\2022.2.5f1\Editor\Data\Resources\PackageManager\ProjectTemplates\libcache\com.unity.template.universal-2d-2.1.1\BurstCache\JIT\f5697730a2a149f99ba89514b9b6414c.dll due to Invalid data directory 0
Run the peverify utility against this for more information.
Skipping module "C:\Program Files\Unity\Hub\Editor\2022.2.5f1\Editor\Data\Resources\PackageManager\ProjectTemplates\libcache\com.unity.template.universal-2d-2.1.1\BurstCache\JIT\f5697730a2a149f99ba89514b9b6414c.dll" (BadImageFormat: probably not a .NET dll)
Could not load image C:\Program Files\Unity\Hub\Editor\2022.1.15f1\Editor\Data\Resources\PackageManager\Server\node_modules\@edt\proxy-helper\build\Release\NativeProxyHelper.dll due to Metadata verifier doesn't handle sections with SizeOfRawData < VirtualSize
Run the peverify utility against this for more information.
Skipping module "C:\Program Files\Unity\Hub\Editor\2022.1.15f1\Editor\Data\Resources\PackageManager\Server\node_modules\@edt\proxy-helper\build\Release\NativeProxyHelper.dll" (BadImageFormat: probably not a .NET dll)
Could not load image C:\Program Files\Unity\Hub\Editor\2022.2.5f1\Editor\Data\Resources\PackageManager\Server\node_modules\@edt\proxy-helper\build\Release\NativeProxyHelper.dll due to Metadata verifier doesn't handle sections with SizeOfRawData < VirtualSize
Run the peverify utility against this for more information.
Skipping module "C:\Program Files\Unity\Hub\Editor\2022.2.5f1\Editor\Data\Resources\PackageManager\Server\node_modules\@edt\proxy-helper\build\Release\NativeProxyHelper.dll" (BadImageFormat: probably not a .NET dll)
Asset Pipeline Refresh (id=6c6300c684f226b40a422b0ade035240): Total: 0.027 seconds - Initiated by RefreshV2(AllowForceSynchronousImport)
Asset Pipeline Refresh (id=18dcc57c3a8b0674b9d7b5ec09d9185c): Total: 0.029 seconds - Initiated by RefreshV2(AllowForceSynchronousImport)

Ignore the paths of the DLLs, it's basically 18000 lines of those "could not load image" errors, but this is what is causing the freezes of the configuration.

**Comment by viliwonka** [comment]
Update: I upgraded Unity to 2022.1.15f1, issue is mostly resolved now - still blocked by those error messages but it takes only few seconds. I think the issue can be closed.

**Comment by viliwonka** [comment]
Follow up:

* upgrading unity did not resolve the issue
* via deep profiling I saw XMLSerializer is root of the issues used inside Configuration (for loading/saving)
