### ISSUE TITLE
Oculus build error

### ISSUE THREAD

**Issue by zhongxiaoerbao1025** [FirstGearGames/FishNet#256]
I used 3.3.0 and 3.3.1 to build oculus app, unity build error:
Building Library\Bee\artifacts\Android\d8kzr\f57k_bly-CSharp.o failed with output:
E:...\Library\Bee\artifacts\Android\il2cppOutput\cpp\Assembly-CSharp.cpp(12849,3): error: no matching function for call to 'GeneratedWriters___Internal_Write___System_Collections_Generic_Dictionary_2U3CSystem_Int32U2CSystem_SingleU3EFishNet_Serializing_Generated_mC66156A37282AD027219EBAA953B521DC1B848F4'

but used 2.6.6 to build is succuss.

**Comment by FirstGearGames** [comment]
Should be resolved in 3.3.2. It's released already and a package is being uploaded now.
