### ISSUE TITLE
Codegen: Different asm inheritence of NB w/ Awake throws

### ISSUE THREAD

**Issue by FirstGearGames** [FirstGearGames/FishNet#26]
When NetworkComponent is in a user assembly and PlayerMotor is not codegen throws **IEnumerator Awake methods are not supported within NetworkBehaviours**
`public abstract class NetworkComponent : NetworkBehaviour, IComponent {}`
`public class PlayerMotor : NetworkComponent
{
      private void Awake() {}
}`

**Comment by FirstGearGames** [comment]
I wasn't able to reproduce. I've requested more information from the reporter. Issue will be closed until able to reproduce.

**Comment by AustinEast** [comment]
Figured out the missing repro step - the errors start when you create a *second* `NetworkComponent` sub-class. For example:

`public class TestComponentA : NetworkComponent { }`
`public class TestComponentB : NetworkComponent { }`

**Comment by FirstGearGames** [comment]
Reproduced, thanks.

**Comment by FirstGearGames** [comment]
> Figured out the missing repro step - the errors start when you create a _second_ `NetworkComponent` sub-class. For example:
> 
> `public class TestComponentA : NetworkComponent { }` `public class TestComponentB : NetworkComponent { }`

The error popped once then after I cleared it I could not reproduce. I checked the generated code and it looks correct. Are the errors showing every time for you?

**Comment by FirstGearGames** [comment]
Resolved in 1.4.5.
