### ISSUE TITLE
Sync type SyncTimer doesnt pause correctly on server side.

### ISSUE THREAD

**Issue by Dolpix-git** [FirstGearGames/FishNet#261]
Unity version: 2022.2.3f1 <DX11>
Fish-Networking version: 3.3.0. Pro

**Describe the bug**
I pause the timer on the server side, and it pauses for clients, but not the server its self. I call PauseTimer() with nothing passed in. I have double-checked that I am not starting the timer somewhere else. I am still updating the timer in update.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a sync Timer.
2. call start on server side.
3. call pause on button down.
4. create an if (not paused) then (debug log the time).

**Expected behaviour**
The clients should not see the timer updating any more, but the server does.

**Added note**
I have not checked if the completed timer is called, even if it's sudo paused on clients (and possibly on server?)

**Comment by FirstGearGames** [comment]
Not yet tested but sounds like a bug.

**Comment by FirstGearGames** [comment]
Fixed in 3.5.2
