### ISSUE TITLE
Reading SyncObject value from client won't return the updated value

### ISSUE THREAD

**Issue by axvemi** [FirstGearGames/FishNet#264]
Unity version: 2021.3.19f1
Fish-Networking version: 3.4.1

**Describe the bug**
Following the Custom Struct Sync example (https://github.com/FirstGearGames/FishNet/tree/main/Assets/FishNet/Example/All/CustomSyncType/Custom%20Struct%20Sync)

If you try to read the value on the update as a client, it will always return 0. It works if you do it on the OnChange method.

**To Reproduce**
1. Prepare to run those two example classes
2. On the update method put the following code:

`if (Input.GetKeyDown(KeyCode.P))
{
Debug.Log("Structy age value as server: " + StructySync.GetValue(true).Age);
Debug.Log("Structy age value as client" + StructySync.GetValue(false).Age);
}`

3. When you print the value from the client, it won't return the updated value.

**Expected behavior**
It should return the updated value.

**Comment by FirstGearGames** [comment]
I assume you're using a separate server and client?

**Comment by axvemi** [comment]
Tried:
One hosting as a client and server, and connecting another client to it
One hosting as only server, and connecting a client to it.

In both cases I got the same result

**Comment by FirstGearGames** [comment]
This is a bug in the example. It seems the Read override is not assigning to the value fields. Can fix it up pretty easily.

**Comment by FirstGearGames** [comment]
Reworked StructySync example.
