### ISSUE TITLE
ClientManager.Connection.Scenes doesn't change after loading scene

### ISSUE THREAD

**Issue by Maclay74** [FirstGearGames/FishNet#268]
Unity version: 2022.2
Fish-Networking version: 3.3.4

**Describe the bug**
After server loaded client into a scene, `ClientManager.Connection.Scenes` doesn't get updated accordingly. 

**To Reproduce**
On server:
```cs
SceneLoadData sld = new SceneLoadData(sceneName);
_networkManager.SceneManager.LoadConnectionScenes(conn, sld);
```

On client:
```cs
Debug.Log(InstanceFinder.ClientManager.Connection.Scenes.Count) // keeps 0
```

**Expected behavior**
`InstanceFinder.ClientManager.Connection.Scenes` should contain scenes the current client is in

**Comment by Maclay74** [comment]
Also, I noticed that `unloadEvent.UnloadedScenes[0].name` is null when `OnUnloadEnd` fires. 
`loadEvent.LoadedScenes[0].name` has correct scene name.

**Comment by FirstGearGames** [comment]
You'll want to file a separate bug report for the unload thing, though it may not actually be a bug; could be intentional. Cannot say without investigating but please do file another report specific for it.

A quick glance at the code looks like client side may not be updating scenes collection.

**Comment by FirstGearGames** [comment]
Resolved in 3.5.2.

**Comment by Maclay74** [comment]
Great, thank you!

**Comment by FirstGearGames** [comment]
Note: this is for conn.Scenes not populating on clients only. If the other thing is a bug please make a new issue.
