### ISSUE TITLE
TransportIdData could not be found for Multipass connectionI with Latency Simulator Enabled

### ISSUE THREAD

**Issue by KZkici** [FirstGearGames/FishNet#269]
Unity version: 2021.3.19f1
Fish-Networking version: 3.4.2.pro

Tugboat transport for localhost testing
Latency simulator enabled with 100 ms

Build Windows
Start Editor as Host
Windows build join as client 
Windows build disconnects
Editor Host throws error:

TransportIdData could not be found for Multipass connectionId of 1.
0x00007ff7f3afb56d (Unity) StackWalker::GetCurrentCallstack
0x00007ff7f3b02129 (Unity) StackWalker::ShowCallstack
0x00007ff7f4a894e3 (Unity) GetStacktrace
0x00007ff7f513678d (Unity) DebugStringToFile
0x00007ff7f2c5c212 (Unity) DebugLogHandler_CUSTOM_Internal_Log
0x000002f3eafa1b83 (Mono JIT Code) (wrapper managed-to-native) UnityEngine.DebugLogHandler:Internal_Log (UnityEngine.LogType,UnityEngine.LogOption,string,UnityEngine.Object)
0x000002f3eafa1abb (Mono JIT Code) UnityEngine.DebugLogHandler:LogFormat (UnityEngine.LogType,UnityEngine.Object,string,object[])
0x000002f40e185810 (Mono JIT Code) UnityEngine.Logger:Log (UnityEngine.LogType,object)
0x000002f50c78c0e5 (Mono JIT Code) UnityEngine.Debug:LogError (object)
0x000002f50c78c08b (Mono JIT Code) [LevelLoggingConfiguration.cs:129] FishNet.Managing.Logging.LevelLoggingConfiguration:LogError (string) 
0x000002f50c78c034 (Mono JIT Code) [NetworkManager.Logging.cs:117] FishNet.Managing.NetworkManager:LogError (string) 
0x000002f4f87ae89b (Mono JIT Code) [Multipass.cs:439] FishNet.Transporting.Multipass.Multipass:SendToClient (byte,System.ArraySegment`1<byte>,int) 
0x000002f49984c6c2 (Mono JIT Code) [LatencySimulator.cs:314] FishNet.Managing.Transporting.LatencySimulator:<IterateOutgoing>g__IterateCollection|27_0 (System.Collections.Generic.List`1<FishNet.Managing.Transporting.LatencySimulator/Message>,FishNet.Transporting.Channel,FishNet.Managing.Transporting.LatencySimulator/<>c__DisplayClass27_0&) 
0x000002f49984c4bb (Mono JIT Code) [LatencySimulator.cs:325] FishNet.Managing.Transporting.LatencySimulator:IterateOutgoing (bool) 
0x000002f49984bd43 (Mono JIT Code) [TransportManager.cs:644] FishNet.Managing.Transporting.TransportManager:IterateOutgoing (bool) 
0x000002f4998489a3 (Mono JIT Code) [TimeManager.cs:974] FishNet.Managing.Timing.TimeManager:TryIterateData (bool) 
0x000002f4998484ab (Mono JIT Code) [TimeManager.cs:686] FishNet.Managing.Timing.TimeManager:IncreaseTick () 
0x000002f499848003 (Mono JIT Code) [TimeManager.cs:344] FishNet.Managing.Timing.TimeManager:<TickUpdate>g__MethodLogic|96_0 () 
0x000002f499847e73 (Mono JIT Code) [TimeManager.cs:331] FishNet.Managing.Timing.TimeManager:TickUpdate () 
0x000002f499847ccb (Mono JIT Code) [NetworkReaderLoop.cs:29] FishNet.Transporting.NetworkReaderLoop:Update () 
0x000002f4ddda5368 (Mono JIT Code) (wrapper runtime-invoke) object:runtime_invoke_void__this__ (object,intptr,intptr,intptr)
0x00007ffc5f6ffeb4 (mono-2.0-bdwgc) [mini-runtime.c:3445] mono_jit_runtime_invoke 
0x00007ffc5f63e764 (mono-2.0-bdwgc) [object.c:3066] do_runtime_invoke 
0x00007ffc5f63e8fc (mono-2.0-bdwgc) [object.c:3113] mono_runtime_invoke 
0x00007ff7f3a1ff04 (Unity) scripting_method_invoke
0x00007ff7f39ff704 (Unity) ScriptingInvocation::Invoke
0x00007ff7f39e8804 (Unity) MonoBehaviour::CallMethodIfAvailable
0x00007ff7f39e88f2 (Unity) MonoBehaviour::CallUpdateMethod
0x00007ff7f34d3b8b (Unity) BaseBehaviourManager::CommonUpdate<BehaviourManager>
0x00007ff7f34dab6a (Unity) BehaviourManager::Update
0x00007ff7f36edc3d (Unity) `InitPlayerLoopCallbacks'::`2'::UpdateScriptRunBehaviourUpdateRegistrator::Forward
0x00007ff7f36d429a (Unity) ExecutePlayerLoop
0x00007ff7f36d4426 (Unity) ExecutePlayerLoop
0x00007ff7f36da4e9 (Unity) PlayerLoop
0x00007ff7f463c099 (Unity) PlayerLoopController::UpdateScene
0x00007ff7f463a29b (Unity) Application::TickTimer
0x00007ff7f4a8f67a (Unity) MainMessageLoop
0x00007ff7f4a93f4b (Unity) WinMain
0x00007ff7f5e5b05e (Unity) __scrt_common_main_seh
0x00007ffd555826bd (KERNEL32) BaseThreadInitThunk
0x00007ffd5716dfb8 (ntdll) RtlUserThreadStart

**Comment by FirstGearGames** [comment]
Found missing step > player prefab must be specified.

**Comment by FirstGearGames** [comment]
Seems this might be more of a situation where the error should be hidden. It occurs because a packet is being held for processing locally while the disconnect happens immediately over the socket. When the packet gets processed it's for a connection that no longer exists.

This cannot occur in an actual environment because packets wont be held locally to simulate latency and once the connection closes no more packets will arrive for that connection. If anything I just need to purge the simulator of a connections packet when they drop.

So this is definitely a bug but harmless. Will resolve when able.

**Comment by FirstGearGames** [comment]
Fixed in 3.5.2.
