### ISSUE TITLE
Networked pooled object is missing OnStartClient call

### ISSUE THREAD

**Issue by tartarusdev** [FirstGearGames/FishNet#273]
Unity version: 2021.3.9f1
Fish-Networking version: 3.4.3. Pro

**Describe the bug**
When a NetworkObject is despawned with type pool the same frame as you spawn a new one and it reuses the newly despawned object there is no OnStartClient called on the client. 

**To Reproduce**
Steps to reproduce the behaviour:
1. [Server] Get a pooled object with NetworkManager.GetPooledInstantiated
2. [Server] Spawn the networked object
3. [Client] The networked object starts and runs for a while
4. [Server] Despawn the pooled object with DespawnType.Pool
5. [Server] In the same frame as the server calls despawn use NetworkManager.GetPooledInstantiated again (This gets the same NetworkObject  as the one we just despawned earlier this frame and the same one that is still alive on the client)
6. [Server] Spawn the networked object 
7. [Client] Doesn't get the OnStartClient call

**Expected behaviour**
The client gets a despawn(OnStopClient) first then a complete respawn of the networked object with OnStartClient

**Comment by FirstGearGames** [comment]
This is clientHost or client only?

**Comment by tartarusdev** [comment]
It's the same in clientHost, clientHost/client and server/client. Not a 100% sure it only happens when its the same frame though. But everytime its on the same frame it never triggers the client side of things.

**Comment by FirstGearGames** [comment]
I was not able to replicate in 3.5.2.Experimental. Can you make a backup then update and try again?

Or first try this script to see if it's failing.

No observer conditions were used. No player object.
```cs
//Placed on a scene object.
using FishNet.Object;
using UnityEngine;

namespace FishNet.Testing.ClientStartCallbacks
{
    public class DespawnAndSpawn : NetworkBehaviour
    {
        public NetworkObject Prefab;
        private NetworkObject _spawned;

        private void Update()
        {
            if (!base.IsServer)
                return;

            if (Input.GetKeyDown(KeyCode.S))
            {
                if (_spawned != null)
                    _spawned.Despawn();
                _spawned = Instantiate(Prefab);
                Debug.Log("Spawning....");
                base.Spawn(_spawned);
            }
        }
    }

}```

```cs
//Played on a new prefab. Prefab is set on DespawnAndSpawn within scene object.
using FishNet.Object;
using UnityEngine;

namespace FishNet.Testing.ClientStartCallbacks
{
    public class PrintStart : NetworkBehaviour
    {
        public override void OnStartClient()
        {
            base.OnStartClient();
            Debug.Log("OSC Called");
        }
    }

}
```

**Comment by FirstGearGames** [comment]
Realized I was not pulling from 'GetPooledInstantiated' but even after updating script (edited my post too) it will worked.

**Comment by tartarusdev** [comment]
Ok, I'll get back to you tomorrow when I have the ability to test it out.

**Comment by tartarusdev** [comment]
Ok, tested your code today and it worked. So looked around some more a found that I actually had the ObserverManager active with an observer using a 1 second update frequency.
When I disable that it started working.

So I probably have some weird issue with the observer code or it doesn't recognize the respawned object as a "new" one and keeps it deactivated until the next observer tick.

**Comment by FirstGearGames** [comment]
Still needs to be looked at. You're using a custom condition or?

**Comment by tartarusdev** [comment]
I use a custom one based on DistanceCondition. But I tried swapping over to the provided DistanceCondition and it worked with that one until I change the Update Frequencey to 1.

Don't think it is only happening if you spawn/respawn the same frame anymore though.

**Comment by FirstGearGames** [comment]
Were you able to find a definitive way to reproduce this? I've still been unsuccessful.

**Comment by tartarusdev** [comment]
I did a bunch of testing now and I'm quite sure it's not an issue with the same frame spawn/respawn. 

The easiest way to reproduce it is:
1. Start as Host to skip building while testing(not needed since it's the same no matter configuration)
2. Setup the NetworkManager as follows
![image](https://user-images.githubusercontent.com/15339885/226192352-8625d8ad-df9b-4a56-8f94-71ff7aaf17e1.png)
3. The player prefab is as follows 
![image](https://user-images.githubusercontent.com/15339885/226194723-8dc64788-05f4-48cf-9d00-16577a284c1c.png)
5. Change the frequency of the DistanceCondition as follows
![image](https://user-images.githubusercontent.com/15339885/226192593-ec91c7c7-8f18-43e6-82f5-f35c88342154.png)
6. Start the game and press S to spawn a object.
7. Press it once again after lets say 1 second

Result:
Depending on when you clicked and how many times you clicked it will miss the stop and eventually get the start of the last object that was spawned.

Also:
If you for some reason despawn it on the server before the client acknowledge the new start it will just vanish in thin air on the client since it seems the update frequency needs to tick once before it will be made available (Could be wrong about this).

Here is some modified version of your code that I used to test it with.

 ```csharp
using FishNet.Object;
using FishNet.Utility.Extension;
using UnityEngine;

public class DespawnAndSpawn : NetworkBehaviour
{
	public NetworkObject Prefab;
	private NetworkObject _spawned;
	public TMPro.TextMeshProUGUI Text;

	private int spawns = 0;

	private void Update()
	{
		Text.text = "Spawns: " + spawns + "\nStarts Server: " + PrintStart.startsServer + "\nStarts Client: " + PrintStart.startsClient;
		
		if (!IsServer)
			return;

		if (Input.GetKeyDown(KeyCode.S))
		{
			SpawnObject();
		}
		
		if (Input.GetKeyDown(KeyCode.D))
		{
			DespawnObject();
		}
	}

	private void SpawnObject()
	{
		DespawnObject();

		_spawned = NetworkManager.GetPooledInstantiated(Prefab, true);
		Debug.LogError($"Spawning.... frame: {Time.frameCount}");
		++spawns;
		_spawned.Spawn();
	}

	private void DespawnObject()
	{
		if (_spawned)
		{
			Debug.LogError($"Despawning.... frame: {Time.frameCount}");
			_spawned.Despawn();
		}
	}
}
```

 ```csharp
using FishNet.Object;
using UnityEngine;

public class PrintStart : NetworkBehaviour
{
	public static int startsServer = 0;
	public static int startsClient = 0;
	public override void OnStartClient()
	{
		base.OnStartClient();
		++startsClient;
		Debug.LogError($"OStartC instanceId: {GetInstanceID()} frame: {Time.frameCount}");
	}

	public override void OnStartServer()
	{
		base.OnStartServer();
		++startsServer;
		Debug.LogError($"OStartS instanceId: {GetInstanceID()} frame: {Time.frameCount}");
	}
	
	public override void OnStopClient()
	{
		base.OnStopClient();
		Debug.LogError($"OStopC instanceId: {GetInstanceID()} frame: {Time.frameCount}");
	}

	public override void OnStopServer()
	{
		base.OnStopServer();
		Debug.LogError($"OStopS instanceId: {GetInstanceID()} frame: {Time.frameCount}");
	}
} 
```

**Comment by FirstGearGames** [comment]
Okay thank you. I will try and give this a whirl Monday or Tuesday. I
actually removed the interval option from the distance condition so I will
have to go back to where it existed.
I don't think the interval exactly is the issue, but it's more or less just
causing reproduction of the issue so I still need to of course figure it
out.

**Comment by FirstGearGames** [comment]
Wanted to update this issue...
I've had a rough time replicating this issue but I'm going to give it another shot **after** 3.6.3.

**Comment by FirstGearGames** [comment]
After too many unsuccessful attempts I'm going to need a small project to reproduce this.

**Comment by tartarusdev** [comment]
Sure, here is the test project I was using.

[FishNet.zip](https://github.com/FirstGearGames/FishNet/files/11594065/FishNet.zip)

**Comment by FirstGearGames** [comment]
Thanks!

**Comment by FirstGearGames** [comment]
I assume the starts are supposed to be the same for client and server? I ran your test project and mashed S, S & D, and waited between presses. The numbers stayed aligned. 

There have been some observer reworks in 3.7.2. Have you tried already on the latest stable release 3.7.5?

**Comment by tartarusdev** [comment]
The newer versions of FishNet(3.7.4) works since it doesn't have the old _timedUpdates system in place in the distance condition I think.
So I guess it will check the condition on all observers every server tick instead and that fixes it for some reason.

**Comment by tartarusdev** [comment]
Ok, that sounds great. It seems like the issue is gone for now so this issue can be marked as solved then.

**Comment by FirstGearGames** [comment]
Great.
