### ISSUE TITLE
Code-stripping is not working

### ISSUE THREAD

**Issue by celojevic** [FirstGearGames/FishNet#274]
Unity version: 2021.3.19f1 LTS
Fish-Networking version: 3.4.3

**Describe the bug**
[Server] and [ServerRpc] tagged code is not being stripped in standalone builds

**To Reproduce**
1. Enable code-stripping, choose any type, as none of them worked
2. Make a script with a server method like this: 
```
[ServerRpc(RequireOwnership = true)]
public void CmdDrop(byte invSlotIndex)
{
    Debug.Log("Chiken");
    Duh();
    #if UNITY_SERVER || UNITY_EDITOR
    ... code here
    #endif
}

[Server]
void Duh()
{
    Debug.Log("duh");
}
```
3. Build and run the project
4. Open in dotPeek/ILSpy and you will see the code there as such:
```
    [Server]
    private void Duh()
    {
      if (!this.IsServer)
      {
        NetworkManager networkManager = this.NetworkManager ?? InstanceFinder.NetworkManager;
        if (networkManager != null)
          networkManager.LogWarning("Cannot complete action because server is not active. This may also occur if the object is not yet initialized or if it does not contain a NetworkObject component. This message may be disabled by setting the Logging field in your attribute to LoggingType.Off");
        else
          Debug.LogWarning((object) "Cannot complete action because server is not active. This may also occur if the object is not yet initialized or if it does not contain a NetworkObject component. This message may be disabled by setting the Logging field in your attribute to LoggingType.Off");
      }
      else
        Debug.Log((object) "duh");
    }

    public void RpcLogic___CmdDrop_1246646286(byte invSlotIndex)
    {
      Debug.Log((object) "Chiken");
      this.Duh();
    }
```

**Expected behavior**
Not sure. Isnt the method supposed to just be empty if [ServerRpc] and non-existent if marked [Server]?
Only the code within the pre-processor directives gets removed, which is the result I was expecting with code-stripping.
PS. code-stripping has never worked for me since i started using FN

**Comment by FirstGearGames** [comment]
Yes, the method should be emptied out.

**Comment by FirstGearGames** [comment]
Tested on 3.5.2 which has the same code stripping as 3.4.3 and many previous versions.
```cs
using FishNet.Object;
using UnityEngine;

public class AAAAAAAAA : NetworkBehaviour
{

    [Server]
    public void AServerMethod()
    {
        Debug.Log("Attribute");
    }

    [ServerRpc]
    public void ServerAServerRpc()
    {
        Debug.Log("Rpc");
    }
```
The `AServerMethod` was removed entirely as expected. `ServerAServerRpc` logic class was removed and writer was kept, as expected.

Unable to reproduce.
PS: make sure you're actually checking build DLLs not ones in the library folder.

**Comment by celojevic** [comment]
yes i am actually using build DLLs
