### ISSUE TITLE
Minor: Bandwidth Display is not placed correctly when placement is set to Top Right

### ISSUE THREAD

**Issue by tedbarth** [FirstGearGames/FishNet#279]
Unity version:
Fish-Networking version: 3.4.3

**Describe the bug**
Bandwidth display is misplaced.

**To Reproduce**
1. Activate Updates in **Statistics Manager**
2. Add component **Bandwidth Display* somewhere
3. Set **Placement** to **Top Right**
4. Enjoy error

**Expected behavior**
Bandwidth text is all visible.

**Screenshots**
![image](https://user-images.githubusercontent.com/8289532/222984711-59d21bbf-56b2-4306-8321-ff196ea9b9d7.png)

**Comment by Maclay74** [comment]
Wasn't it fixed in 3.5.x?

**Comment by FirstGearGames** [comment]
Fixed in latest release.
