### ISSUE TITLE
Clients not moving smoothly on host client.

### ISSUE THREAD

**Issue by AlphaLul** [FirstGearGames/FishNet#28]
In the prediction examples, the host client (server and client) moves smoothly on clients, and clients move smoothly on other clients, but clients don't move smoothly on the host client.

**Comment by FirstGearGames** [comment]
This is not a bug but a potential enhancement. You are seeing this because of how the prediction works. I'll work on a solution to resolve this in the near future.

**Comment by yigiteren** [comment]
Was about to create the same issue, glad it is not a bug. Great tool, looking forward for a solution!

**Comment by FirstGearGames** [comment]
Hey! I have already created the component to resolve this. I only need to finalize it and wrap it into the predicted object component.

**Comment by FirstGearGames** [comment]
Added in 152.
