### ISSUE TITLE
NetworkTransform makes rigidbody unstable on host

### ISSUE THREAD

**Issue by AhonenAJ** [FirstGearGames/FishNet#282]
Unity version: 2021.3.15f1
Fish-Networking version: 3.4.3 Pro

**Describe the bug**
I am dropping a rigidbody with a simple box collider onto a sloped terrain. The box collider has a physics material with high friction values and no bounce to make it come to rest as quickly as possible (I get similar results without the material, though). Dropping the box works fine, it may roll or just stop once it settles on the terrain. If I add a NetworkTransform to the object, it no longer stops but keeps jittering to some extent, seemingly forever. And this is all on the host client. The box object owner is set to null. The problem seems to be NetworkTransform touching the transform position/rotation even on the host, although it should be all up to date already, which then messes up the physics simulation somehow. Using unpacked position/rotation doesn't help.

If I add:
`if (nc.IsHost) continue;`
to the TargetUpdateTransform call loop in NetworkTransform.SendToClients, the problem goes away. (I'm making the rigidbody kinematic on non-host clients so they work fine as long as the host's jitters are sorted out.) And my TimeManager is configured to handle the physics simulation so that shouldn't be a problem either, not that changing it altered the outcome in any way.

I also tried getting this to work with PredictedObject, which seemed to work fine on the host but then I got these similar kinds of jitters and instabilities on the other clients, causing them to go out of sync and drift off gradually.

**To Reproduce**
1. Create a sloped terrain (maybe just a sloped box collider will be enough?)
2. Create a spawnable network object with a network transform that also has a rigidbody and a box collider with high friction
3. Play as host
4. Spawn the box above the sloped terrain and let it fall with gravity
5. The rigidbody keeps sliding slightly or jitters in place instead of settling and going asleep

**Expected behavior**
The NetworkTransform shouldn't affect the rigidbody simulation on the host.

**Screenshots**
My rigidbody box config:
![image](https://user-images.githubusercontent.com/114407678/223411731-cd7a1ee5-c00f-48df-9c25-1c95cfb6b194.png)

**Comment by Maclay74** [comment]
I might be wrong, but you shouldn't use `NetworkTransform` for rigid bodies, use `PredictedObject` instead.

**Comment by FirstGearGames** [comment]
You wouldn't if using prediction but either way the NT doesn't need to send from server to clientHost; definitely something that can be improved.

**Comment by FirstGearGames** [comment]
PS: the IsHost check will actually prevent sending to ANY connection.
The proper change should be this...
Added in 3.5.2
```cs
                        //No need for server to send to local client (clientHost).
                        if (!nc.IsLocalClient)
                            TargetUpdateTransform(nc, _changedWriters[lodIndex].GetArraySegment(), channel);
```

**Comment by AhonenAJ** [comment]
Excellent, thank you!
