### ISSUE TITLE
DontDestroyOnLoad only works for root GameObjects or components on root GameObjects

### ISSUE THREAD

**Issue by kenorb** [FirstGearGames/FishNet#299]
Unity version: 2021.3.18f1
Fish-Networking version: 3.4.3

**Describe the bug**

I've got the following error happens on game start:

> DontDestroyOnLoad only works for root GameObjects or components on root GameObjects.

Stack trace:
```
UnityEngine.StackTraceUtility:ExtractStackTrace ()
FishNet.Managing.NetworkManager:SetDontDestroyOnLoad () (at Assets/Libraries/GitHub/FishNet/Assets/FishNet/Runtime/Managing/NetworkManager.cs:437)
FishNet.Managing.NetworkManager:Awake () (at Assets/Libraries/GitHub/FishNet/Assets/FishNet/Runtime/Managing/NetworkManager.cs:274)
```

I'm not sure what's the issue, it's for initial setup. I've set player prefab in NetworkManager prefab. 

**To Reproduce**

If it's not clear, let me know if you need further info.

**Expected behavior**

I'd like to understand the error more clearly or how to fix it.

**Comment by FirstGearGames** [comment]
This is a unity restriction and warning.
