### ISSUE TITLE
base calls in virtual RPCs produce codegen errors.

### ISSUE THREAD

**Issue by FirstGearGames** [FirstGearGames/FishNet#30]
@mbussi#2209
"It seems that while you can have a virtual observers rpc and override it in a child class, if from the body of the overridden rpc you call the base method you end up with that cryptic error message"
(0,0): error System.Security.SecurityException: ECall methods must be packaged into a system module.

May require base being in a different assembly.

**Comment by FirstGearGames** [comment]
A work around for this is being prepared and will prevent future incidents.
ETA within 7 days.

**Comment by tkuebler** [comment]
I'm seeing the same problem.  commenting for notification of close.  :)

**Comment by FirstGearGames** [comment]
The work around is to make another virtual method, and call that method in the RPC.
A proper solution will be made but the next release has a lot of fixes that have to get out before anymore time is put into this.
The next release will generate an error telling you how to use the work around.

**Comment by tkuebler** [comment]
> 

Hope it also includes the offending file and line number.

**Comment by Abdelfattah-Radwan** [comment]
> > 
> 
> Hope it also includes the offending file and line number.

It does. You can also double click the log and it will take you there.

**Comment by FirstGearGames** [comment]
This action is blocked by the compiler with a detailed error. The codegen needs a bit of work to make this run as desired so that might take some time.

Keeping open until fully resolved.

**Comment by FirstGearGames** [comment]
This isn't going to be an easy fix for a large number of reasons. Unfortunately the work-around solution will have to do for an undetermined amount of time.
