### ISSUE TITLE
PredictedObject interpolation bug 

### ISSUE THREAD

**Issue by Maclay74** [FirstGearGames/FishNet#301]
Unity version: 2022.2
Fish-Networking version: 3.4.3

**Describe the bug**
When using `PredictedObject` and switching between 0 and 1 interpolations steps, it keeps information about the moment when it was disabled and interpolates from it once it was enabled.

**To Reproduce**
1. Create object with PredictedObject
2. Call `SetInterpolation(0, true)`; 
3. Move the object
4. Call `SetInterpolation(1, true);`
5. See that it was interpolated from the position when it was on step 2.
 
**Expected behavior**
PredictedObject probably needs a method to clear it's internal state so it won't interpolate

**Screenshots**

<video src="https://user-images.githubusercontent.com/5504685/226438022-45459338-50b6-41ff-b9cd-2fd3e9f22880.mp4" />

**Comment by FirstGearGames** [comment]
Setting interpolation to 0 was never intended to be a solution for picking up objects. If you cannot throw or push the objects around using PO on them is kind of pointless, a NT will work.

A near future release will have the option to disable the PO locally though for reasons such as this.

**Comment by Maclay74** [comment]
Okay, I took another approach, instead of parenting I use joints to control position of the object.
I create a joint between the player and the box

```cs
var joint = gameObject.AddComponent<ConfigurableJoint>();
joint.connectedBody = newParent.GetComponent<Rigidbody>();
joint.autoConfigureConnectedAnchor = false;
joint.connectedAnchor = new Vector3(0, 0, 1);
joint.xMotion = ConfigurableJointMotion.Locked;
joint.yMotion = ConfigurableJointMotion.Locked;
joint.zMotion = ConfigurableJointMotion.Locked;
joint.angularXMotion = ConfigurableJointMotion.Locked;
joint.angularYMotion = ConfigurableJointMotion.Locked;
joint.angularZMotion = ConfigurableJointMotion.Locked;
```

I tried to create it on both server and client and on server only, the result is the same (at least over my local network)

<video src="https://user-images.githubusercontent.com/5504685/227731763-a8898b7a-a9d8-404e-880b-4475f2acb6c3.mp4" style="width: 100%;"/>

On this video, at the beginning I run it in Editor and it works fine, but in built app it jitters.
And when I connect to the server it behaves even more weird. 

I just don't understand, but clearly there is something wrong with PO for rigidbodies.

**Comment by FirstGearGames** [comment]
Consider trying 3.5.8. But just as a heads up, the PredictedObject interpolation is only getting Enterprise fixes at this time.
With the CSP rework PredictedObject will more-or-less become obsolete and many of these issues won't exist. You'll have to wait until that time comes unfortunately.
