### ISSUE TITLE
Build crashes with IK enabled

### ISSUE THREAD

**Issue by intensevideogame** [FirstGearGames/FishNet#309]
Unity version: 2021.3.20
Fish-Networking version: 3.5.6

when using animation rigging with fishnet and in build, it crashes instantly.

1. I personally follow the steps from this tutorial so basically just do this https://www.youtube.com/watch?v=TUBHvQ2XEJs
2. I also followed FirstGearGames tutorials for setting up fishnet
3. built the game
4. played the game and then crashed

Expected behavior:
well the end of the arm is supposed to be at the target position and the game should not crash I guess.

**Comment by FirstGearGames** [comment]
Not enough information to go off from. Try disabling FishNet components to see what specifically is causing it. You may be getting NaN errors which when spammed by cause a crash but without further analysis there's no way to know if FishNet is to blame.
Please re-open when you have more information.
