### ISSUE TITLE
[question] What is the best place to capture the input?

### ISSUE THREAD

**Issue by yigiteren** [FirstGearGames/FishNet#31]
In the `RigidbodyPrediction.cs` example, checking the input is done inside the TimeManager_OnTick() method. Is there a specific reason to do so? Isn't it cleaner to capture the input inside the update, while capturing the timing for `_nextJumpTime`?

**Comment by FirstGearGames** [comment]
Hey, please use our Discord for questions. You will receive much more prompt assistance there. Thank you!
https://discord.gg/Ta9HgDh4Hj
