### ISSUE TITLE
[FN 3.5.7 Pro] Network Transform Throws Tons of Errors Randomly

### ISSUE THREAD

**Issue by Sonicboomcolt** [FirstGearGames/FishNet#311]
Unity version: 2021.3.0f1
Fish-Networking version: 3.5.7 Pro

**Describe the bug**
I'm not sure if it happens all the time but when walking around and rotating it will sometimes cause the host to vanish and throw a ton of errors on the client. [VIDEO SHOWING THE ERROR IN ACTION](https://youtu.be/OXVoBbOqndw)

**To Reproduce**
1. Have Client Auth enabled on NT
2. Move around/Rotate around
3. It should throw an error and cause the host to vanish.

EDIT: Seems the network LODS caused the issue.

**Expected behavior**
NT Won't vanish when moving around.

**Screenshots**
The errors that spam the log.
![image](https://user-images.githubusercontent.com/49329116/227732230-d91fe4b5-8966-45d1-9a02-20e88aae856c.png)

Network Transform setup.
![image](https://user-images.githubusercontent.com/49329116/227732417-db6427b7-1fe8-45b0-8753-23ef0cfafd20.png)

**Comment by FirstGearGames** [comment]
Seems it's sending the transform off into oblivion. How are you moving the
character?

**Comment by FirstGearGames** [comment]
Can you show full setup of your prefab too please.

**Comment by Sonicboomcolt** [comment]
Somehow by some big brain move I disabled network LODS and it seems to have fixed the issue

**Comment by FirstGearGames** [comment]
Okay there is quite possibly still some things to resolve with the LOD. Are
you able to make a small project replicating this issue?

**Comment by FirstGearGames** [comment]
Definitely LOD issue. Network LOD has been disabled in 3.5.8 with a warning until this can be resolved. I'm closing this out as the feature has been disabled / considered unusable at this time.

I'd really like to get this resolved ASAP though; if you can please DM me with what you have I'll take a look.
