### ISSUE TITLE
Synced parent NetworkTransform issue with distance condition

### ISSUE THREAD

**Issue by FREEZX** [FirstGearGames/FishNet#312]
There is an error that happens on the client whenever you try to parent a NetworkTransform to an object that is not matching the condition. The error is caused because the client is unable to locate the parent NT, so it doesn't get spawned properly.
I believe that this kind of setup should be handled gracefully, because there would always be a disconnect with parenting as the child is rarely at the exact same position as its parent.

Including minimal reproduction project, requires the addition of Fishnet pro (I used 3.6.0) in the assets folder:
[NetLODRepro.zip](https://github.com/FirstGearGames/FishNet/files/11069987/NetLODRepro.zip)
To reproduce just host and join using another instance.

**Comment by FirstGearGames** [comment]
Does this happen if you disable NetworkLOD? I ask because the LOD feature is temporarily being disabled while all bugs are resolved. If this still occurs without LOD I can investigate further.

**Comment by FREEZX** [comment]
I'm traveling and won't be able to check this to be 100% sure, but in my game these errors happened without network LODs.

**Comment by FirstGearGames** [comment]
This is kind of a catch 22. The root could be visible for some observers but not all. The transform also sends in localspace to support proper moving when as a child. It would be a lot of perf to switch between local and world based on if the observer can see the parent or not. 

What might be more practical is to simply hide the child (NT) object from the observer when it's parent is not visible.

**Comment by FREEZX** [comment]
I suppose by "Hide" you mean the child won't exist on clients until their parent is observed, that sounds like a good solution to the problem to me.

**Comment by FirstGearGames** [comment]
That is what I meant.

**Comment by FirstGearGames** [comment]
After spending more time thinking about I believe it becomes more complex.

I initially considered making a custom condition that despawns the NT object and set it when the NT recognizes a new parent that the connection does not have observation of, and reversing it when the NT no longer had the parent. This would work for the initial spawn but if the parent suddenly came into observation the other condition wouldn't know, unless it was timed and checked regularly. Timed conditions then of course present a cost of regularly being updated.

I'm thinking the best approach might be a 'sub condition' of sorts that is only checked when normal conditions state changes.  Perhaps, a NetworkTransformParentCondition would be added automatically as a sub condition when a NT is present with synchronized parents enabled. The sub condition then would not be updated or checked until all prior conditions have changed state... be it scene, distance, ect. This way it's not a timed update and it knows to update based on if observation was gained or lost of the parent.

At a glance I believe this would work but given the additional work I cannot provide a timeline for this yet.

**Comment by FREEZX** [comment]
Until it's done properly, I suggest leaving a note somewhere that parenting doesn't behave well with conditions that don't immediately resolve to the same result for the child and parent.

**Comment by FirstGearGames** [comment]
I can put something in the docs.

**Comment by FirstGearGames** [comment]
Updated the docs and I'm going to put more time into resolving this specifically.

**Comment by FirstGearGames** [comment]
Resolved in 3.7.0
