### ISSUE TITLE
[FN 3.4.2] Network Animator - Server Authorative Not Playing animations

### ISSUE THREAD

**Issue by nipeerc** [FirstGearGames/FishNet#313]
Unity version: **2020.3.25f1**
Fish-Networking version: **3.4.2**

**Describe the bug**
Network Animator set to Server Authorative is not playing animations when sending ServerRPC. 
`[ServerRpc]
 private void PlayAttackAnimationServer(string anim)
 {
       animator.Play(anim, 0, 0)
 }`

This code block plays the animation on the server but it not replicating it back to clients. The only way I have been able to get it to work is by just sending ServerRPC and inside of it send an ObserverRPC. 

The Network Animator on the player has Client Authorative and Syncronize to Owner are both unchecked.

**To Reproduce**
`
private void Update()
{
     If (Input.GetKeyDown(Keycode.Alpha1)
     {
           PlayAttackAnimationServer("OH2");
      }
}
`

Just have an animation on the animation controller with corresponding name to string passed in.

**Expected behavior**
I expect that if I tell server to play an animation and both options are unchecked that the server would play the animation on all clients. Is that incorrect? I asked in discord but didnt get any responses.

**Comment by FirstGearGames** [comment]
You have to call play on the network animator, not the animator. It's the only way to know the play state is changing.

**Comment by nipeerc** [comment]
Actually tried playing directly on network animator and did not work either
