### ISSUE TITLE
SceneManager infinite loop

### ISSUE THREAD

**Issue by KartoffelbauerRebus** [FirstGearGames/FishNet#322]
Unity version: 2021.3.16f1
Fish-Networking version: 3.6.1.Experimental.Pro

**Describe the bug**
SceneManager.cs:1067 - 'while' condition is only set to false before entering the loop and then true inside the loop, but never reset. 

**Fix**
Set allScenesLoaded to true before iterating through the scenes again. (i.e. add line 1070)
![grafik](https://user-images.githubusercontent.com/13179578/231051038-1bf8952a-442d-4317-9125-e70182e838b9.png)

**Comment by FirstGearGames** [comment]
Nice catch. Added in 3.6.3
