### ISSUE TITLE
Duplicate code adding an extra NetworkObject

### ISSUE THREAD

**Issue by KartoffelbauerRebus** [FirstGearGames/FishNet#323]
Unity version: 2021.3.16f1
Fish-Networking version: 3.6.1.Experimental.Pro

**Describe the bug**
ObjectCaching.cs:324 and ObjectCaching.cs:334 (which is called in line 326) are identical and each add a NetworkObject to _clientObject.
![grafik](https://user-images.githubusercontent.com/13179578/231052994-f0e13be4-cb08-460c-8a8a-265f3cf58fca.png)
![grafik](https://user-images.githubusercontent.com/13179578/231053000-84d7443c-3901-4df0-8bdc-cf77326e5eba.png)

**Solution**
Remove either line.

[#296](https://github.com/FirstGearGames/FishNet/issues/296#issuecomment-1475010879) related. Without the above fix, the following line adds doubles, leaving dead duplicates in the array after destruction.
```c#
NetworkObject nob = localClientSpawned[nobIndex];
```

**Comment by SnaiperoG3D** [comment]
I have a leak on server with a lot of nobs in memory. Checking this out. As i saw in code, i guess its true for server too

**Comment by FirstGearGames** [comment]
> I have a leak on server with a lot of nobs in memory. Checking this out. As i saw in code, i guess its true for server too

If you are running as clientHost, maybe. This code only iterates on client.

**Comment by FirstGearGames** [comment]
> Unity version: 2021.3.16f1 Fish-Networking version: 3.6.1.Experimental.Pro
> 
> **Describe the bug** ObjectCaching.cs:324 and ObjectCaching.cs:334 (which is called in line 326) are identical and each add a NetworkObject to _clientObject. ![grafik](https://user-images.githubusercontent.com/13179578/231052994-f0e13be4-cb08-460c-8a8a-265f3cf58fca.png) ![grafik](https://user-images.githubusercontent.com/13179578/231053000-84d7443c-3901-4df0-8bdc-cf77326e5eba.png)
> 
> **Solution** Remove either line.
> 
> [#296](https://github.com/FirstGearGames/FishNet/issues/296#issuecomment-1475010879) related. Without the above fix, the following line adds doubles, leaving dead duplicates in the array after destruction.
> 
> ```cs
> NetworkObject nob = localClientSpawned[nobIndex];
> ```

Can you please send me a DM on Discord.

**Comment by FirstGearGames** [comment]
After reviewing I've removed the IterateSpawn call and moved the `ApplyRpcLinks` to it's place.
Iirc IterateSpawn used to be used in multiple places but it seems in the current version it's only used once, immediately after already adding the object to spawn.

This was likely something caused by a refactor. 
New code...
```cs
                        _clientObjects.AddToSpawned(cnob.NetworkObject, false);
                        SpawningObjects.Add(cnob.ObjectId, cnob.NetworkObject);
                        /* Fixes https://github.com/FirstGearGames/FishNet/issues/323
                         * The redundancy may have been caused by a rework. It would seem
                         * IterateSpawn was always running after the above lines, and not
                         * from anywhere else. So there's no reason we cannot inline it
                         * here. */
                        _clientObjects.ApplyRpcLinks(cnob.NetworkObject, cnob.RpcLinkReader);
                        //IterateSpawn(cnob);
```
