### ISSUE TITLE
NPE because Tugboat is constructed once, but deconstructed twice in editor

### ISSUE THREAD

**Issue by tedbarth** [FirstGearGames/FishNet#329]
Unity version: 2022 (any minor)
Fish-Networking version: 3.5.8 (and others)

**Describe the bug**
After upgrading to Unity Editor 2022 whenever I have the debugger connected there is an NPE caught in Tugboat's deconstructor. The NPE is caused by the editor deconstructing twice, while the game is not even started.

This looks like a bug in Unity, but since it is annoying as hell and not solved by Unity since several minor versions I like to point this out here. This could also be an incompatibility problem of FN, though.

**To Reproduce**
Steps to reproduce the behavior #1:
1. Start game from editor when having whole FN added to assets while debugger (set to stop on uncaught exceptions) is connected
2. [You notice that the breakpoint in Tugboat's constructor is called **twice**; NPE on the second call in StopClient() because Client is null]

Steps to reproduce the behavior #2:
1. Add constructor with NOOP action (e.g. Debug.Log("foo")) to Tugboat class
3. Start Unity Editor from IntelliJ while debugger points are active in Tugboat's constructor and deconstructor
4. [You notice that the breakpoint in Tugboat's constructor is called **once**]
5. Start game
6. [You notice that the breakpoint in Tugboat's constructor is called **twice**; NPE on the second call in StopClient() because Client is null]

**Expected behavior**
No NPE.

**Screenshots**
![image](https://user-images.githubusercontent.com/8289532/232302586-ad383865-3e0a-4ccd-840e-1a0ea8792d62.png)

**Comment by FirstGearGames** [comment]
This has already been resolved and will be in 3.6.3.
