### ISSUE TITLE
NetworkBehaviour: Object cannot start as inactive and then send RPC

### ISSUE THREAD

**Issue by xKamuna** [FirstGearGames/FishNet#33]
If an object is inactive in the scene at the start, and then becomes active, the server throws a warning for each RPC called:

"Cannot complete action because server is not active. This may also occur if the object is not yet initialized or if it does not contain a NetworkObject component. This message may be disabled by setting the Logging field in your attribute to LoggingType.Off"

This also happens when setting the object to be inactive in Awake().

EDIT: Fixed information and new information.

**Comment by FirstGearGames** [comment]
You said client throws a warning but it appears you're trying to perform an action that only the server should "server is not active".

**Comment by xKamuna** [comment]
Sorry, I meant server. I was playing as client and server so I got confused as to which was which.

**Comment by xKamuna** [comment]
I think I figured out the problem. When a game object with a NetworkBehaviour is inactive, it doesn't receive any messages.
This is possibly by design. If so, feel free to close this issue.

**Comment by FirstGearGames** [comment]
Disabling alone should not prevent messages. It's possible the object never initialized though, which would cause such a problem.

**Comment by xKamuna** [comment]
Interesting. When started it enabled, then disabled it, RPCs would not get called on the object when I called an RPC on the inactive object (I also use RunLocally on these RPCs). Do you think something else is going on there? They are all ObserversRpcs, I have no ServerRpcs (the game is very simple so the client is very light, using only a simple Broadcast for input).

**Comment by tylerzudans** [comment]
@FirstGearGames I spun my tires for a bit due to the same message, but the object is was networkbehaviour, and the server was active. I think the issue was that I was calling an ObserverRPC from a client. Not sure if that would be expected to cause this warning. If so I can make a PR to include that in the warning message :)
