### ISSUE TITLE
NetworkBehaviour synced with SyncVars fail to sync after a scene change

### ISSUE THREAD

**Issue by nscimerical** [FirstGearGames/FishNet#331]
Unity version: 2021.3.21f1
Fish-Networking version: 3.5.8

**Describe the bug**
My scene flow is somewhat complex. I'll try to give context. This is basically how it goes:

Offline scene -> Lobby scene -> Game scene

When loading the lobby scene, I spawn a Player object to represent each client. This Player object persists between scene changes (e.g. Lobby -> Game). The player object contains references and variables related to the client like name, color, and character number. Along with the Player object spawned, I also spawn an Avatar (a NetworkBehaviour) that represents the client physically in the game world, this is the character that the client can move around with.

Here comes the bug. When spawning an Avatar on the scene, I assign a reference of the Avatar to the Player object. This is for convenience that I use to quickly reference the Avatar script from the Player object.

```csharp
[ServerRpc(RequireOwnership = false)]
private void RpcSpawnAvatar(NetworkConnection connection = null)
{
    var spawnLocation = FindObjectOfType<SpawnPoint>().GetSpawnLocation();
    var avatar = Instantiate(avatarPrefab, spawnLocation.position, spawnLocation.rotation);
    var player = Player.PlayerList.First(player => player.Owner == connection);

    player.avatar = avatar; // ISSUE HERE
    avatar.player = player;
    avatar.NetworkObject.SetIsGlobal(false);

    Spawn(avatar.gameObject, connection);
    RpcSpawnAvatarResponse(connection);
}
```

Here's the Player script:

```csharp
public class Player : NetworkBehaviour
{
    public Avatar avatar;
    public string playerName;
    public int playerCharacter = -1;
}
```

Here's the base Avatar script that a lot of specific avatars inherit:

```csharp
public class Avatar : NetworkBehaviour
{
    // Keep reference to Player for convenience
    [HideInInspector]
    [SyncVar] public Player player;
}
```

When first spawning in the Lobby scene, the Player's Avatar reference is properly set. But when I change to the next scene (from Lobby to Game scene in this case), the host Player's Avatar reference is null, even though I've changed it properly in the RPC script above. This happens 100% of the time and all clients are affected. Essentially, the NetworkBehaviour being synced is null on other clients.

I've done other workarounds like setting the Avatar reference of the Player during OnStartServer when the avatar is spawned. Unfortunately, the result is the same and the avatar remains null. It seems like the host stops sending values on objects that it owns.

**Expected behavior**
When I assign a new NetworkBehaviour value on a SyncVar, I expect the value to also be synced on clients.

**Comment by nscimerical** [comment]
Found the issue. When the client is still loading the scene, the host has already spawned its own avatar on the server. This new reference that is set on the server is then replicated unto clients which still hasn't finished loading yet. So it gets an ID of the NetworkBehaviour of an object that doesn't exist yet and the SyncVar's solution is to set its value to null instead of... logging a warning or error on the console. I've fixed the problem by waiting for all clients to load before spawning anything so I'll be closing this issue.

**Comment by FirstGearGames** [comment]
So host is visible to client but you set the SyncVar to an object the
client cannot see? If that's the case null is the appropriate value. The
client could cache the ID that was intended but not found and check spawns
as they come in for that ID, and set SyncVar if spawned. But that itself is
kind of an issue, because what if the object was say in a class inside a
synclist. The complexity becomes much more serious.

As you mentioned the client would need visibility of the syncvar object, or
not have visibility of the holding script until the value was available.

**Comment by FirstGearGames** [comment]
PS: a warning would be nice. Please make a feature request so I can get
that in.
