### ISSUE TITLE
NetworkTransform with PredictedObject

### ISSUE THREAD

**Issue by Stormhound** [FirstGearGames/FishNet#332]
Unity version: 2021.3.14f1
Fish-Networking version: 3.5.8 PRO

**Describe the bug**
I'm using CSP and I have fast-paced FPS Controller, so I know I should be using AddForce for movement but its not just suitable with my movement code and instead of that I'm manuplating velocity directly. Directly manuplating velocity causing some jittery movement on client since PredictedObject is designed for continuous movement not for immediate changes on velocity. However, ⁠https://discord.com/channels/424284635074134018/1086363106327928933/1086681948623220809 In this thread i saw I could use NetworkTransform with CSP. So I set everything up but there's something weirdness going on, for more detail you can watch video.

**To Reproduce**
1. Add PredictedObject and select NetworkTransform for observers also add graphical object.
2. Click on NetworkTransform and deselect Client Authorization and also deselect send to owner.
3. Add RBPrediction code from examples.
4. Try with at least 2 player and try to bump each other.

**Expected behavior**
It was very smooth time to time but then suddenly it started doing that so I don't know what to expect to be honest.

**Screenshots**
![image](https://user-images.githubusercontent.com/68158551/233149067-7bf3cd2d-b8f3-4a28-af17-26a84a4e6a1b.png)
![image](https://user-images.githubusercontent.com/68158551/233149109-72b3ed3d-f8eb-430b-ada7-787ea33d257a.png)

https://user-images.githubusercontent.com/68158551/233149145-c812b163-7f11-4508-ba5c-60558dd48e93.mp4

**Comment by Stormhound** [comment]
P.S I was not moving at first seconds in the video.

**Comment by FirstGearGames** [comment]
RB prediction does not rely on NetworkTransform. Please see CSP guide for more setup information.
Also recommend waiting for prediction v2 if able.
