### ISSUE TITLE
SyncVars stopped to work

### ISSUE THREAD

**Issue by vilmarpimentel** [FirstGearGames/FishNet#337]
Unity version: 2021.3.23f1
Fish-Networking version: 3.6.4

**Describe the bug**
Exception on SyncVar.cs line 177 (NetworkManager is null). It's working fine on version 3.5.8

**To Reproduce**
1. Update to version 3.6.4.
2. Make a server build (Windows or Linux)
3. Test on editor or any other platform as a client-only (not HOST, it works as host)

**Expected behavior**
The player should spawn fine and sync all variables.

**Comment by FirstGearGames** [comment]
Confirmed. Will fix immediately.

**Comment by vilmarpimentel** [comment]
Lovely work. Thanks <3

**Comment by FirstGearGames** [comment]
Resolved in 3.6.5 - releasing it now.

**Comment by FirstGearGames** [comment]
Pro/free updated. Thanks!
