### ISSUE TITLE
Detaching LiteNetLib results in connection rejection

### ISSUE THREAD

**Issue by Zulex** [FirstGearGames/FishNet#341]
Unity version: 2020.3.12f1
Fish-Networking version: 

**Describe the bug**
As I have been using LiteNetLib before in the project and wanted to integrate FishNet, I assumed it was possible to keep the original LiteNetLib folder (Version 1.0.1.1, however I wouldn't mind updating to 1.1.0 which just released today). When importing FishNet, I got messages stating that there are 2 references for a type (as 2 DLL's are imported). I removed the folder 'LiteNetLib' from the FishNet asset and also made a reference in the fishnet.runtime.asmdef to the other LiteNetLib. Starting the server goes well, when starting the client I receive an error that the connection has been rejected. 3

**To Reproduce**
1. Clean project
2. import LiteNetLib 1.0.1.1 (or 1.1.0) : https://github.com/RevenantX/LiteNetLib/releases
3. import Fishnet
4. Delete LiteNetLib folder in fishnet asset
5. set reference in fishnet.runtime.asmdef to the LiteNetLib 1.0.1.1 folder
6. Setup a simple networkmanager
7. Start game and try to connect

**Expected behavior**
Connection should be possible (and player should spawn)

**Error code

`
Local client disconnect reason: ConnectionRejected.
UnityEngine.Debug:Log (object)
FishNet.Managing.Logging.LevelLoggingConfiguration:Log (string) (at Assets/FishNet/Runtime/Managing/Logging/LevelLoggingConfiguration.cs:108)
FishNet.Managing.NetworkManager:Log (string) (at Assets/FishNet/Runtime/Managing/NetworkManager.Logging.cs:74)
FishNet.Transporting.Tugboat.Client.ClientSocket:StopConnection (System.Nullable``1<LiteNetLib.DisconnectInfo>) (at Assets/FishNet/Runtime/Transporting/Transports/Tugboat/Core/ClientSocket.cs:163)
FishNet.Transporting.Tugboat.Client.ClientSocket:Listener_PeerDisconnectedEvent (LiteNetLib.NetPeer,LiteNetLib.DisconnectInfo) (at Assets/FishNet/Runtime/Transporting/Transports/Tugboat/Core/ClientSocket.cs:187)
LiteNetLib.EventBasedNetListener:LiteNetLib.INetEventListener.OnPeerDisconnected (LiteNetLib.NetPeer,LiteNetLib.DisconnectInfo) (at Assets/LiteNetLib/INetEventListener.cs:221)
LiteNetLib.NetManager:ProcessEvent (LiteNetLib.NetEvent) (at Assets/LiteNetLib/NetManager.cs:579)
LiteNetLib.NetManager:PollEvents () (at Assets/LiteNetLib/NetManager.cs:1474)
FishNet.Transporting.Tugboat.Client.ClientSocket:IterateIncoming () (at Assets/FishNet/Runtime/Transporting/Transports/Tugboat/Core/ClientSocket.cs:259)
FishNet.Transporting.Tugboat.Tugboat:IterateIncoming (bool) (at Assets/FishNet/Runtime/Transporting/Transports/Tugboat/Tugboat.cs:194)
FishNet.Managing.Transporting.TransportManager:IterateIncoming (bool) (at Assets/FishNet/Runtime/Managing/Transporting/TransportManager.cs:514)
FishNet.Managing.Timing.TimeManager:TryIterateData (bool) (at Assets/FishNet/Runtime/Managing/Timing/TimeManager.cs:959)
FishNet.Managing.Timing.TimeManager:IncreaseTick () (at Assets/FishNet/Runtime/Managing/Timing/TimeManager.cs:646)
FishNet.Managing.Timing.TimeManager:<TickUpdate>g__MethodLogic|98_0 () (at Assets/FishNet/Runtime/Managing/Timing/TimeManager.cs:341)
FishNet.Managing.Timing.TimeManager:TickUpdate () (at Assets/FishNet/Runtime/Managing/Timing/TimeManager.cs:331)
FishNet.Transporting.NetworkReaderLoop:Update () (at Assets/FishNet/Runtime/Transporting/NetworkReaderLoop.cs:28)
`

**Comment by FirstGearGames** [comment]
At this time I won't be troubleshooting custom implementations of LiteNetLib, sorry.
