### ISSUE TITLE
SyncTypes not synchronizing on initialization.

### ISSUE THREAD

**Issue by AlphaLul** [FirstGearGames/FishNet#344]
Unity version: 2021.3.20
Fish-Networking version: 3.6.5

**Describe the bug**
From the perspective of non-host clients, clients that join after them do not synchronize SyncTypes on initialization. For example, if each player were assigned a color when they spawned, clients wouldn't receive the color for players that join after them.

**To Reproduce**
I have some example scripts that can be used to reproduce the behavior.
Spawn Manager: [https://hastebin.com/share/ligahuboxo.csharp](https://hastebin.com/share/ligahuboxo.csharp)
Player: [https://hastebin.com/share/fuwafisuke.csharp](https://hastebin.com/share/fuwafisuke.csharp)
Pawn: [https://hastebin.com/share/momasucume.csharp](https://hastebin.com/share/momasucume.csharp)

**(It is easier to explain with images, so it might help more to look at the screenshots)**
Steps to reproduce:
1. Add the Spawn Manager to any game object in the scene. This script automatically spawns a pawn whenever a player connects.
2. Create a Player and a Pawn prefab.
3. Attach the Player script to the Player prefab and the Pawn script to the Pawn prefab.
4. Connect the Pawn prefab to the 'pawnPrefab' field in the Player script.
5. Make it so the PlayerSpawner script in the FishNet Network Manager spawns the Player prefab. This makes it so the server automatically spawns players when they connect, and then the Spawn Manager script spawns a pawn for them after they load into the scene.
6. Connect with 3 or more clients. From the perspective of client 2, the Debug.Log should print "Null" from client 3 and beyond.

**Expected behavior**
Client 2 should have references to all of the players, since the SyncVar should be synchronizing the server's initial value for any clients that join. I'm not sure if it has something to do with setting the SyncVar before spawning the pawn or SyncVars not syncing right when a player joins, but the code provided in the example scripts used to work in FishNet 3.5.8.

**Screenshots**
NetworkManager setup:
![image](https://user-images.githubusercontent.com/35549491/234407423-089d1a19-4922-498e-a818-b49cf7bcbb8e.png)

Player prefab setup:
![image](https://user-images.githubusercontent.com/35549491/234407729-b9f6cb56-7cec-4d63-a48c-ef3f36c05fb5.png)

Pawn prefab setup:
![image](https://user-images.githubusercontent.com/35549491/234407666-88e1a903-9a8f-43ea-a910-d7ff887c9167.png)

Logs from client 2's perspective. The first 2 logs are from pawns 1 and 2, and the last 2 are from pawns 3 and 4:
![image](https://user-images.githubusercontent.com/35549491/234406628-6474f0d4-c662-431c-b2a0-3953c6cd97dd.png)

**Comment by AlphaLul** [comment]
The same thing also happens when loading into scenes but the order is whoever loads into the scene after doesn't sync. It seems like it has to do something with spawning something with a SyncVar right after it enters the scene. This wasn't a problem in 3.5.8 tho, so it's something new about SyncTypes in 3.6.4 and beyond.

**Comment by FirstGearGames** [comment]
Resolved in 3.6.6
