### ISSUE TITLE
Network Transform of ClientHost not syncing with client

### ISSUE THREAD

**Issue by Spyboticer** [FirstGearGames/FishNet#345]
Unity version:2022.1.16
Fish-Networking version:3.6.5 Pro

**Describe the bug**
HostClient network transform not syncing with client only network transform

**To Reproduce**
1. Go to 'network transform'
2. Click on 'configure to be a rigidbody'
3. Launch the host/client
4 Launch the client
5 See weirdness from client host

**Expected behavior**
Clienthost sees where the other player is moving.

**Screenshots**
![weirdness screenshot](https://user-images.githubusercontent.com/43469665/234685528-2e9eafa7-23e4-4491-a834-7dcc5efd0b43.png)

**Comment by FirstGearGames** [comment]
Are you using client auth, CSP, ect?

**Comment by Spyboticer** [comment]
It was client auth by i managed to find the issue,somhow a error the hdrp volume component not being referenced correctly caused the network transform to stop working O_o

**Comment by FirstGearGames** [comment]
That error probably stopped something from completing setup. Good to know it's resolved, thanks!
