### ISSUE TITLE
Client connection disconnected during scene unload causing exception in server

### ISSUE THREAD

**Issue by Xelopie** [FirstGearGames/FishNet#346]
![image](https://user-images.githubusercontent.com/47631876/234685642-15db0ae5-9ee4-4df9-bda1-339045d7a245.png)
First of all, I am using a pretty old version of FN (2.6.2) but I have looked up the code of the latest FN version (3.6.5hf0) and those logics involved are most likely the same so I believe this issue persists. 

**Steps to reproduce:**
1. Load a scene with (AutomaticallyUnload = false) for some connections
2. Wait for the scene to be loaded...
3. Unload the previously loaded scene with all those associated connections
4. Immediately kick an associated connection (just disconnect it)
5. Wait for the unload...
6. Boom! You get the exception

**Describe the bug:**
![image](https://user-images.githubusercontent.com/47631876/234689306-5f1ac942-d460-47d1-bda0-a010dafde79e.png)
It is because the NetworkConnection associated with the scene was disconnected, which means getting Reset, and which means NetworkManager on line:50 was null. All of these had happened before the scene unloading was completed. And after the unloading had completed, the __UnloadScene coroutine tried to send the broadcasts to all those NetworkConnections and exception happened.

In my case, I am using the SceneManager.UnloadConnectionScenes when a match is over and the server wants to clean up everything so as the scene. At the same time, the server wants to disconnect with all the clients in the past match. 

My scene is loaded with AutomaticallyUnload = false so it is a scene caching situation. It is just to prevent any "connection accidents" happening to ruin the scene which the match is using. And besides, players can reconnect afterwards even if they get disconnected unfortunately.

Not sure if my usage is kind of weird or not. But unloading a scene is a long progress and the status of any connections associated with it can be tainted during the progress so I guess it needs a fix.

**Comment by FirstGearGames** [comment]
Only v2 LTS and latest stable (or experimentals) can be troubleshot. Please update to the latest v2 then try again.

**Comment by Xelopie** [comment]
> Only v2 LTS and latest stable (or experimentals) can be troubleshot. Please update to the latest v2 then try again. Re-open issue if still a problem. Thanks!

Just updated to v2 LTS and this problem persists. Not sure how to re-open this issue or I need to create a new one?
