### ISSUE TITLE
When using Multipass, stopping a server transport will not disconnect clients that were connected through that transport.

### ISSUE THREAD

**Issue by Disastercake** [FirstGearGames/FishNet#350]
Unity version: 2021.3.22
Fish-Networking version: 3.6.7.Pro

**Describe the bug**
When using Multipass and you have multiple server transports running, if you stop one of the Transports then remote clients that were connected through that transport will not go through the disconnect pipeline.

**To Reproduce**
1. Create a script that exposes individual server transports to a UI to toggle them on and off individually.
2. Have a remote client connect through one of the server transports.
3. Toggle the specific server transport off (leave others on).
4. On the host: Players from that transport still have GameObjects in the scene and there is no message of a disconnect.

**Expected behavior**
Would expect the server to automatically cycle all clients connected through the closing transport of properly send events to both remote clients and the server for each client disconnecting.

**Comment by FirstGearGames** [comment]
Will be resolved in 3.7.0. I've already completed the code, it's currently in testing.
