### ISSUE TITLE
Offline Rigidbody causes Rigidbody2D gameobject to move very slowly

### ISSUE THREAD

**Issue by FlyFunMan** [FirstGearGames/FishNet#355]
Unity version: 2021.3.21f1
Fish-Networking version: 3.6.9 (also occurred on 3.5.8hf0)

**Describe the bug**
When an Offline Rigidbody component is added to a gameobject with a Rigidbody2D component, the object moves very slowly for everyone but the host (less than a 10th of normal speed). This does not happen if the gameobject has a Rigidbody component instead.

**To Reproduce**
1. Go to the RigidbodyPrediction example scene.
2. On the Offline Capsule component, replace the Rigidbody and the Capsule collider with their 2D equivalents.
3. Set the Offline Capsule's Offline Rigidbody's Rigidbody Type to "Rigidbody 2D".
4. Enable the Offline Capsule 
5. Connect the client to the host. The client will display the bug.

**Expected behavior**
I would expect the Rigidbody2d gameobject to move at normal speed, just like the Rigidbody does.

**Screenshots**
The capsule on the left has a Rigidbody2D and the capsule on the right has a Rigidbody.
https://user-images.githubusercontent.com/45148010/236065937-247dd287-22fa-481c-b9b3-16fe2fab8be5.mp4

**Comment by FirstGearGames** [comment]
Have you tried this on 3.7.8+? We resolved some kinematic settings with the rigidbody pauser scripts.

**Comment by FlyFunMan** [comment]
I just tried it on 3.7.11, and it still seems to be occurring.

**Comment by FirstGearGames** [comment]
Okay thank you. I did not see your response until now but I'll be able to investigate.

**Comment by FirstGearGames** [comment]
I've been backlogged on this. If you can provide me a sample unitypackage with just the scene/prefabs/scripts to test I can have a look within a week.
