### ISSUE TITLE
ClientManager connection functions missing return value

### ISSUE THREAD

**Issue by Drischdaan** [FirstGearGames/FishNet#357]
Unity version: 2021.3.23f1
Fish-Networking version: 3.6.9

### Describe the bug
The return value of the `StartConnection` and `StopConnection` functions inside of the `ClientManager` are missing.
The `ServerManager` returns a `boolean` on these functions.

### Expected behavior
The functions `StartConnection` and `StopConnection` inside the `ClientManager` should return a `boolean`, not `void`.

### Solution
I already created a pull request for this issue: #356

**Comment by FirstGearGames** [comment]
This is intentional because not all transports (actually none) provide instant feedback so returning anything would be pointless. Some transports do on the server side however. I can make them both booleans but the thing is, it really depends on the transport if that means anything.

**Comment by Drischdaan** [comment]
> This is intentional because not all transports (actually none) provide instant feedback so returning anything would be pointless. Some transports do on the server side however. I can make them both booleans but the thing is, it really depends on the transport if that means anything.

I understand the point you're making. I am using the default transport and I rely on the client starting up successfully. Using the event callback would add unnecessary complexity. Therefore, I think this solution would be a helpful addition. While some transports may not return a boolean value immediately, we can simply ignore the return value in those cases. Overall, I believe this approach would be ideal for this situation.

**Comment by FirstGearGames** [comment]
Added in 3.7.0
