### ISSUE TITLE
Host syncvar onchange method not calling with asServer = false

### ISSUE THREAD

**Issue by SnaiperoG3D** [FirstGearGames/FishNet#361]
Unity version: 2021.3.23.f1
Fish-Networking version: 3.6.9 Pro

**Describe the bug**
On host syncvar onchange method not calling with asServer = false, but it happens only in some weird cases. This is replica of my logic. I have player nickname spawning from pool, all onchange methods on nickname nob not working with asServer = false, only with true. 
https://pastebin.com/0uF4r4Qu
Ive put here only nickname spawn snippet, also i have a player spawn logic in same way

**To Reproduce**
Dont know yet, need more info about it

**Comment by FirstGearGames** [comment]
Does this script reproduce 100% of the time?

**Comment by SnaiperoG3D** [comment]
yeah, as i result of not working onchange methods, local player can see his nickname above his head on host. i have a return logic if its a server call with asServer arg check. and there is no call with asServer false, where i do my checks before enable or disable nickname above the head. i can try to reproduce it in empty project in few days. maybe this bug have other envoirment, cuz i start to have visible nicknames even not on host, which wasnt in previos versions of fish. ill try to get more info about it

**Comment by FirstGearGames** [comment]
If this script can replicate I'll use it to test and resolve.

**Comment by SnaiperoG3D** [comment]
ok, there are two scenes also. one with menu. and one online scene which loads on server start, maybe its this is a point

**Comment by SnaiperoG3D** [comment]
as i found from players, it appears only on singleplayer(host)

**Comment by FirstGearGames** [comment]
There is a small chance this was resolved in 3.7.4. Can you please update and let me know if the problem still persist.

**Comment by SnaiperoG3D** [comment]
Sure, in few next days
