### ISSUE TITLE
Strange log warning 

### ISSUE THREAD

**Issue by SnaiperoG3D** [FirstGearGames/FishNet#367]
Unity version: 2021.3.23.f1
Fish-Networking version: 3.6.9 Pro

start to have these logs at server. Also i have a feeling that leak not gone in my case. dont know yet is it my fault or fish. will take more logs from server and post here.

https://pastebin.com/8nsYQ6Dt

**Comment by FirstGearGames** [comment]
Please ask in the help channel before posting things to bugs right away. I'd like to see a discussion on troubleshooting steps made.
