### ISSUE TITLE
Late joining clients with additive scenes results in an exception.

### ISSUE THREAD

**Issue by ncorns** [FirstGearGames/FishNet#368]
**General**
Unity version: URP 2021.3.22f1
Fish-Networking version: 3.6.9
Link on our Discord where you troubleshot the issue(on Discord click the three dots next to the message, then Copy Message Link): 
https://discord.com/channels/424284635074134018/1034477094731784302/1107030990649561283

**Description**
When a host starts and enters an additive scene with at least one network object, any clients which connect late and spawn outside of the additive scene will throw an exception despite the network object being configured with a scene observer. The exception is:

_"SceneId of {sceneId} not found in SceneObjects. This may occur if your scene differs between client and server, if client does not have the scene loaded, or if networked scene objects do not have a SceneCondition. See ObserverManager in the documentation for more on conditions."_

The issue here is that the client is not in the additive scene on spawning and they are not supposed to see any of the network objects in the additive scene (essentially, the error message above is asking to add a scene condition on the network object despite there being one). 

If you step over this part, there is another issue if the client then enters the additive scene, the network objects do not load. The Client has to exit the additive scene and then re-enter it to see everything. I found that by stepping over the lines in AddConnectionToScene() to bypass adding the additive scene on the client removed this problem allowing the client to enter the additive scene on the first try. 

**Replication**
1. Create a new unity URP project
2. Import the Fishnet package 
3. Off topic step - open the player prefab and assign the camera, otherwise the examples don't seem to work.
4. Open the additive main scene example
5. Off topic step - fix the issue with the missing scriptable object for the spawn prefabs.
6. Run the application for the host and enter the additive scene (connection, not global)
7. Run the application for the client and join the host. The exception above will be thrown.

**Expected behavior**
I would expect the client to be able to join a host late that has entered an additive scene without any exceptions. I would expect the client to be able to move through the main scene and then into the additive scene to join the host and see the network objects synced as the host sees them.

**Videos - Behaviour with and without a fix **
https://github.com/FirstGearGames/FishNet/assets/3323383/567bd8ab-6e7a-4a7e-be66-c8e084c3cac5
https://github.com/FirstGearGames/FishNet/assets/3323383/6a854b45-aaf5-4a0e-8223-8635ac50f7f4

If the above links do not work, alternatives:
https://www.dropbox.com/s/ztyrh6scf1x1gku/With%20Fix.mp4?dl=0
https://www.dropbox.com/s/ztyrh6scf1x1gku/With%20Fix.mp4?dl=0

**Comment by FirstGearGames** [comment]
Can you try changing this method in SceneCondition
```cs
        public override bool ConditionMet(NetworkConnection connection, bool currentlyAdded, out bool notProcessed)
        {
            notProcessed = false;

                /* When there is no owner only then is the gameobject
                 * scene checked. That's the only way to know at this point. */
                return connection.Scenes.Contains(base.NetworkObject.gameObject.scene);
        }```

**Comment by ncorns** [comment]
Unfortunately this didn't work. The late connecting client enters the additive scene and sees nothing, then exits and enters again and can see the network object but in both cases, cannot see the other player (host). When the host then leaves the additive scene, followed by the client, the client crashes.
