### ISSUE TITLE
NetworkObject might raise Null Reference exception.

### ISSUE THREAD

**Issue by jimdroberts** [FirstGearGames/FishNet#369]
Fish-Networking version: 3.6.9

In NetworkObject.cs, NetworkObserver on line 699 might be null when calling ResetForObjectPool if the object is never spawned before adding the object back to an Object pool.

1. Instantiate an object from the ObjectPool.
2. Don't ServerManager.Spawn the NetworkObject.
3. Add the object back to the ObjectPool.

Fix:
Just add a null reference check for NetworkObserver on line 699 in NetworkObject.cs

if (NetworkObserver != null)
    NetworkObserver.Deinitialize(false);

**Comment by FirstGearGames** [comment]
Resolved in 3.7.0
