### ISSUE TITLE
Network Object destruction not occuring if running in a non host manner but have a client and server manager.

### ISSUE THREAD

**Issue by djgaven588** [FirstGearGames/FishNet#372]
**General**
Fish-Networking version: 3.6.9

**Description**
This is quite an odd and probably non typical use case that has caused this issue. We're running both a client and server manager on our servers. These are not operating in a host mode, but instead the client manager is connecting to another server, and the server manager is actually accepting game clients.

We have modified the client manager to never return true for host, as in our use case the client manager will never connect to the server manager on the same instance.

ManagedObjects.cs does this check on line 136:
`nob.Observers.Contains(NetworkManager.ClientManager.Connection)`

Looking into the connection comparison, if the IDs match they are considered equal, but in this case an ID conflict is possible since there are 2 different servers that do not have any sort of synchronized ID generation.

**Replication**
1. Have a client and server manager
2. Modify the client manager to not report host as true
3. Connect the client manager to an outside server, and accept a game client on the server manager
4. Cause a network object owned by the game client to despawn
5. An ID conflict potentially occurs and causes the ManagedObjects to try and wait to destroy the object, which never is executed as the client manager in this case does not change connection state, not allowing it to trigger. If it did fire, this would still not be the expected outcome, as we are wanting to pool the object, not destroy it with a frame delay.

**Expected behavior**
When a client manager is not connected to the same application's server manager, behavior should act as if they are running independently as client and server.

**Fix**
Change line 136 in `ManagedObjects.cs` to be:
`if (NetworkManager.IsHost && nob.Observers.Contains(NetworkManager.ClientManager.Connection))`

This prevents the above described situation and will allow despawning to act as expected.

**Comment by FirstGearGames** [comment]
Why not use two different NetworkManagers?

**Comment by djgaven588** [comment]
This would work, it's currently less development effort to have them on the same NetworkManager though.

**Comment by FirstGearGames** [comment]
This seems like a topic that needs to be discussed. Please create a thread in #open-development with a title and link to this issue.
