### ISSUE TITLE
Trigger collisions not called when scene is loaded using LocalPhysicsMode.Physics3D

### ISSUE THREAD

**Issue by vilmarpimentel** [FirstGearGames/FishNet#374]
**General**
Unity version: 2021.3..25f1
Fish-Networking version: 3.6.9
Link on our Discord where you troubleshot the issue(on Discord click the three dots next to the message, then Copy Message Link): https://discord.com/channels/424284635074134018/1034477094731784302/1107033513695383623

**Description**
On the video above, there is a test on an empty project showing what should happens. Loading an additive scene, using LocalPhysicsMode.Physics3D, the player is teleported from a scene (with the black plane) and spawn on another map (with red plane), there is a trigger zone that identifies the collision nicely. But on this same example using FishNet, the trigger zone do not works. Player gameobject and the trigger zone are in the same scene.

**Replication**
1. Create two scenes. On the second scene, add a trigger collider somewhere with a script that Log "Triggered" OnTriggerEnter
2. Create a simple player controller, spawn on scene 1
3. Load Scene 2 (the one that has the Trigger collider) as additive, using LocalPhysicsMode.Physics3D.
4. Enter the Trigger collider with the player, and the OnTriggerEnter will never be called.

**Expected behavior**
The OnTrigger events should be called.

Here is the script that teleport the player to a map:
`player.mapId = map.mapId;

var position = overridePosition == Vector3.zero ? map.startPosition : overridePosition;

var clientSceneInfo = new ClientSceneInfo()
{
    position = position,
    rotation = map.startRotation
};

SceneLoadData sld = new SceneLoadData(map.mapId);
sld.Options.AllowStacking = map.isInstanced;
sld.Options.AutomaticallyUnload = !map.isCached;

if (sld.Options.AllowStacking)
    sld.Options.LocalPhysics = LocalPhysicsMode.Physics3D;

sld.ReplaceScenes = ReplaceOption.All;
sld.MovedNetworkObjects = new NetworkObject[] { player.NetworkObject };
sld.Params = new LoadParams()
{
    ClientParams = clientSceneInfo.ToBytes()
};

player.OnBeforeTeleport(true);

InstanceFinder.SceneManager.LoadConnectionScenes(player.Connection, sld);`

**Comment by FirstGearGames** [comment]
If anything this is caused by your colliders and how Unity handles scene stacking. This does not sound like a FN bug.

**Comment by vilmarpimentel** [comment]
So basically, when I teleport to the other scene and enter the trigger collider zone, it should cast the OnTrigger, but it's not. And if this doesn't work, we can't make dungeons with trigger zones :/

**Comment by vilmarpimentel** [comment]
The yellow collider is on another scene, and it do not collide with it (expected behaviour) and when I enter the trigger zone, it cast it normally (expected behaviour). But on FN, this collider zone it's never triggered

**Comment by FirstGearGames** [comment]
I'm pretty confident this is not FN related as we do not touch anything
with colliders. There's a very very small but unlikely chance if you're
using rigidbody CSP. Otherwise, not probably not.

I can keep the bug report up but it's going to be backlogged for awhile; I
encourage to troubleshoot it more, especially make sure the objects are in
the right scene.
