### ISSUE TITLE
Attribute annotated methods are not executed when `isNetworked` is set to `false`

### ISSUE THREAD

**Issue by xetra11** [FirstGearGames/FishNet#381]
**General**
Unity version: 2021.3.16f1
Fish-Networking version: 3.5.8hf0
Link on our Discord where you troubleshot the issue(on Discord click the three dots next to the message, then Copy Message Link): https://discord.com/channels/424284635074134018/923983677980045382/1110524132178808902

**Description**
When setting a component (inherited from `NetworkObject`) to `isNetworked` false it happens that annotated methods with i.e. `[Client(RequireOwnership=false)]` and such won't execute. Also `OnStartClient` and those events do not execute as well.

What I'd like to see would be a `offline` flag for `NetworkObject`. That way I can test the logic in a isolated environment without the need to setup any networking. In my use-case that's a "must-have" since I have plenty of features I can't test spinning up a localhost environment everytime.

**Replication**
See Description

**Expected behavior**
Components inheriting from `NetworkBehaviour` can also execute their logic without the need of a established network. This can be realized with an `offline` flag that may set `isNetworked` to false internally and also blends out all network related guard conditions and attributes.

**Comment by FirstGearGames** [comment]
Resolved in 3.7.5
