### ISSUE TITLE
GameObject with a NB and no NO on it serializes as null

### ISSUE THREAD

**Issue by maxkratt** [FirstGearGames/FishNet#382]
**General**
Unity version: 2021.3.22f1
Fish-Networking version: 3.7.2.Experimental.Pro
Link on our Discord where you troubleshot the issue: https://discord.com/channels/424284635074134018/1108372474124570624/1109485798979547156

**Description**
When trying to pass a GameObject across the network it will be null on the other side if it doesn't include a NetworkObject directly on it. This happens even if it has a NetworkBehaviour directly on it and a NetworkObject on one of its parents.

**Replication**
1. Place a game object in the scene with a network object component and a child game object with a network behaviour script.
2. From the player object attempt to send a ServerRpc with the child game object mentioned above.
3. The RPC will run on the server with the GameObject parameter set as null. 
4. This happens as a host client and a solo client.

**Expected behavior**
As per our discussion on Discord, the GameObject should be able to be passed if it has a NetworkBehaviour on it.

**Comment by FirstGearGames** [comment]
Resolved in 3.7.5
