### ISSUE TITLE
Heartbeat / Tugboat Timeout does not seem to work correctly when an app instance crashes

### ISSUE THREAD

**Issue by oculavis-cvar** [FirstGearGames/FishNet#385]
**General**
Unity version: 2023.1.0 (Used as it has Multiplayer Play Mode)
Fish-Networking version: 3.6.9
Link on our Discord where you troubleshot the issue(on Discord click the three dots next to the message, then Copy Message Link): Our team currently does not have a Discord account, so we can only rely on Git Issues for reporting. 

**Description**
We found out that our clients never react to a server/host crashing or being closed unexpectedly in any other way, e.g. via the Task Manager. Even though Tugboat has a timeout setting, it does not seem to be used, as other clients and the server never realize that the server / another client is offline in such a scenario. Is this a bug or intended?

**Replication**
1. Write a simple FishNet app where multiple clients can connect to a host.
2. Add a log for client connection status changes, e.g. OnClientConnectionState and OnRemoteConnectionState, to monitor connection changes.
3. Run one host and multiple clients. Kill one of the clients or the host with the Task Manager (alternatively, run them on another device and let the app crash - that is how we found this potential bug).
4. You will see that the connection change to that client/server will never be registered.

**Expected behavior**
The server / clients log a connection change (e.g. when the server went offline (client) or a client left (server)).

**Screenshots**
None.

**Comment by FirstGearGames** [comment]
Likely not a bug. When you force kill sockets like that they don't send the disconnect. You're at the mercy of C# socket timeouts. It will happen it just might take a little longer.

**Comment by oculavis-cvar** [comment]
Makes sense. Just wanted to add, in case someone has the same issues, that this seemingly does not happen on e.g. "normal" Desktop, but on Windows UWP it does. A timeout never seems to be reached there.

**Comment by FirstGearGames** [comment]
It should eventually... Usually it's a minute or two, just depends on the
system. Ideally it would be cleaned up gracefully but sockets don't always
behave. I can add a setting in the client manager to check for activity and
go through disconnect stuff if none after X time. Server manager, probably
not because it would have to check every connection regularly, and the
timeout feature already exists on the server socket, at least in LNL.
