### ISSUE TITLE
Ping Display and Bandwidth Display cuasing garbage

### ISSUE THREAD

**Issue by Ocean-View-Games** [FirstGearGames/FishNet#391]
**General**
Unity version: 2019.3.19
Fish-Networking version:  3.7.4

**Description**
Ping Display and Bandwidth Display cuasing garbage. In UNITY_SERVER mode.

**Replication**
1. Import fishnet
2. Create blank scene
3. Attach Ping Display and or Bandwidth Display to a gameobject.
4. Press Play
4. Check profiler for GC

**Expected behavior**
No GC should be generated at all

**To Fix**
move #if !UNITY_EDITOR && UNITY_SERVER to above the OnGUI function to fully block the function. Even with a return the GC is still generated

**Comment by FirstGearGames** [comment]
I'll make sure they don't operate on server builds but the rest is up to the user in creating their own.
