### ISSUE TITLE
SyncTimer with PauseTimer(true) not working as expectation

### ISSUE THREAD

**Issue by ndp1100** [FirstGearGames/FishNet#393]
Fish-Networking version: 3.6.9

**Description**
When I tried to Pausetimer(true), then UnPause, Remaining value will be wrong make Timer stop.

I found that PauseTimer and UnpauseTimer set prev and next value = -1, that make SyncTimer not working as I expect.
![Screenshot_1](https://github.com/FirstGearGames/FishNet/assets/3240636/eff4b754-9451-4b74-bad4-28465eaade47)

When I replace value -1 with Remaining value, the issues fixed

**Comment by FirstGearGames** [comment]
-1 is the intended value for some of those scenarios but I see no harm in making it put remaining.
This will be available in 3.7.7.
