### ISSUE TITLE
Unable to lookup LocalConnection for 0 as host.

### ISSUE THREAD

**Issue by Turtleman667** [FirstGearGames/FishNet#395]
**General**
Unity version: 2021.3.15f1
Fish-Networking version: 3.7.5 (tryed it on 3.6.9 and 2.6.4)
Link on our Discord where you troubleshot the issue(on Discord click the three dots next to the message, then Copy Message Link): https://discord.com/channels/424284635074134018/1034477094731784302/1116530071717548082

**Description**
When i build windows server and check locally all is fine and I can connect any count of clients and play (I start check from connecting from editor)
But when I build server for linux and put in on Linux server ive got errors in client when trying to connect from my PC:
```
Unable to lookup LocalConnection for 0 as host.
ObjectId 49512 could not be found in Server spawned, nor Server pending despawn. This may occur as clientHost when objects are destroyed before the client receives a despawn packet. In most cases this may be ignored
```
and looks like this errors causing by instantiating players prefab on connect

**Replication**
To see this problem build server for Linux

**Screenshots**
![image](https://github.com/FirstGearGames/FishNet/assets/25915134/a44a66f1-e8df-46e8-b782-17b8985694c9)

**Comment by FirstGearGames** [comment]
Please try again in the help channels posting stack traces and anything else helpers may need.
