### ISSUE TITLE
non player Rigidbody2d huge desync

### ISSUE THREAD

**Issue by SnaiperoG3D** [FirstGearGames/FishNet#396]
# Important
If General, Description, and Replication are not completed the issue will be closed immediately.

**General**
Unity version: 2021.3.23f1
Fish-Networking version: 3.7.4 Pro
Link on our Discord where you troubleshot the issue(on Discord click the three dots next to the message, then Copy Message Link): 
https://discord.com/channels/424284635074134018/1034477094731784302/1117151534048874657

**Description**
Non owner rigidbody2d object huge jitter on client. I have a csp setup for players and non player objects with dynamic rigidbody2d on the map. When player try to push that object, on server everything fine, but on client look like that object has own not synced velocity and its trying to fly away, but server sending his values and object teleport back. As huge player push object (velocity on client increase) as much more terrible teleports on client. Fix for that is to set rigidbody2d on client to kinematic. Ive checked a new ComponentConfiguration part of networktransform and its missing setup for non client auth. as a result if rigidbody2d was setted to dynamic and networktransform as non client auth, both copies (server and client) will be as dynamic. in my case changing client copy to kinematic fix the issue. Maybe there is no velocity rigidbody2d sync or something. I thought about modify ComponentConfiguration part, but there are might be something that idk, so i just did simple fix script and place it on nessesary objects: https://pastebin.com/E2JT4UJT

**Replication**
1. Setup simple 2D top-down project with csp player (maybe csp not a problem)
2. Disable gravity in project settings -> physics 2d.
3. Place somewhere objects with dynamic rigidbody2d, collider, networktransform with rigidbody2d component config. Set mass something about 1000, to not fly away on push fast
4. Run project with parrelsync. And try to push scene objects by player, they will jitter as harder as hard you push and increase rb velocity on client.

**Expected behavior**
No jitter or client

**Screenshots**
I can record a video

**Comment by FirstGearGames** [comment]
If you need something to be pushed around it must be setup for CSP, rigidbodies presumably, meaning adding a PredictedObject component (for pv1).

**Comment by SnaiperoG3D** [comment]
ive placed a predictedobject to to object and i have almost same result. im checking root object pos and lookslike its working fine, but graphics object still jitter, it start going back and then teleporting forward

**Comment by FirstGearGames** [comment]
In an effort to resolve these quicker can you first try on 3.7.8+, and if problem still exist make a very small unitypackage containing a test scene, prefabs, scripts.

**Comment by SnaiperoG3D** [comment]
i did a test project with fish 3.10.5. used my code for csp movement. setuped 3 different objects with different setup to check all. one setup working good (3 object in project) with small issue, that on client player can sometimes walk incide the objects, what not happening on server, also im getting another problem with this fish version. i have now this error on clients: `StateIndex not found. LastNbTick 18. NB Player(Clone).`
plus, i had another issue before and in this fish version too. when one plyer push other player, in process all fine, but when player stops, pushed player keep moving for some time and then teleports back. as mush lattency in transportmanager -> latency simulator as more distance it keep moving and teleports back. i thought maybe parrelsync is the reason, but i did a standalone win build, and its still present, much less, but still accour

test project: https://drive.google.com/file/d/1kNg0k-o4uAKCBPPfMvoSo_T8kzQfuS9H/view?usp=sharing
create 2 copies in parrelsync. push 3 blue object. sometimes client player goes incide it. 
connect 2 clients and try to push another player, as much lattency as much it keep moving and teleports back
error appear on client as it connect to server

**Comment by FirstGearGames** [comment]
The error can be ignored. It was debug left in by mistake but should only occur periodically.
Do you have a smaller project? Make sure you are using FN free btw. 
You only need to export files as a Unitypackage so it won't include the junk.

**Comment by SnaiperoG3D** [comment]
its an 5mb zip empty project with few scripts, but ok, i did export. installed free fish from github, same things happening. also much more intersectiong in editor with parrelsync. in build everything much better.
https://drive.google.com/file/d/1dOqhTJeJxx5Hgl5BPensSxbRcppDByNY/view?usp=sharing

**Comment by SnaiperoG3D** [comment]
ive did a video. also ive tested it on mobile + standalone + editor + server on standalone linux dedic. and im facing an issue, that on mobile other client have huge jitter when moving, they moving, then stops, then moving again. same thing happens on editor and win standalone but much less. here is a video:
https://drive.google.com/file/d/15kmtilL4nSQeq2wdk7hnmrWf6n-j750P/view?usp=sharing

**Comment by SnaiperoG3D** [comment]
well, due that fact that i cant find anyone with that experience in discord as a help with it, ive figired out next thing. i need a player movement done without drifting, to be a clamp like in io games, so ive used rb.moveposition, ive changed that logic to rb.addforce and increased linear drag in rb2d. now thing going much better, there is no continious pushing issue anymore, but still jitter moving, not huge, but annoying, also this jitter much worster on mobile, on mobile other clients still moving, stops moving for half a sec, and moving again

**Comment by SnaiperoG3D** [comment]
i guess i found the point with jitter (move, stops, move), but have no idea what cause it. for some reason, same csp movement code, same framerate move player slower on mobile rather the other platforms: editor or win standalone

**Comment by SnaiperoG3D** [comment]
update. i released my project to testers. and i have weird result, that for some reason this issue appears only on my phone. movement good on other devices, and it might be somehow releated to Unity itself, or idk

**Comment by SnaiperoG3D** [comment]
omg, after so many hours i finnaly found it. i disabled my wifi, and all working almost great. still some little jittering, but fine. idk what is it, but without my wifi its working much much better

**Comment by FirstGearGames** [comment]
Is this not an issue then?

**Comment by SnaiperoG3D** [comment]
well, i guess there is something wrong with playing with wifi. i have no idea whats wrong. mobile network working good. wifi have this issue. i will do more tests

**Comment by FirstGearGames** [comment]
If anything I'd expect the opposite. Maybe something is going on with your internal network vs mobile. If the issue persist you can make a small sample project for me please and I'll take a look.
