### ISSUE TITLE
NullReferenceException in NetworkTransform on Stopping Server

### ISSUE THREAD

**Issue by ooonush** [FirstGearGames/FishNet#397]
**General**
Unity version: 2022.3
Fish-Networking version: 3.7.5

**Description**
The error occurs on NetworkObjects with DefaultDespawnType = Pool. Checked on scene **ReplaceMain** `Assets\FishNet\Example\All\SceneManager\Scenes\Replace\ReplaceMain.unity`.

**Replication**
1. Go to `Assets\FishNet\Example\All\SceneManager\Scenes\Replace\ReplaceMain.unity`
2. Select **Player** Prefab in **NetworkManager** and set **DefaultDespawnType = Pool**.
3. Start as Host -> Stop Server.
4. See console.

**Screenshots**
![image](https://github.com/FirstGearGames/FishNet/assets/72870405/29eb164f-75bf-45fb-8a58-10e53a69bcea)

**Comment by FirstGearGames** [comment]
Should be a harmless error. I've added a check though to ensure it does not occur.
```cs
        private void ChangeTickSubscription(bool subscribe)
        {
            if (subscribe == _subscribedToTicks || base.NetworkManager == null)
                return;
```
Resolved in 3.7.7
