### ISSUE TITLE
NetworkTransform Rigidbody configuration is missing code and is incorrect

### ISSUE THREAD

**Issue by NonPolynomialTim** [FirstGearGames/FishNet#399]
**General**
Unity version: 2022.2.13
Fish-Networking version: 3.7.5hf0
…
Link on our Discord where you troubleshot the issue(on Discord click the three dots next to the message, then Copy Message Link): 
https://discord.com/channels/424284635074134018/1034477094731784302/1117997317514076260

**Description**
Setting a NetworkTransform's Component Configuration to `Rigidbody` will set server-owned rigidbodies to kinematic due to a missing early return.  I believe NetworkTransform.cs is missing code on line 730 (which can be seen in the screenshot below), and lines 742-743 should be copied in at line 730 to prevent setting server-owned rigidbodies to kinematic.

**Replication**
1. Create a new scene with a single gameobject with rigidbody and NetworkTransform components.
2. Set the NetworkTransform's Component Configuration to `Ridigbody`.
3. Start the game as a server only

**Expected behavior**
Since scene objects are server-owned by default, the rigidbody should react to physics on the server.

**Actual behavior**
The server-owned object is set to kinematic on the server and all clients, rendering the rigidbody inert.

**Screenshots**
![image](https://github.com/FirstGearGames/FishNet/assets/10065854/1f276ba6-8275-4877-a5b3-0370bbc432e8)

**Comment by dnnkeeper** [comment]
Exactly what I just found myself! I guess It should be `bool isKinematic = _clientAuthoritative && (!base.IsOwner || base.IsServerOnly);` because it makes sense only if client has authority over this object (which also should never happen for scene objects)

**Comment by FirstGearGames** [comment]
> **General** Unity version: 2022.2.13 Fish-Networking version: 3.7.5hf0 … Link on our Discord where you troubleshot the issue(on Discord click the three dots next to the message, then Copy Message Link): https://discord.com/channels/424284635074134018/1034477094731784302/1117997317514076260
> 
> **Description** Setting a NetworkTransform's Component Configuration to `Rigidbody` will set server-owned rigidbodies to kinematic due to a missing early return. I believe NetworkTransform.cs is missing code on line 730 (which can be seen in the screenshot below), and lines 742-743 should be copied in at line 730 to prevent setting server-owned rigidbodies to kinematic.
> 
> **Replication** Steps to reproduce the behavior:
> 
>     1. Create a new scene with a single gameobject with rigidbody and NetworkTransform components.
> 
>     2. Set the NetworkTransform's Component Configuration to `Ridigbody`.
> 
>     3. Start the game as a server only
> 
> 
> **Expected behavior** Since scene objects are server-owned by default, the rigidbody should react to physics on the server.
> 
> **Actual behavior** The server-owned object is set to kinematic on the server and all clients, rendering the rigidbody inert.
> 
> **Screenshots** ![image](https://user-images.githubusercontent.com/10065854/245333903-1f276ba6-8275-4877-a5b3-0370bbc432e8.png)

> Exactly what I just found myself! I guess It should be `bool isKinematic = _clientAuthoritative && (!base.IsOwner || base.IsServerOnly);` because it makes sense only if client has authority over this object (which also should never happen for scene objects)

This could be a tricky situation. Making kinematic when client auth and not owner or server only makes sense if you are client only and not the owner.

But keep in mind client auth is enabled by default, so for objects where no owner would be expected the server would still set this kinematic due to the following:
- client auth.
- not owner (server wouldn't be owner). (condition met)
- is server only. (condition met).

**Comment by FirstGearGames** [comment]
Perhaps this?
```cs
            bool CanMakeKinematic()
            {
                if (_clientAuthoritative)
                    return (!base.IsOwner || base.IsServerOnly);
                else
                    return !base.IsServer;
            }
```
