### ISSUE TITLE
LOD - Client Disconnect ServerRpc - Variable Tick Rate

### ISSUE THREAD

**Issue by WelfareCheckVS** [FirstGearGames/FishNet#421]
**General**
Unity version:  2021.3.16f1
Fish-Networking version: 3.10.1
[Link on our Discord where you troubleshot the issue(on Discord click the three dots next to the message, then Copy Message Link): ]https://discord.com/channels/424284635074134018/958788907577790465/1129827282442268702

**Description**
Client disconnects when sending ServerRpc if LOD is enabled (any range settings with Nth distances) and Time Manager tick rate is set to variable. 

**Replication**
1. Create blank project
2. Setup Network Manager with Time Manager set Timing Type to variable (any tick rate)
3. Create LOD on Observer Manager (any distances)
4. Connect client and send ServerRpc
5. Disconnect is 80/20 chance but usually on first send.
6. Client disconnect message: Connection [1] sent excessive level of detail updates.  (See attached LodError.txt)

**Expected behavior**
No disconnect when sending ServerRpc

[LodError.txt](https://github.com/FirstGearGames/FishNet/files/12100397/LodError.txt)

**Comment by FirstGearGames** [comment]
Resolved in 3.10.3.
Inside ServerManager.LOD -> ParseNetworkLODUpdate change
`
uint packetTick = conn.PacketTick.Value(NetworkManager.TimeManager);
`
to
`
uint packetTick = conn.PacketTick.LastRemoteTick;
`
