### ISSUE TITLE
Server authoritative movement for scene object works between builds but not between build and editor. 

### ISSUE THREAD

**Issue by etn218n** [FirstGearGames/FishNet#422]
**General**
Unity version: 2022.3.5f1
Fish-Networking version: 3.10.1 Pro

**Description**
Server authoritative movement for scene object works between builds (1 build instance for host and another for client) but not between build and editor. 

**Replication**
1. Add a GameObject with NetworkTransform. Client Authoritative and Send to owner are unticked.
2. Add simple NetworkBehaviour with movement by setting transform.position. This is done in Update() loop with IsServer if guard.
3. Make a standalone Windows Build.
4. Create a server as Host or Server only in the build. Join as client with the editor. The host can see the scene object moving but client does not. Some errors show up on log console.  The same error happens if the host is the editor and client is the build. Only client and server between build instances work.

**Expected behavior**
Server authoritative movement for scene object should work between editor and build instances.

**Screenshots**
<img width="521" alt="error" src="https://github.com/FirstGearGames/FishNet/assets/45911945/77a84c07-48d8-4318-99cd-69ff133deffa">

**Comment by FirstGearGames** [comment]
Please provide a link where you troubleshot the issue and re-open if needed.

**Comment by etn218n** [comment]
Hi. The discord link has been provided. How can I re-open the issue?
