### ISSUE TITLE
ServerRPC is not sending if you're using Spawn() before

### ISSUE THREAD

**Issue by Stormhound** [FirstGearGames/FishNet#423]
# Important
If General, Description, and Replication are not completed the issue will be closed immediately.

**General**
Unity version: 2021.3.24f1
Fish-Networking version:  3.7.7 Pro
Link on our Discord where you troubleshot the issue(on Discord click the three dots next to the message, then Copy Message Link): 
https://discord.com/channels/424284635074134018/1034477094731784302/1131527797022670858

**Description**
I'm using Predicted Spawn on a object then in the same method I'm trying to send server rpc afterwards but Spawn() blocking the server rpc

**Replication**
1. Create C# script with NetworkBehaviour
2. In script get a reference to a prefab that contains NetworkObject + PredictedSpawn
3. Enable PredictedSpawning
4. In script create a method for client to run, inside the script first Instantiate the prefab then use Spawn(); for that object.
5. Try to send ServerRPC after the Spawn(); method
6. ServerRPC shouldn't be called due to Spawn(); method.

**Expected behavior**
ServerRPC should be called, right?

**Screenshots**

**Comment by FirstGearGames** [comment]
Update to 3.10.2 and try again. Won't troubleshoot for your version sorry.

**Comment by Stormhound** [comment]
Issue seems resolved with 3.10.3
