### ISSUE TITLE
SceneManager.OnLoadEnd is called twice on Host

### ISSUE THREAD

**Issue by makcimbx** [FirstGearGames/FishNet#424]
**General**
Unity version: 2022.3.4f1
Fish-Networking version: 3.10.2
Link on our Discord where you troubleshot the issue(on Discord click the three dots next to the message, then Copy Message Link): https://discord.com/channels/424284635074134018/1034477094731784302/1131643994997268631

**Description**
When using networkManager.SceneManager.OnLoadEnd, after scene load its called twice on Host.

**Replication**
1. Two players, client and host
2. Server run networkManager.SceneManager.LoadGlobalScenes
3. Client get one OnLoadEnd
4. Host get two OnLoadEnd

**Expected behavior**
OnLoadEnd called once

**Comment by FirstGearGames** [comment]
Issue was not troubleshot. Posting the same thing without troubleshooting does not quality.
