### ISSUE TITLE
OnChange event is called 8 times on host

### ISSUE THREAD

**Issue by vilmarpimentel** [FirstGearGames/FishNet#426]
**General**
Unity version: 2022.3.5f1
Fish-Networking version: 3.10.2

**Description**
The OnChange event on SyncDictionary is being called 8 times on host. On the previous version that I was using (3.7.11) was just being called twice (that's expected, one as client one as server)

**Replication**
1. Create a SyncDictionary on any network behavior.
2. Add a method to OnChange event.
3. Add a member to the dictionary

**Expected behavior**
The OnChange should not be duplicated for client/server with the same operation.

**Comment by FirstGearGames** [comment]
Unable to replicate. Please try to debug on our Discord server and make a reply with that thread and any new findings. Thanks.
```cs
using FishNet.Object;
using FishNet.Object.Synchronizing;
using UnityEngine;

public class SLCallbackTest : NetworkBehaviour
{
    public bool Add;
    [SyncObject]
    private readonly SyncList<uint> _syncList = new SyncList<uint>();

    private void Awake()
    {
        _syncList.OnChange += _syncList_OnChange;
    }

    private void _syncList_OnChange(SyncListOperation op, int index, uint oldItem, uint newItem, bool asServer)
    {
        string msg = $"Operation {op}. AsServer {asServer}. NewItem {newItem}";
        if (asServer)
            Debug.Log(msg);
        else
            Debug.LogWarning(msg);
    }

    public void Update()
    {
        if (Add)
        {
            Add = false;
            _syncList.Add(base.TimeManager.LocalTick);
        }
    }
}
```
