### ISSUE TITLE
Obsolete code

### ISSUE THREAD

**Issue by samhubbard** [FirstGearGames/FishNet#44]
This is popping up in Unity 2021.3.0f1

`Assets/Plugins/FishNet/Runtime/Transporting/Transports/Multipass/Multipass.cs(656,30): warning CS0672: Member 'Multipass.SetServerBindAddress(string)' overrides obsolete member 'Transport.SetServerBindAddress(string)'. Add the Obsolete attribute to 'Multipass.SetServerBindAddress(string)'.
`

`Assets/Plugins/FishNet/Runtime/Transporting/Transports/Multipass/Multipass.cs(670,13): warning CS0618: 'Transport.SetServerBindAddress(string)' is obsolete: 'Use SetServerBindAddress(IPAddressType)'
`

`Assets/Plugins/FishNet/Runtime/Managing/Server/Object/ServerObjects.cs(577,50): warning CS0618: 'ListCaches.NetworkConnectionCache' is obsolete: 'Use GetNetworkConnectionCache instead.'
`

**Comment by FirstGearGames** [comment]
You shouldn't see those messages. Try deleting your FN folder and reimport 148.

**Comment by samhubbard** [comment]
I'm sorry. I should have specified that I am running 1.4.8. I've deleted and reimported FN and receive the same warnings.

**Comment by FirstGearGames** [comment]
This has been resolved in 1.4.9. Thanks!

**Comment by samhubbard** [comment]
Awesome, I'll grab that version as soon as it's available.
