### ISSUE TITLE
Minor: Fixable garbage generation in ServerObjects.Observables RebuildObservers

### ISSUE THREAD

**Issue by Exokide** [FirstGearGames/FishNet#445]
General
Unity version: 2021 LTS
Fish-Networking version: 3.7.11

Description
A lot of methods are named RebuildObservers, might want to work on that.

The RebuildObservers that runs all the foreach loops taking in IEnumerables for nobs and conns really generates a lot of garbage even on Il2CPP compiled versions we are talking multiple KB a tick.

There are maybe a few ways to go about this but in testing the best way I could find was by changing the method signature to a set of Generics with IList<NetworkObject> and IList<NetworkConnection> restrictions which supports Lists and Arrays and then changing the foreach loops to for loops (also caching the x.Count variables (very minor) )

This obviously locks out things like real Enumerables and HashSets, but this can be rectified by keeping the old method as well and just changing all the callers that can support this faster method (currently all I believe)

`public void RebuildObservers<T1, T2>(T1 nobs, T2 conns, bool timedOnly = false) where T1 : IList<NetworkObject> where T2 : IList<NetworkConnection>`

**Comment by FirstGearGames** [comment]
Did you profile this? I did a quick check and found 0 allocations besides GUI Repaint (normal).
```cs
public void RebuildObservers(IEnumerable<NetworkObject> nobs, IEnumerable<NetworkConnection> conns, bool timedOnly = false)
```

I used the HashGrid demo scene, turned on VSync, and examined 1 second of profiler. During that time 30 calls (tick rate) were made where both IEnumerables had values and no GC was allocated.
