### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Ghalbeyou** [FirstGearGames/FishNet#446]
# Important
If General, Description, and Replication are not completed the issue will be closed immediately.

**General**
Unity version: 2022.1.24f1 
Fish-Networking version: 3.10.7R
Discord link: 
** Above, post a link from our Discord where you troubleshot the issue (on Discord click the three dots next to the message, then Copy Message Link). This is only required if you are unable to provide consistent replicate steps and/or do not know the exact cause of the problem.

**Description**
When Importing the asset, it gives me error and when restarting, more errors.

**Replication**

Just importing the asset to unity 2022.1.24f1 after a restart, error happens

**Expected behavior**
Assets\FishNet\Runtime\Managing\Timing\TimeManager.cs(499,25): error CS0117: 'Physics' does not contain a definition for 'simulationMode'

Assets\FishNet\Runtime\Managing\Timing\TimeManager.cs(499,42): error CS0103: The name 'SimulationMode' does not exist in the current context

Assets\FishNet\Runtime\Managing\Timing\TimeManager.cs(504,25): error CS0117: 'Physics' does not contain a definition for 'simulationMode'

Assets\FishNet\Runtime\Managing\Timing\TimeManager.cs(504,42): error CS0103: The name 'SimulationMode' does not exist in the current context

**Screenshots**

**Comment by FirstGearGames** [comment]
Troubleshot on Discord please.

**Comment by quimodotcom** [comment]
See everyone, this is how you don't solve a problem. But never fear, no need to "Troubleshot on Discord please.", go to the TimeManager script and change line 493 from 

`#if UNITY_2022_1_OR_NEWER`

to

`#if UNITY_2022_2_OR_NEWER`
