### ISSUE TITLE
Unchilding rigidbodies from a v2 predicted object, for example a ragdoll from a character, conflicts with rigidbody pauser of parent predicted object.

### ISSUE THREAD

**Issue by Baerikus** [FirstGearGames/FishNet#449]
**General**
Unity version: 2022.3.5f1, but should not matter.
Fish-Networking version: 3.10.7R - Using prediction v2
Discord link to the message where you requested opening a bug report for this:
https://discord.com/channels/424284635074134018/1104850498290462821/1144992057866322020

**Description**
You told me It's not really a bug, but I should open a bug report anyway because you could see the necessity for it. 

Currently, in v2 it seems not be possible to unchild the character mesh from the character predicted object, in case of character death for example, to be able to use it as a client sided ragdoll. As far as I can tell, this is related to the predicted object setting up rigidbody pausers for every child rigidobdy. 

A feature to update this rigidbody pauser values after unchilding, or something similar, to be able to use the character mesh as client sided ragdoll, would be appreciated. 

Maybe combined with this, a simple component that replaces the old "offline rigidbody" could also help to configure client sided rigidbodies if it would overwrite the rigidbody pauser or similar.

**Current Workaround**
Make the RigidbodyPauser of the NetworkObject public instead of internal and call "UpdateRigidbodies" on it, after unparenting. This seems to work for now but requires changing fishnet code.

**Comment by FirstGearGames** [comment]
Added NetworkObject.RigidbodyPauser.UpdateRigidbodies() in 3.11.1
