### ISSUE TITLE
Prediction V2: Replicate() simulates too far ahead, jumps around for observers

### ISSUE THREAD

**Issue by RyanGarber** [FirstGearGames/FishNet#461]
While Replicate() and Reconcile() work flawlessly on the owner and the server, it does not for observers. The simulation is too far ahead of them and seems to jump around in time.

More information, a video example, and the project itself are in this repo: https://github.com/RyanGarber/FishNet-PV2/tree/main#observer-replicate-bug

**Comment by FirstGearGames** [comment]
This does not appear to be a bug. You are manually assuming the predicted inputs will be the same as the previous user created. We do provide an example demonstrating this but that example was intended as an example of degrading prediction.

EG: if you have a car moving forward you continue to move it forward with less predicted input each time.
```cs
if (state.IsPredicted)
   state,Foward *= 0.75f; //reduce forward by 25% but continue to move forward under the assumption the player is still moving forward.
```

To be clear, you never need to use predict future inputs, it is optional. But by predicting future inputs with some erosion on the values can help keep the object in real-time/the future more.

**Comment by RyanGarber** [comment]
From what I understand, I should be ignoring/reducing inputs on observers when the state is Predicted, and using the actual input when it is UserCreated. Is this correct?
