### ISSUE TITLE
Connectivity bugs when using Multipass transport with domain reload disabled

### ISSUE THREAD

**Issue by xaevman** [FirstGearGames/FishNet#471]
**General**
Unity version: 2022.3.6f1
Fish-Networking version: 3.11.2
Discord link: https://discord.com/channels/424284635074134018/1034477094731784302/1157004728299946046
Proposed Fix: https://github.com/FirstGearGames/FishNet/pull/473

**Description**
When testing in-editor, using the Multipass transport, with domain-reload disabled for faster play-in-editor iteration time, clients can start receiving network traffic about spawned entities before they have actually completed scene loads and network initialization.

This leads to warnings on the client like:
`Spawned NetworkObject was expected to exist but does not for Id 28.`
`Received a spawn objectId of 30 which was already found in spawned, and was not predicted.`

This appears to be caused by the fact that `ClientTransportData` objects are added back into the static `ResettableObjectCache<>` multiple times during the call to `ResetLookupCollections()` because the same object (which is a class/reference type) is added to both the `_multpassIdLookup` and various `_transportIdLookup` tables. Since the backing ObjectCache now contains multiple entries which point to the same `ClientTransportData` object, and since those static caches will not be cleared between play-in-editor sessions without a .NET domain reload occurring, consumers of the ObjectCache during the next run will accidentally be mutating the state of shared `ClientTransportData` objects. My understanding starts to fade here, but this obviously causes confusion when those objects are subsequently used to look up connection addresses and state.

This can be verified by making a small modification to `ResetLookupCollections` to ensure that no `ClientTransportData` object is pushed back into the object cache twice:
```        
private void ResetLookupCollections()
{
    // be careful not to store the same ctd in the ObjectCache multiple times.
    var ctds = new HashSet<ClientTransportData>();

    /* If being destroyed the editor
     * or application is probably quitting,
     * but cache stuff anyway to save perf. */
    foreach (ClientTransportData item in _multpassIdLookup.Values)
    {
        ctds.Add(item);
    }
    _multpassIdLookup.Clear();

    for (int i = 0; i < _transportIdLookup.Count; i++)
    {
        foreach (ClientTransportData item in _transportIdLookup[i].Values)
        {
            ctds.Add(item);
        }

        _transportIdLookup[i].Clear();
    }

    foreach (var ctd in ctds) {
        ctd.ResetState();
        ResettableObjectCaches<ClientTransportData>.Store(ctd);
    }
}
```

This works, but I think a better fix is to stop using the cache entirely in this case. `ClientTransportData` is only 12 bytes in size, so it could easily be a struct and be used by-value very efficiently. The release-mode version of Multipass already does everything by value, so I don't think this is an issue there.

**Replication**
- Prereqs
    - A scene with a simple spawned and networked player object
    - Player object should have something to synchronize. A SyncVar is an easy test
    - Set up NetworkManager to use Multipass transport
    - Add two or more transports (we use Tugboat for local testing and FishySteamworks for remote clients)
    - Disable domain reload in project settings
        - Edit -> Project Settings -> Editor -> Enter Play Mode Options (checked), Reload Domain and Reload Scene unchecked
    - You need some strategy to test two separate instances simultaneously. We use ParallelSync to run two editors
        - Configure one instance as Host
        - Configure the other instance as Client, connecting to 127.0.0.1 on whatever port you set up for Tugboat
- Enter play on Host instance. Verify player object spawns in correctly. This should work fine.
- Enter play on Client instance. Verify players are spawned in and synchronizing correctly. This should work fine.
- Stop Client
- Stop Host
- Enter play on Host instance again. Once again, the host should run correctly
- Enter play on the Client instance again. 
- Observe warnings on the client about nonexistant or unexpected objectIds being received until `OnLoadedStartScenes` completes

**Expected behavior**
Clients do not start receiving spawned object data until they are fully registered.

**Comment by FirstGearGames** [comment]
Suppose it is true we do not need classes in this case. It was done to simplify the code but structs are lower risk in this sense.

Unfortunately HashCode.Combine is not available in 2019 net2.0.

How do we feel about this implementation until FishNet v4(which is dropping Unity 2019).

```cs
        public int A;
        public int B;
        public int C;

        public TestStruct(int a, int b, int c)
        {
            A = a;
            B = b;
            C = c;

        }

        public bool Equals(TestStruct other)
        {
            return (A, B, C).GetHashCode() == other.GetHashCode();
        }
```

**Comment by FirstGearGames** [comment]
Marking as resolved but let me know if you've any input.

Resolved in 3.11.3

**Comment by xaevman** [comment]
> Suppose it is true we do not need classes in this case. It was done to simplify the code but structs are lower risk in this sense.
> 
> Unfortunately HashCode.Combine is not available in 2019 net2.0.
> 
> How do we feel about this implementation until FishNet v4(which is dropping Unity 2019).
> 
> ```cs
>             /// <summary>
>             /// Cached hashcode for values.
>             /// </summary>
>             private int _hashCode;
> 
>             public ClientTransportData(int transportIndex, int transportId, int multipassId)
>             {
>                 TransportIndex = transportIndex;
>                 TransportId = transportId;
>                 MultipassId = multipassId;
>                 _hashCode = (transportIndex, transportId, multipassId).GetHashCode();
>             }
> 
>             public bool Equals(ClientTransportData other)
>             {
>                 return (_hashCode == other._hashCode);
>             }
> ```

Ahh yeah, hadn't thought about the older Unity versions. Sounds good!

**Comment by FirstGearGames** [comment]
Keeping open until release.
