### ISSUE TITLE
[Prediction V2] Jitter on Camera follow using Lerp/Damps

### ISSUE THREAD

**Issue by gresc574** [FirstGearGames/FishNet#474]
**General**
Unity version: 2021.3.24f1
Fish-Networking version: 3.11.0R.Pro
Discord link: Not my origin thread but its the same issue https://discord.com/channels/424284635074134018/1155989794107699363 / prediction-v2 channel https://discord.com/channels/424284635074134018/1104850498290462821/1156717554119745607

**Description**
**Using PredictionV2** Adding any kind of Lerp or Damp to a Camera following a Predicted graphical object causes jitter.

**Replication**
1. Run the Predictive V2 Rigidbody Demo
2. Place Cinemachine into scene
3. Hit Play
4. Set Follow/Look at Target to predictive graphical object and add dampening
![image](https://github.com/FirstGearGames/FishNet/assets/5010049/8c6712e9-8b54-4381-8b70-3693ca34e115)
5. Notice Jitter when moving / rotating. But only when using Damp values.

Same can be reproduced without using cinemachine 
![image](https://github.com/FirstGearGames/FishNet/assets/5010049/0ca71ce6-f0a6-46a6-b49e-2f3ff3bea94c)

Setting Position / Rotation values without lerps / damps causes no jitter

**Expected behavior**
Using Lerps/Damps on a Camera following the graphical object shouldn't cause jitter

**Comment by FirstGearGames** [comment]
This is likely a camera configuration issue. Camera movement on an already smoothed object can be funky sometimes. First try having the camera move in late update, and if that does not fix it please use our help channels.
