### ISSUE TITLE
_syncTypeWriters in NetworkBehaviour not Return Writers to pool

### ISSUE THREAD

**Issue by duyca** [FirstGearGames/FishNet#476]
**General**
Unity version: 2022.3.1
Fish-Networking version: 3.7.6.Pro

**Description**
_syncTypeWriters in NetworkBehaviour not Return Writers to pool. It lead to leak memory on Server long run

**Replication**
1. Just Give it a look

**Expected behavior**
Writers should back to the pool when NetworkBehaviour get Destroy.

**Screenshots**
![image](https://github.com/FirstGearGames/FishNet/assets/28534354/69813fbf-5ad6-4af1-9d8c-e08e2c05c547)

**Comment by FirstGearGames** [comment]
They are never pulled from the pool, so this would create a leak. I'll look to improve this in v4.
