### ISSUE TITLE
The Write method in the custom serializer is not called for SyncVar.

### ISSUE THREAD

**Issue by ooonush** [FirstGearGames/FishNet#479]
**General**
Unity version: 2022.3.4f1
Fish-Networking version: 3.11.2

**Description**
The Write method in the custom serializer is not called for SyncVar.
This happens in one project of mine, although the exact same code works without error in another project.

**Replication**
```csharp
[SyncVar] private SessionPlayer _ownerPlayer;
```
Custom serializer:
```csharp
public static void WriteSessionPlayer(this Writer writer, SessionPlayer player)
{
    writer.WriteInt32(player.NetworkConnection.ClientId);
    writer.WriteInt32(player.ClientPlayerId);
    Debug.Log("Write: " + player.ClientPlayerId); // Not called
}

public static SessionPlayer ReadSessionPlayer(this Reader reader)
{
    int connectionId = reader.ReadInt32();
    int clientPlayerId = reader.ReadInt32();
    Debug.Log("Read: " + clientPlayerId); // Called
    NetworkManager networkManager = reader.NetworkManager;
    return new SessionPlayer(networkManager, clientPlayerId, connectionId);
}
```

I also added Debug.Log to SyncVar.WriteDelta:
![image](https://github.com/FirstGearGames/FishNet/assets/72870405/468b0831-d01c-4e54-8a31-bc577b6fe89c)

You can see that the custom Writer is not called because nothing is output to the console.
![image](https://github.com/FirstGearGames/FishNet/assets/72870405/c0d97987-2d1e-4af8-b906-5a11ebba1cb1)
WriteBoolean() is called instead.

![image](https://github.com/FirstGearGames/FishNet/assets/72870405/11df4f15-a4e4-45e9-bf52-555966bdb204)

![image](https://github.com/FirstGearGames/FishNet/assets/72870405/f4fff68b-04f5-4174-b20e-00185f9ac5f6)

**Comment by ooonush** [comment]
Found a generated method that is called for Write.

![image](https://github.com/FirstGearGames/FishNet/assets/72870405/9b162ad0-e076-4c43-9d63-8386e7bbec78)

![image](https://github.com/FirstGearGames/FishNet/assets/72870405/65d4e541-6675-4cbc-a1fb-d5042ce520a7)

**Comment by ooonush** [comment]
I changed the IsConnectedFirstTime and it seems to work fine now.

![image](https://github.com/FirstGearGames/FishNet/assets/72870405/73a618a9-6a4d-4b84-977a-4182174efd5b)

![image](https://github.com/FirstGearGames/FishNet/assets/72870405/1e7e2a43-2e30-4a0e-9bb1-85dddd027a20)

**Comment by ooonush** [comment]
I added the [CodegenExclude] attribute and the error disappeared.

**Comment by ooonush** [comment]
Nope, now it can't find the serializer.

![image](https://github.com/FirstGearGames/FishNet/assets/72870405/35f8daba-4c9b-4a69-92d5-1f0abb2ca1e2)

**Comment by FirstGearGames** [comment]
Yeah, it cannot find serializers across assemblies because of Unity limitations. Each assembly is processed one at a time and this is done by Unity during script compilation; I cannot reference previously iterated assemblies.

Generated serializers cannot possible know how you want to initialize new instances of your object, and that's where custom serializers come in. You of course have the issue then of not seeing them cross assembly. You SHOULD be able to copy the serializer into all assemblies which use the struct and have it work though. It's not a great option but at this time it's all we have with how Unity works.

**Comment by FirstGearGames** [comment]
Closing this out as a Unity limitation.
