### ISSUE TITLE
Error NullReferenceException

### ISSUE THREAD

**Issue by waella** [FirstGearGames/FishNet#48]
I try the lobby example using 1.5.1. Got an  error NullReferenceException

buy in 1.4.8 pro is success. it might be a bug

![image](https://user-images.githubusercontent.com/7343178/169202214-b4e4afae-a0f9-44ce-847f-2c0f136aabf2.png)

**Comment by FirstGearGames** [comment]
Thanks, will check into it.

**Comment by FirstGearGames** [comment]
I plan to try and replicate this today.

**Comment by FirstGearGames** [comment]
I forgot to update you on this, I'm sorry about that. I was not able to reproduce but I tested on a newer version which I believe had solved the bug. Please re-open if problem persist. Thanks!
