### ISSUE TITLE
NetworkTransform is not fully resetting when object despawns to pool

### ISSUE THREAD

**Issue by evbishop** [FirstGearGames/FishNet#481]
**General**
Unity version: 2021.3.18, 2022.3.10
Fish-Networking version: 3.11.1.R.Pro
Discord link: https://discord.com/channels/424284635074134018/1157177254565126144

**Description**
NetworkTransform doesn't fully reset when despawning server-owned pooled network objects.

**Replication**

Spawner script:
```
public class Spawner : NetworkBehaviour
{
    [SerializeField] NetworkObject cube;

    public override void OnStartServer()
    {
        base.OnStartServer();
        InvokeRepeating(nameof(SpawnCube), 4, 2);
    }

    void SpawnCube()
    {
        NetworkObject no = NetworkManager.GetPooledInstantiated(
            cube,
            transform.position,
            transform.rotation,
            IsServer);
        
        Spawn(no);
    }
}
```

Script of a cube to spawn:
```
public class Cube : NetworkBehaviour
{
    public override void OnStartServer()
    {
        base.OnStartServer();
        Invoke(nameof(DespawnCube), 1.5f);
    }

    void DespawnCube()
    {
        Despawn(NetworkObject);
    }

    void Update()
    {
        if (IsServer)
            transform.position += new Vector3(Time.deltaTime * 5, 0f, 0f);
    }
}
```

Setup the spawner on the scene and setup the cube prefab. The screenshot section contains details.

Start two instances of the project, start the server (and optionally the client) in one of them, the client on the other. 
Wait for a cube to spawn, despawn and respawn.
Observe what happens on the client: the cube first spawns in the desired coordinates but then starts to interpolate from the coordinates that it was despawned at to the coordinates that it should be at.

**Expected behavior**
The object on client is moving in sync with the object on the server after getting respawned from pool

**Screenshots**
Setup the prefab of the cube to spawn:
![image](https://github.com/FirstGearGames/FishNet/assets/16606035/6f26cefc-0096-402d-b052-39c73ff54b79)

Setup the spawner on the scene:
![image](https://github.com/FirstGearGames/FishNet/assets/16606035/27a78921-4dc2-42a0-a725-115da481144a)

**Comment by FirstGearGames** [comment]
Thanks for the script. This is something we've seen come across our radar a couple times but have not been able to replicate. Hopefully we can now isolate it for good using your script.

**Comment by maxkratt** [comment]
Here's a unitypackage of the problem using the provided scripts in case it saves time @FirstGearGames 
[PoolingProblem.zip](https://github.com/FirstGearGames/FishNet/files/12783290/PoolingProblem.zip)

**Comment by duyca** [comment]
ah i got face it before. Look like _currentGoalData from NetworkTransform not reset when object Despawn.

**Comment by FirstGearGames** [comment]
I believe the data is supposed to be set via SetDefaultGoalData when the
object is spawned again. There might be some condition causing that part to
fail. Does marking it invalid in OnNetworkStop resolve the issue?

**Comment by duyca** [comment]
yes. i reset _currentGoalData in SetDefaultGoalData, right affter _lastReceivedTransformData reset.
_currentGoalData.Transforms.Update(_lastReceivedTransformData);
But in some case it still got error rotation so i got reset it to identity inside OnDisable and it work great for me.

**Comment by duyca** [comment]
![image](https://github.com/FirstGearGames/FishNet/assets/28534354/2622d795-10c3-492f-98dd-633c17dc03be)

**Comment by FirstGearGames** [comment]
Resolved after testing.
