### ISSUE TITLE
No getting started guide in docs?

### ISSUE THREAD

**Issue by marcospgp** [FirstGearGames/FishNet#486]

**Comment by FirstGearGames** [comment]
There are a lot of guides, written and videos under more learning resources.
https://fish-networking.gitbook.io/docs/manual/tutorials

**Comment by epitaque** [comment]
> There are a lot of guides, written and videos under more learning resources. https://fish-networking.gitbook.io/docs/manual/tutorials
![image](https://github.com/user-attachments/assets/3f8a651f-64c7-4e21-bb0a-19dbc27d08d0)

I would appreciate a guide for getting started. If you put yourselves in the shoes of someone who has never used FishNet, there is no guide on how to set up a basic scene with one host and one client and send one message, for example.
