### ISSUE TITLE
Regression of Issue 437: duplicate scene names (but different paths) collide causing incorrect scene loading

### ISSUE THREAD

**Issue by AlmostInteractive** [FirstGearGames/FishNet#490]
**General**
Unity version: 2020.3
Fish-Networking version: 3.11.1
Discord link: https://discord.com/channels/424284635074134018/1034477094731784302/1160265992992194601

**Description**
Duplicate scene names (but different paths) collide.  eg:  `Scenes/level_one/myLevel.unity` and `Scenes/level_two/myLevel.unity` will collide (as both are reduced to `'myLevel'` and passed to `SceneManager.GetScene` on `SceneLookupData.cs` ln 350).

**Replication**
1. Create two scenes with the same name but different paths.
2. Load the first scene.  If it loaded the correct scene, load the second scene.  One will not load and instead load the other scene.

**Expected behavior**
`Scenes/level_one/scene` and `Scenes/level_two/scene` should be loaded correctly.

**Comment by AlmostInteractive** [comment]
Changing `SceneLookupData.cs` line 350 to `result = SceneManager.GetScene(Name);` fixes this issue since it uses the path as part of the name.

**Comment by AlmostInteractive** [comment]
Removing `SceneLookupData.cs` ln 61 fixes this issue.  eg:

```
        public string NameOnly
        {
            get {
                if (string.IsNullOrEmpty(Name))
                    return string.Empty;
                return RemoveUnityExtension(Name);
            }
        }
```

I don't know if there's a reason you want just the non-unique filenames without path prefixes, but a quick glance at the code seems like no.  Could be an easy fix.

**Comment by FirstGearGames** [comment]
Not sure if this is a regression or an incomplete fix. I do see at one point this was worked on but it's possible maybe all of the scenarios were not found.

I did update the code to use Name in most cases except when trying to GetScene via string, since Unity does not return path in scene lookups.

**Comment by AlmostInteractive** [comment]
My version of `NameOnly` isn't exactly "name only" but it does remove the unity extension still.  :)  I patched my local version with the above and it's working as expected.  Unity is quite happy to load `Scenes/level_one/scene.unity` via the string "Scenes/level_one/scene"
