### ISSUE TITLE
PredictionV2 is not deinitialized when NetworkObject  is destroyed

### ISSUE THREAD

**Issue by ooonush** [FirstGearGames/FishNet#494]
**General**
Unity version: 2022.3.4
Fish-Networking version: 3.11.2
Discord link: https://discord.com/channels/424284635074134018/1104850498290462821/1159488003467661312

**Description**
In my game, a similar bug happens when destroying an NetworkObject with PredictionV2. It can also happen when loading another scene.

**Replication**
There is a video in discord where I show how to replicate this bug.

**Comment by FirstGearGames** [comment]
Thanks. Labeled issue.
