### ISSUE TITLE
BandwidthDisplay.cs - one method is mixed up when we are unsubscribing

### ISSUE THREAD

**Issue by funnymanwin** [FirstGearGames/FishNet#497]
**General**
Unity version: 2021.3.31
Fish-Networking version: 3.11.2R 
Discord link: 

**Description**
BandwidthDisplay.cs script.
Methods are mixed up. Just need to replace one method to another. Nothing really critical, but it's incorrect.

**Replication**
Open the script and look.

**Expected behavior**
We are subscribed on event in Start() and want to unsubscribe in OnDestroy(). There are two methods which we want to subscribe and then unsubscribe. But second one is mixed up with fist one in method OnDestroy().

**Screenshots**
![image](https://github.com/FirstGearGames/FishNet/assets/76844755/4df69006-e767-460d-931d-23dd521acec2)
![image](https://github.com/FirstGearGames/FishNet/assets/76844755/698592ad-7a77-403d-a4d5-d6fc445e57a7)

**Comment by FirstGearGames** [comment]
Fixed in 3.11.3 ty!
