### ISSUE TITLE
CustomSerializer is Being Ignored For Derived Classes of the Class That Had the CustomSerializer Written.

### ISSUE THREAD

**Issue by Katerlad** [FirstGearGames/FishNet#506]
**General**
Unity version: 2022.3
Fish-Networking version: 3.11.2
Discord link: https://discord.com/channels/424284635074134018/1163197644651384902

**Description**
When syncing Derived Classes of a Class that has a custom serializer written for it, it instead tries to sync each field individually automatically instead of using the custom serializer.

In this case I am trying to sync all Scriptable objects by using an ID field on a class called NetworkScriptableObject, and looking up the ID field on the clients side. Using the ID load the Scriptable Object even for classes that derive from NetworkScriptableObject.

**Replication**
- Load test project
- Start Server on One Unity Instance
- Start Client on another instance
- Inspect PlayerPrefabs that were spawned, and look at TestSO_Sync Script.
- See that the client was able to sync the scriptable object down! - Thats good.
- press Space, to trigger a debug to access the Sprite info on each Scriptable Object.
- the Derived Network Scriptable Objects Sprite will be null - Shown in Debug Log.
- the normal Network Scripatble Object Sprite will be there. - Shown in the Debug Log. 
- the console will also only show 1 Debug log from the Custom Serializer script, saying it read the serializer. 
- there should be 2 Debug logs, one for the normal Network Scriptable object - that one exists.
- one from the Derived Network Scriptable Object - This one is missing

This leads me to believe that the Derived Network Scriptable Object does not use the Custom Serializer for the Network Scriptable Object, which is used to just send the ID only, and look up the ID on the clients end, by loading a new static Scriptable object.

**Expected behavior**
I expect that all derived classes of NetworkScriptableObject, use NetworkScriptableObjects Custom Serializer, so you do not have to create a custom serializer for each one. 

**Test Project**
Here is the test project to use the replication steps above.
[TestCustomSerializersForDerivedClasses.zip](https://github.com/FirstGearGames/FishNet/files/13033630/TestCustomSerializersForDerivedClasses.zip)

**Comment by FirstGearGames** [comment]
This has been confirmed by the way. It's going to be a low priority for now though.

**Comment by FirstGearGames** [comment]
There's a couple work-arounds which would be pretty easy to implement so I'm going to label this as won't fix for an unknown amount of time.

I'd like to brainstorm them with you to see what you feel works best so we can update this with a solution prior to closing.

**Comment by FirstGearGames** [comment]
This was accidentally resolved as a bi-product of another feature. Huzzah!
Fixed in release 4.1.3

**Comment by Katerlad** [comment]
Hey Im diving back into this project a little bit, and a solution to this would still be helpful. 

If you have 10 minutes sometime, maybe we could brainstorm a solution? 

My main goal is I want to Sync Scriptable Objects by ID be more native. Currently anywhere I use a scriptable object, I convert it to an ID and sync the ID then on the client convert ID back into Scriptable Object. 

Id like to just give Fishnet a "NetworkScriptableObject" and it does this process for me, but even if I have the abilty to role my own serializer so that this is taken care of automatically that would be great too, but this bug prevents that from happening.

Its related to this suggestion here => https://github.com/FirstGearGames/FishNet/discussions/508
