### ISSUE TITLE
DefaultPrefabObjects Changing Indexes Between Editor and Standalone Builds

### ISSUE THREAD

**Issue by NickMercer** [FirstGearGames/FishNet#52]
Unity Version: Unity 2021.2.15f1
My Package Release Version (found in FishNet/Version) 1.5.2p2 Pro
Editor or Standalone Build as Server/Host
Editor or Standalone Build as Client

Note: I am using ParrelSync. However the issue doesn't happen when I connect the 2 unity editor instances, the symlink catches the default prefabs change and they're in the same order for each editor. But when I make a standalone build, the standalone build's DefaultPrefabs array is in a different order than the editor one, and throws console errors/spawns the wrong prefabs. **This error only occurs when mixing editor builds with standalone builds**. If both client and server are standalone builds, the error does not occur. 

Steps To Reproduce:
Use the DefaultPrefabObjects menu item.

Build a standalone build using Build and Run
Run the standalone as client or server
Run the editor as client or server

Run game to a point where a prefab from the DefaultPrefabs list is supposed to spawn.

These console messages appear and the wrong prefab is spawned:
![Error Messages](https://user-images.githubusercontent.com/59749523/170641886-a55d93c3-a991-47bd-ae80-0557da458611.png)

Here is my prefab objects array in edit mode vs play mode:
Edit Mode:
![DefaultPrefabObjects in Edit Mode](https://user-images.githubusercontent.com/59749523/170641951-f6ebe4e3-3a45-4425-947d-36b7d007c278.png)

Play Mode:
![DefaultPrefabObjects in Play Mode](https://user-images.githubusercontent.com/59749523/170641977-fc574a7e-b582-401c-9e25-f6bf729e6575.png)

And my NetworkManager and DefaultPrefab settings:
![NetworkManager](https://user-images.githubusercontent.com/59749523/170642028-b1b80f45-2a91-43c6-a324-71255b797fd1.png)

![Prefab Settings](https://user-images.githubusercontent.com/59749523/170642119-c8864f25-1cde-4dc5-83cb-d2eeb2777739.png)

**Comment by FirstGearGames** [comment]
Hey, open DefaultPrefabObjects.cs
and comment out the body within method `        internal void Sort()`
I'll have an official fix soon.

**Comment by FirstGearGames** [comment]
Resolved in 1.5.3, will be released today.
