### ISSUE TITLE
Additive Scenes demo scene includes a ServerScenePrewarmer component where it should not

### ISSUE THREAD

**Issue by KeithSwanger** [FirstGearGames/FishNet#529]
**General**
Unity version: 2022.3.12
Fish-Networking version: 4.0.2 (free)
Discord link: n/a

**Description**
The GameObject `Trees(Networked)` in the scene `AdditiveScenes_0` has a `ServerScenePrewarmer` component. This seems to be an error and removing the component, as well as the `NetworkObject` component fixes the bug.
All trees within this scene appear and disappear at once instead of abiding by each individual tree's `NetworkObserver` conditions. Many errors appear in the console.

**Replication**
1. Add AdditiveScenes_(0-3) scenes to build settings
2. Open AdditiveScenes_Start demo scene
3. Start AdditveScenes_Start
4. Start server and join as a client
5. Notice that trees within AdditveScene_0 will all appear at once, and multiple errors will appear in the console

**Comment by FirstGearGames** [comment]
There were no errors for me but I did notice that the scenes were not listed in the Prewarmer (EG: elements were None unlike this screen capture) 
![image](https://github.com/FirstGearGames/FishNet/assets/27169134/a6ed3f9d-8669-4a10-9590-8040ddd9598e)

That was probably the cause of the issue. I've fixed the Prewarmer references for next release.
