### ISSUE TITLE
Server owned prediction v2 object with default input runs replicates with predicted state on server, and therefore runs twice per tick on the server.

### ISSUE THREAD

**Issue by Baerikus** [FirstGearGames/FishNet#535]
**General**
Unity version: tested on 2022.3.10f1
Fish-Networking version: everythink ok on 3.10.7R, any higher produces the bug, also v4

**Description**
If i upgrade from fn version 3.10.7R to any newer version, my server owned prediction v2 objects, that are passing default as input, are running 2 replicates per tick on the server. One for user created input and one for predicted. So passsing default somehow tricks the server into thinking he needs to run predicted input as well.

**Replication**
1. Create a server owned prediction v2 object
2. Pass default as input data on the server
3. Debug.Log input data tick, replicate state and IsServerInitialized
4. See error in debug logs

**Expected behavior**
![image](https://github.com/FirstGearGames/FishNet/assets/83476064/618277e4-bcd7-4aa3-adba-18bb0d07c836)

**Behavior**
![image](https://github.com/FirstGearGames/FishNet/assets/83476064/bcc8c5ed-0ae6-4ec3-b98e-923fe0a18018)

**Comment by FirstGearGames** [comment]
Resolved in 4,0.7 pre-release
