### ISSUE TITLE
Graphical object observer smoothing of prediction v2 network object is not taking parent scale in count

### ISSUE THREAD

**Issue by Baerikus** [FirstGearGames/FishNet#536]
**General**
Unity version: tested on 2022.3.10f1
Fish-Networking version: working fine on 3.10.7R, any newer produces the error, also v4

**Description**
It seems like the smoothing of the graphical object of an prediction v2 object is not taking the scale if the parent of the graphical in count and therefore scales the graphical wrongly for observers. Also the graphical is locally moving against the movement of its parent and therefore appearing like standing still on the screen.

**Replication**
1. Create prediction v2 object with the following hierarchy
-> Parent Object (scale 1,1,1; networkObject; cspV2 script)
         -> Child Object (scale 0.5, 3, 0.5; this is getting moved by the cspV2 script)
                   -> Child Object of the Child Object (scale 1,1,1; this is the graphical object assigned to the network object as graphical)
3. Run client and server on seperate builds / editors, running both in the same editor does not produce the error

**Expected behavior**
The graphical child should keep its scale and should get moved like on the server.
![image](https://github.com/FirstGearGames/FishNet/assets/83476064/def53f09-0c01-4916-8206-6ef133ed7e48)

**Behavior**
![image](https://github.com/FirstGearGames/FishNet/assets/83476064/02ce1107-2153-4a24-9a0e-635a48c634a9)

**Comment by FirstGearGames** [comment]
Reported as no longer broken as of current releases.
