### ISSUE TITLE
Prediction is not working

### ISSUE THREAD

**Issue by Sinhirt** [FirstGearGames/FishNet#540]
**General**
Unity version: 2022.3.11f1
Fish-Networking version: 4.02
Discord link: https://discord.com/channels/424284635074134018/1034477094731784302/1171777522447421510

**Description**
Prediction is not working (its seems it will not initialize) until i manualy change parameter in inspector.
 
**Replication**
1. Open and play CharacterControllerPrediction (or any other demo scene on prediction)....character is moving in tickrate steps, no smoothing at all.
2. Change any variable on PredictedObject component of spawned character and smoothing then turn ON.

**Expected behavior**
Smooth character

**Screenshots**

https://github.com/FirstGearGames/FishNet/assets/141421048/e743efe1-7a57-44b7-8cd0-ff717e7a0590

**Comment by FirstGearGames** [comment]
This has been identified as a bug and will be resolved soon. Thank you!

**Comment by FirstGearGames** [comment]
Resolved in 4.0.7
