### ISSUE TITLE
Add reconcile tick to OnPre/PostReconcile events.

### ISSUE THREAD

**Issue by FirstGearGames** [FirstGearGames/FishNet#55]
Requested by Roceh.
Add reconcile tick to OnPre/PostReconcile events.

**Comment by Roceh** [comment]
This isnt a big issue currently, the request was based on my misunderstand of what was happening at reconcile and the fact I was not doing a reconcile every tick. I reworked the setting of the vehicle state of the non player client vehicles before reconcile playback to just use the last state received from the server and have the server only send that on the same tick as reconcilation , it now behaves much like your predicted object class.

**Comment by FirstGearGames** [comment]
Added in 2.2.0.
There's several features included to aid in this and other potential custom scripts. 
- Added TimeManager.IsReplaying() which returns if any predictions are replaying.
- Added TimeManager.IsReplaying(Scene) which returns if a scene is replaying physics.
- Added NetworkBehaviour.GetLastReconcileTick to know which tick is being reconciled to.
- Added TimeManager.GetPreciseTick.
- Added TimeManager.GetTickPercent.
