### ISSUE TITLE
LocalTick breaks "only increment" promise when connecting the host client

### ISSUE THREAD

**Issue by TsFreddie** [FirstGearGames/FishNet#559]
**General**
Unity version: 2022.3.8f
Fish-Networking version: 4.0.3 & 3.11.10

**Description**
When host client connects, both LocalTick and Tick value (since they are the same value when server is running) decreases.
Although I believe "Tick" shouldn't decrease either in server, LocalTick did promise that in the XML doc.

**Replication**
1. Attach the following script to an empty scene with the example NetworkManager prefab
2. Run the scene
3. Click "Server"
4. Click "Client"

```
using FishNet;
using FishNet.Transporting;
using UnityEngine;

public class TickCheck : MonoBehaviour
{
    private long _lastTick = -1;
    private bool _initialized;

    private void Update()
    {
        if (!_initialized)
        {
            var serverManager = InstanceFinder.ServerManager;
            if (serverManager)
            {
                serverManager.OnServerConnectionState += OnServerConnectionState;
                _initialized = true;
            }
        }
    }
    
    private void OnServerConnectionState(ServerConnectionStateArgs args)
    {
        switch (args.ConnectionState)
        {
        case LocalConnectionState.Started:
            InstanceFinder.TimeManager.OnTick += OnTick;
            break;
        case LocalConnectionState.Stopping:
            InstanceFinder.TimeManager.OnTick -= OnTick;
            _lastTick = -1;
            break;
        }
    }

    private void OnTick()
    {
        if (_lastTick == -1)
        {
            _lastTick = InstanceFinder.TimeManager.LocalTick;
            return;
        }
        
        if (InstanceFinder.TimeManager.LocalTick - _lastTick != 1)
        {
            var expectedTick = _lastTick + 1;
            Debug.LogError($"Expecting tick: {expectedTick}, Unexpected tick: {InstanceFinder.TimeManager.LocalTick}");
        }
        
        _lastTick = InstanceFinder.TimeManager.LocalTick;
    }
}
```

**Expected behavior**
The LocalTick (or Tick in server) shouldn't decrease or stay the same during two different OnTick/OnPreTick/OnPostTick calls

**Comment by FirstGearGames** [comment]
Localtick should only change when a tick iterates or when the socket is
reset. Every OnTick should be incremental. This does sound a bit weird.

**Comment by FirstGearGames** [comment]
After reviewing your example more thoroughly(on desktop) I see that you are disconnecting a socket. The tick **is** supposed to reset when the socket closes. When clientHost the client uses the servers tick since it is the server, so tick will reset when clientOnly or when server socket changes.

In other words, seems to be working properly.

**Comment by TsFreddie** [comment]
Is connecting a client as host disconnecting the socket?

**Comment by FirstGearGames** [comment]
No, that should not reset Tick. If that's happening it is indeed a bug.

**Comment by TsFreddie** [comment]
The testing code listening LocalConnectionState is just to reset the test when Server stops. The reproduceable steps does not involve stopping the server.

Click Server -> Click Host -> Mismatched tick

**Comment by FirstGearGames** [comment]
I was able to reproduce. Thanks!

**Comment by FirstGearGames** [comment]
Here's the line that needs correction... Inside `ClientManager.cs` find
`networkManager.TimeManager.Tick = networkManager.TimeManager.LastPacketTick;`
and add a not IsServer conditional, like so...

```cs
            //Only do this if not also server.
            if (!networkManager.IsServer)
                networkManager.TimeManager.Tick = networkManager.TimeManager.LastPacketTick;
```
