### ISSUE TITLE
Client has a chance of instantly timeout due to a unsigned int underflow

### ISSUE THREAD

**Issue by TsFreddie** [FirstGearGames/FishNet#560]
**General**
Unity version: 2022.3.8f
Fish-Networking version: 3.11.10

**Description**
When I connect a client in my current project, there is a chance that client gets kicked instantly upon connecting.

No sure what the triggering cause is, but this probably shouldn't happen anyway. Maybe I was sending broadcast too quickly when client connects or something.
![image](https://github.com/FirstGearGames/FishNet/assets/3797859/c6c685c3-841f-4f60-b374-d3ce78ed5e3c)

The unsigned substract also exists in v4:
https://github.com/FirstGearGames/FishNet/blob/47e4af5e4e5fb1b3470adf522ef75362c86c4d08/Assets/FishNet/Runtime/Managing/Server/ServerManager.cs#L378C25-L378C25

**Replication**
Couldn't reproduce it in a fresh project

**Expected behavior**
Client shouldn't instantly timeout.

**Comment by FirstGearGames** [comment]
Need to know if this is happening as client only or client host.

**Comment by TsFreddie** [comment]
Seems to be clientHost only. I'll try that.

**Comment by TsFreddie** [comment]
Fix in #559 did fix it. Thanks

**Comment by FirstGearGames** [comment]
Awesome thanks. Resolved in 3.11.12R and next 4x
