### ISSUE TITLE
Error in Debug Manager

### ISSUE THREAD

**Issue by nineserenities** [FirstGearGames/FishNet#562]
Debug Manager causing errors on Clients when Server triggers Connection Scene Loading leading to error ArgumentOutOfRangeException: ArgumentOutOfRange_NeedNonNegNum
Parameter name: count

**General**
Unity version: 2022.3.12f1
Fish-Networking version: 3.11.10R
Discord link: https://discord.com/channels/424284635074134018/1034477094731784302/1178015782471479326

**Description**
I connected clients to my server. Then on the server side, I trigger a scene loading using LoadConnectionScenes().
Upon loading the next scene, the clients throw the error: ArgumentOutOfRangeException: ArgumentOutOfRange_NeedNonNegNum
The error was resolved by removing the Debug Manager or unchecking the "Write Scene Object Details" in the Debug Manager.

**Replication**
1. Create a function to change scene using Connection Scenes and Scene Load Data
2. In the OnStartServer function, subscribe to SceneManager.OnQueueEnd
3. In the OnQueueEnd function, add the SceneUnloadData() and UnloadConnectionScenes() to unload the previous scene when the scene OnQueueEnd is triggered
4. Ensure that the DebugManager is attached to Network Manager and check the "Write Scene Object Details"
5. Connect the clients to the server and proceed to Load the Connection Scenes
6. When the Connection scenes have been loaded, the OnQueueEnd will be triggered and we perform the Unloading of the previous scene
7. The "ArgumentOutOfRangeException" error should appear on the clients.
8. I suspect that the error happened during the scene loading, before the OnQueueEnd was triggered, because the scene loading was incomplete and several UIs were not enabled on Client Start.

**Expected behavior**
The scene should be loaded fully on the client side without errors.

**Screenshots**
There are no visible errors show in the game, but the following error appears in the Console:

ArgumentOutOfRangeException: ArgumentOutOfRange_NeedNonNegNum
Parameter name: count
System.ArraySegment`1[T]..ctor (System.Byte[] array, System.Int32 offset, System.Int32 count) (at <834b2ded5dad441e8c7a4287897d63c7>:0)
FishNet.Serializing.Reader.ReadArraySegment (System.Int32 count) (at Assets/FishNet/Runtime/Serializing/Reader.cs:370)
FishNet.Managing.Client.ClientObjects.CacheSpawn (FishNet.Serializing.PooledReader reader) (at Assets/FishNet/Runtime/Managing/Client/Object/ClientObjects.cs:449)
FishNet.Managing.Client.ClientManager.ParseReader (FishNet.Serializing.PooledReader reader, FishNet.Transporting.Channel channel, System.Boolean print) (at Assets/FishNet/Runtime/Managing/Client/ClientManager.cs:434)
FishNet.Managing.Client.ClientManager.ParseReceived (FishNet.Transporting.ClientReceivedDataArgs args) (at Assets/FishNet/Runtime/Managing/Client/ClientManager.cs:363)
FishNet.Managing.Client.ClientManager.Transport_OnClientReceivedData (FishNet.Transporting.ClientReceivedDataArgs args) (at Assets/FishNet/Runtime/Managing/Client/ClientManager.cs:327)
FishNet.Transporting.Tugboat.Tugboat.HandleClientReceivedDataArgs (FishNet.Transporting.ClientReceivedDataArgs receivedDataArgs) (at Assets/FishNet/Runtime/Transporting/Transports/Tugboat/Tugboat.cs:231)
FishNet.Transporting.Tugboat.Client.ClientSocket.IterateIncoming () (at Assets/FishNet/Runtime/Transporting/Transports/Tugboat/Core/ClientSocket.cs:288)
FishNet.Transporting.Tugboat.Tugboat.IterateIncoming (System.Boolean server) (at Assets/FishNet/Runtime/Transporting/Transports/Tugboat/Tugboat.cs:204)
FishNet.Managing.Transporting.TransportManager.IterateIncoming (System.Boolean server) (at Assets/FishNet/Runtime/Managing/Transporting/TransportManager.cs:632)
FishNet.Managing.Timing.TimeManager.TryIterateData (System.Boolean incoming) (at Assets/FishNet/Runtime/Managing/Timing/TimeManager.cs:1049)
FishNet.Managing.Timing.TimeManager.IncreaseTick () (at Assets/FishNet/Runtime/Managing/Timing/TimeManager.cs:708)
FishNet.Managing.Timing.TimeManager.<TickUpdate>g__MethodLogic|104_0 () (at Assets/FishNet/Runtime/Managing/Timing/TimeManager.cs:383)
FishNet.Managing.Timing.TimeManager.TickUpdate () (at Assets/FishNet/Runtime/Managing/Timing/TimeManager.cs:373)
FishNet.Transporting.NetworkReaderLoop.Update () (at Assets/FishNet/Runtime/Transporting/NetworkReaderLoop.cs:28)

**Comment by celojevic** [comment]
Im having the same issue on 3.11.7. However, the error does not occur if i build the server as a development build

**Comment by FirstGearGames** [comment]
Yes, it will be active in builds if development build. Sounds like the debugging feature is a little busted so I'll get that fixed.

**Comment by FirstGearGames** [comment]
I was not able to replicate; I'll most likely need an example project, or more instruction if you know what is different with my test project.


* I have two scenes, A which is the first scene, and B the second.
* Both scenes have a networkObject in it.
* Player prefab is set, and NetworkManager has ObserverManager with the SceneCondition.
* Add DebugManager and tick Write Scene Object Details.

My script below is placed on the NetworkManager.
```cs
using FishNet;
using FishNet.Connection;
using FishNet.Managing.Scened;
using System.Linq;
using UnityEngine;

public class SceneChange : MonoBehaviour
{

    private void Start()
    {
        InstanceFinder.SceneManager.OnQueueEnd += SceneManager_OnQueueEnd;
    }
    
    private void SceneManager_OnQueueEnd()
    {
        if (InstanceFinder.ServerManager.Clients.Count == 0)
            return;
        
        NetworkConnection firstC = InstanceFinder.ServerManager.Clients.First().Value;
        SceneUnloadData sld = new SceneUnloadData("A");
        InstanceFinder.SceneManager.UnloadConnectionScenes(firstC, sld);
    }

    private void Update()
    {
        if (InstanceFinder.IsServerStarted && Input.GetKeyDown(KeyCode.Space))
        {
            if (InstanceFinder.ServerManager.Clients.Count == 0)
                return;

            NetworkConnection firstC = InstanceFinder.ServerManager.Clients.First().Value;
            SceneLoadData sld = new SceneLoadData("B");
            InstanceFinder.SceneManager.LoadConnectionScenes(firstC, sld);
        }
    }
}
```
When I connect a client I press space to execute the scene load.

**Comment by FirstGearGames** [comment]
Closed due to inactivity.
