### ISSUE TITLE
Cant reconnect after disconnected

### ISSUE THREAD

**Issue by 15so42** [FirstGearGames/FishNet#563]
fishnet version:3.5.8
unity version:2021.3.18f1c1
My client can connect to the host and run normally the first time. However, if the client disconnects and then tries to reconnect, it cannot connect and displays the following error:
![screenshot-20231127-155247](https://github.com/FirstGearGames/FishNet/assets/33503286/f41f6195-f3af-4e26-866f-e47db2c18271)

At this time, the host also reports an error:
![screenshot-20231127-152248](https://github.com/FirstGearGames/FishNet/assets/33503286/4e86b0eb-6832-466a-bf37-ad75495f84f5)

It seems like the host has not properly cleared the disconnected client's state. How can this be resolved? Is it a bug?

**Comment by 15so42** [comment]
15:21:23 disconnectd
15:21:49 reconnect

**Comment by 15so42** [comment]
![screenshot-20231127-172719](https://github.com/FirstGearGames/FishNet/assets/33503286/0566861d-6709-4bea-9647-0733bea1e061)

**Comment by FirstGearGames** [comment]
Your version of FishNet is not supported for debugging. To receive debugging please update to the latest R release, which at the time of this post is 3.11.12R.

If you are on a Pro release and do not have access to Pro anymore I'd be happy to give you the latest release; just DM me on Discord FirstGearGames if that is the case. 

Closing this out for now, will re-open if issue persist after updating.

**Comment by 15so42** [comment]
![screenshot-20231128-120034](https://github.com/FirstGearGames/FishNet/assets/33503286/550e4126-acce-4d2f-a3cd-e30c2008468f)
I upgraded to version 3.11.12r, but the problem still persists. The way to reproduce the issue is the same as before.How to know the reason?

**Comment by 15so42** [comment]
Alright, I created a new empty scene for testing, and now the client can reconnect to the host. It seems that something in my project is causing the disconnection during the reconnection process, but the log content is too vague for me to identify where the problem lies. Do you have any suggestions on how to proceed?Thanks a lot

**Comment by 15so42** [comment]
I cant solve this problem
