### ISSUE TITLE
Spawning an Object With Parent

### ISSUE THREAD

**Issue by Awesomegameplayer** [FirstGearGames/FishNet#565]
**General**
Unity version: 2021.3.16f1
Fish-Networking version: 3.11.12R
Discord link: https://discord.com/channels/424284635074134018/1034477094731784302/1179579615866519724

**Description**
When spawning an object that has been instantiated with a parent the object will spawn deactivated and without a parent, along with the console giving the error: 

``(Object) cannot be moved to scene name (Scene Name), handle -12580 because (Object) is not root and only root objects may be moved.``

**Replication**
1. Instantiate an object and assign it a parent that has a Network Object component.
2. Spawn the object.
4. See error.

**Expected behavior**
The object will spawn disabled and without a parent.

<details>
<summary>
Error Message
</summary>

> <rawtext>
> UnityEngine.Debug:LogError (object)
> FishNet.Managing.Logging.LevelLoggingConfiguration:LogError (string) (at Assets/FishNet/Runtime/Managing/Logging/LevelLoggingConfiguration.cs:128)
> FishNet.Managing.NetworkManager:LogError (string) (at Assets/FishNet/Runtime/Managing/NetworkManager.Logging.cs:116)
> FishNet.Managing.Server.ServerManager:Spawn (FishNet.Object.NetworkObject,FishNet.Connection.NetworkConnection,UnityEngine.SceneManagement.Scene) (at Assets/FishNet/Runtime/Managing/Server/ServerManager.QOL.cs:114)
> FishNet.Object.NetworkObject:Spawn (UnityEngine.GameObject,FishNet.Connection.NetworkConnection,UnityEngine.SceneManagement.Scene) (at Assets/FishNet/Runtime/Object/NetworkObject.QOL.cs:233)
> Unity.VisualScripting.InstanceActionInvoker`4<FishNet.Object.NetworkObject, UnityEngine.GameObject, FishNet.Connection.NetworkConnection, UnityEngine.SceneManagement.Scene>:InvokeUnsafe (object,object,object,object) (at Library/PackageCache/com.unity.visualscripting@1.7.8/Runtime/VisualScripting.Core/Reflection/Optimization/InstanceActionInvoker_3.cs:53)
> Unity.VisualScripting.InstanceActionInvoker`4<FishNet.Object.NetworkObject, UnityEngine.GameObject, FishNet.Connection.NetworkConnection, UnityEngine.SceneManagement.Scene>:Invoke (object,object,object,object) (at Library/PackageCache/com.unity.visualscripting@1.7.8/Runtime/VisualScripting.Core/Reflection/Optimization/InstanceActionInvoker_3.cs:34)
> Unity.VisualScripting.Member:Invoke (object,object,object,object) (at Library/PackageCache/com.unity.visualscripting@1.7.8/Runtime/VisualScripting.Core/Reflection/Member.cs:993)
> Unity.VisualScripting.InvokeMember:Invoke (object,Unity.VisualScripting.Flow) (at Library/PackageCache/com.unity.visualscripting@1.7.8/Runtime/VisualScripting.Flow/Framework/Codebase/InvokeMember.cs:179)
> Unity.VisualScripting.InvokeMember:Enter (Unity.VisualScripting.Flow) (at Library/PackageCache/com.unity.visualscripting@1.7.8/Runtime/VisualScripting.Flow/Framework/Codebase/InvokeMember.cs:260)
> Unity.VisualScripting.Flow:InvokeDelegate (Unity.VisualScripting.ControlInput) (at Library/PackageCache/com.unity.visualscripting@1.7.8/Runtime/VisualScripting.Flow/Flow.cs:451)
> Unity.VisualScripting.Flow/<InvokeCoroutine>d__55:MoveNext () (at Library/PackageCache/com.unity.visualscripting@1.7.8/Runtime/VisualScripting.Flow/Flow.cs:394)
> Unity.VisualScripting.Flow/<InvokeCoroutine>d__55:MoveNext () (at Library/PackageCache/com.unity.visualscripting@1.7.8/Runtime/VisualScripting.Flow/Flow.cs:398)
> Unity.VisualScripting.Flow/<InvokeCoroutine>d__55:MoveNext () (at Library/PackageCache/com.unity.visualscripting@1.7.8/Runtime/VisualScripting.Flow/Flow.cs:398)
> Unity.VisualScripting.Flow/<InvokeCoroutine>d__55:MoveNext () (at Library/PackageCache/com.unity.visualscripting@1.7.8/Runtime/VisualScripting.Flow/Flow.cs:398)
> Unity.VisualScripting.Flow/<InvokeCoroutine>d__55:MoveNext () (at Library/PackageCache/com.unity.visualscripting@1.7.8/Runtime/VisualScripting.Flow/Flow.cs:398)
> Unity.VisualScripting.Flow/<InvokeCoroutine>d__55:MoveNext () (at Library/PackageCache/com.unity.visualscripting@1.7.8/Runtime/VisualScripting.Flow/Flow.cs:398)
> Unity.VisualScripting.Flow/<InvokeCoroutine>d__55:MoveNext () (at Library/PackageCache/com.unity.visualscripting@1.7.8/Runtime/VisualScripting.Flow/Flow.cs:398)
> Unity.VisualScripting.Flow/<Coroutine>d__53:MoveNext () (at Library/PackageCache/com.unity.visualscripting@1.7.8/Runtime/VisualScripting.Flow/Flow.cs:302)
> UnityEngine.MonoBehaviour:StartCoroutine (System.Collections.IEnumerator)
> Unity.VisualScripting.Flow:StartCoroutine (Unity.VisualScripting.ControlOutput,System.Collections.Generic.ICollection`1<Unity.VisualScripting.Flow>) (at Library/PackageCache/com.unity.visualscripting@1.7.8/Runtime/VisualScripting.Flow/Flow.cs:263)
> Unity.VisualScripting.EventUnit`1<Unity.VisualScripting.CustomEventArgs>:Run (Unity.VisualScripting.Flow) (at Library/PackageCache/com.unity.visualscripting@1.7.8/Runtime/VisualScripting.Flow/Framework/Events/EventUnit.cs:178)
> Unity.VisualScripting.EventUnit`1<Unity.VisualScripting.CustomEventArgs>:Trigger (Unity.VisualScripting.GraphReference,Unity.VisualScripting.CustomEventArgs) (at Library/PackageCache/com.unity.visualscripting@1.7.8/Runtime/VisualScripting.Flow/Framework/Events/EventUnit.cs:154)
> Unity.VisualScripting.EventUnit`1/<>c__DisplayClass14_0<Unity.VisualScripting.CustomEventArgs>:<StartListening>b__0 (Unity.VisualScripting.CustomEventArgs) (at Library/PackageCache/com.unity.visualscripting@1.7.8/Runtime/VisualScripting.Flow/Framework/Events/EventUnit.cs:67)
> Unity.VisualScripting.EventBus:Trigger<Unity.VisualScripting.CustomEventArgs> (Unity.VisualScripting.EventHook,Unity.VisualScripting.CustomEventArgs) (at Library/PackageCache/com.unity.visualscripting@1.7.8/Runtime/VisualScripting.Core/Events/EventBus.cs:71)
> Unity.VisualScripting.EventBus:Trigger<Unity.VisualScripting.CustomEventArgs> (string,UnityEngine.GameObject,Unity.VisualScripting.CustomEventArgs) (at Library/PackageCache/com.unity.visualscripting@1.7.8/Runtime/VisualScripting.Core/Events/EventBus.cs:80)
> Unity.VisualScripting.CustomEvent:Trigger (UnityEngine.GameObject,string,object[]) (at Library/PackageCache/com.unity.visualscripting@1.7.8/Runtime/VisualScripting.Flow/Framework/Events/CustomEvent.cs:67)
> FishCmdRpc:RpcLogic___CmdMaster_2424894439 (string,string,UnityEngine.GameObject,UnityEngine.GameObject[],UnityEngine.Vector3[],UnityEngine.Transform[],string[],int[],single[],UnityEngine.Color[]) (at Assets/Scripts/Networking/FishCmdRpc.cs:20)
> FishCmdRpc:RpcReader___Server_CmdMaster_2424894439 (FishNet.Serializing.PooledReader,FishNet.Transporting.Channel,FishNet.Connection.NetworkConnection)
> FishNet.Managing.Server.ServerManager:ParseReceived (FishNet.Transporting.ServerReceivedDataArgs) (at Assets/FishNet/Runtime/Managing/Server/ServerManager.cs:735)
> FishNet.Managing.Server.ServerManager:Transport_OnServerReceivedData (FishNet.Transporting.ServerReceivedDataArgs) (at Assets/FishNet/Runtime/Managing/Server/ServerManager.cs:603)
> FishNet.Transporting.Tugboat.Tugboat:HandleServerReceivedDataArgs (FishNet.Transporting.ServerReceivedDataArgs) (at Assets/FishNet/Runtime/Transporting/Transports/Tugboat/Tugboat.cs:243)
> FishNet.Transporting.Tugboat.Server.ServerSocket:IterateIncoming () (at Assets/FishNet/Runtime/Transporting/Transports/Tugboat/Core/ServerSocket.cs:506)
> FishNet.Transporting.Tugboat.Tugboat:IterateIncoming (bool) (at Assets/FishNet/Runtime/Transporting/Transports/Tugboat/Tugboat.cs:202)
> FishNet.Managing.Transporting.TransportManager:IterateIncoming (bool) (at Assets/FishNet/Runtime/Managing/Transporting/TransportManager.cs:632)
> FishNet.Managing.Timing.TimeManager:TryIterateData (bool) (at Assets/FishNet/Runtime/Managing/Timing/TimeManager.cs:1048)
> FishNet.Managing.Timing.TimeManager:IncreaseTick () (at Assets/FishNet/Runtime/Managing/Timing/TimeManager.cs:708)
> FishNet.Managing.Timing.TimeManager:<TickUpdate>g__MethodLogic|104_0 () (at Assets/FishNet/Runtime/Managing/Timing/TimeManager.cs:383)
> FishNet.Managing.Timing.TimeManager:TickUpdate () (at Assets/FishNet/Runtime/Managing/Timing/TimeManager.cs:373)
> FishNet.Transporting.NetworkReaderLoop:Update () (at Assets/FishNet/Runtime/Transporting/NetworkReaderLoop.cs:28)
> </rawtext>
</details>

**Screenshots**
Since I use Visual Scripting things look a bit different but this should still be understandable.
![image](https://github.com/FirstGearGames/FishNet/assets/152555755/3018e487-05d1-4fcf-82fc-4abb1b910cc8)

**Comment by FirstGearGames** [comment]
I'm not sure if this is a bug without seeing how you are calling spawn, but I'm thinking it is not. If you are passing a scene into the spawn message, which I assume you are, then this is working properly.

This happens because Unity does not let you move child objects, and you are setting it a child prior to spawning. You can child it after spawning but you might run into issues with visibility; depends on your goal really.

If I am mistaken on your work flow please re-open this; otherwise follow up in help chat. Thank you.
