### ISSUE TITLE
Using BufferLast Causes Client Unable to Reconnect After Disconnection, Error: Invalid Param

### ISSUE THREAD

**Issue by 15so42** [FirstGearGames/FishNet#568]
Unity version:2021.3.18f1c1
Fishnet version:3.11.12r
also using FishyStemworks.

My client can connect to the host and run normally the first time. However, if the client disconnects and then tries to reconnect, it cannot connect and displays the following error:

![screenshot-20231127-155247](https://github.com/FirstGearGames/FishNet/assets/33503286/f15be4cc-7028-43b0-a928-3194103f8e84)

At this time, the host also reports an error:

![screenshot-20231127-152248](https://github.com/FirstGearGames/FishNet/assets/33503286/e65ca7c5-ee4e-4f00-b28c-68aa02560cc1)

![screenshot-20231127-172719](https://github.com/FirstGearGames/FishNet/assets/33503286/fc00e097-af4f-41f7-9ce6-3d337d7d47d2)

Finally, I fixed it by removing the BufferLast attribute.

![image](https://github.com/FirstGearGames/FishNet/assets/33503286/60e98f2c-81b1-439f-b973-dda011e93aad)

**Comment by FirstGearGames** [comment]
Hello, can you provide a Discord link where you troubleshot this issue?
If you are not able to use Discord let me know and we'll see what other options there are.

**Comment by FirstGearGames** [comment]
This will be closed in another week if we are not able to get additional information.
