### ISSUE TITLE
SyncVars do not update if object is spawned by client using PredictedSpawn

### ISSUE THREAD

**Issue by lingonpaj** [FirstGearGames/FishNet#575]
# Important
If General, Description, and Replication are not completed the issue will be closed immediately.

**General**
Unity version: 2022.2.13f
Fish-Networking version:  4.0.6
Discord link: https://discord.com/channels/424284635074134018/1034477094731784302/1186367282440568983
** Above, post a link from our Discord where you troubleshot the issue (on Discord click the three dots next to the message, then Copy Message Link). Issue may be closed out if this is not included.

**Description**
If a remote client spawns an object using PredictedSpawn the syncvars don't trigger/update the OnChange method on remote clients, only on the server. RPCs still work fine, and objects spawned by the server has their OnChange functions triggered on clients.

**Replication**
1. Create an object with a NetworkBehaviour, add a SyncVar to it and an OnChange method.
2. Make a prefab with this script and add the Predicted Spawn script, check all checkboxes.
3. Spawn this prefab from a client using either a pool or instantiating it then calling NetworkManager.ServerManager.Spawn() on it. Make sure only the client calls the instantiate method.
4. Notice that the OnChange method is not triggered on remote clients (including the one that spawned it), no matter what the server changes the value to, it's only called on the server.

**Expected behavior**
The OnChange method is triggered, no matter which client spawned the object using Predicted Spawn.

**Screenshots**

**Comment by FirstGearGames** [comment]
PredictedSpawn SyncVars are going away in v4 so I'm going to close this out with that said. A better replacement is coming.

**Comment by AavaGames** [comment]
This should be noted in the documentation somewhere. I spent a few hours troubleshooting this issue too.
