### ISSUE TITLE
Multiple NetworkManagers with DestroyOldest

### ISSUE THREAD

**Issue by Ta1kur1** [FirstGearGames/FishNet#577]
# Important
If General, Description, and Replication are not completed the issue will be closed immediately.

**General**
Unity version: 2022.3.16f1
Fish-Networking version: 3.11.13
Discord link: https://discord.com/channels/424284635074134018/1034477094731784302/1182711345012027502

**Description**
There appears multiple NetworkManagers when disconnecting from a game. I use multipass with FishyUnityTransport and Tugboat. The multiple NM issue only happens when disconnecting from a tugboat game.

**Replication**
1. Use Multipass with  tugboat and FishyUnityTransport
2. Load with FUT to online scene and disconnect and load back to menu to see nothing bad happens
3. Load with tugboat to online scene and disconnect and load back to menu to see error messages and two NetworkManagers

**Expected behavior**

**Screenshots**

**Comment by FirstGearGames** [comment]
Can this be replicated perhaps with Tugboat/Yak instead of Tugboat and FUT?

**Comment by FirstGearGames** [comment]
This will be closed in another week if we are not able to get additional information.
