### ISSUE TITLE
GameKit implementation of "AddUnique" does not match documented behavior

### ISSUE THREAD

**Issue by petergiuntoli** [FirstGearGames/FishNet#579]
I wasn't sure if this was brought in from somewhere else or is home grown but AddUnique is documented as returning true if adding an element but it actually returns true if the element already exists.

https://github.com/FirstGearGames/FishNet/blob/d780e805d454b4c79da65059340d730fb1aedb4b/Assets/FishNet/Plugins/GameKit/Dependencies/Utilities/Arrays.cs#L18-L29

I notice that this is causing unintended behavior inside "CanvasTracker" https://github.com/FirstGearGames/FishNet/blob/d780e805d454b4c79da65059340d730fb1aedb4b/Assets/FishNet/Plugins/GameKit/Dependencies/Utilities/Types/Canvases/CanvasTracker.cs#L93-L105

Additionally I think the function signature could make the "object" a type T instead of boxing internally but that's a separate issue.

`public static bool AddUnique<T>(this List<T> list, T value)`

I ended up noticing this because my game has it's own implementation of AddUnique but vscode chooses to autocomplete the "gamekit" version first which has the opposite return value behavior.

**Comment by FirstGearGames** [comment]
You are right on both. Fixed and improved in v3.11.14 and 4.0.7.
