### ISSUE TITLE
NetworkTransform throwing error when an object despawns

### ISSUE THREAD

**Issue by maxkratt** [FirstGearGames/FishNet#584]
_This error has been reported and kindly reproduced by Discord user, rekurer. (Thank you!)_

**General**
Unity version: Unity 2022.3.7f1
Fish-Networking version: 4.0.6
Discord link: https://discord.com/channels/424284635074134018/1034477094731784302/1190594598725242952

**Description**
After updating from 3.10.8 to 4.0.6 there is an error in some projectile code. Projectiles are updated server side and have position synced by NetworkTransform. If a bullet hits an object then the bullet is despawned. This worked fine in the old version, but now the following error is spammed every tick:
```
NullReferenceException: Object reference not set to an instance of an object
FishNet.Component.Transforming.NetworkTransform.TimeManager_OnPostTick () (at Assets/FishNet/Runtime/Generated/Component/NetworkTransform/NetworkTransform.cs:909)
FishNet.Managing.Timing.TimeManager.IncreaseTick () (at Assets/FishNet/Runtime/Managing/Timing/TimeManager.cs:724)
FishNet.Managing.Timing.TimeManager.<TickUpdate>g__MethodLogic|104_0 () (at Assets/FishNet/Runtime/Managing/Timing/TimeManager.cs:383)
FishNet.Managing.Timing.TimeManager.TickUpdate () (at Assets/FishNet/Runtime/Managing/Timing/TimeManager.cs:373)
FishNet.Transporting.NetworkReaderLoop.Update () (at Assets/FishNet/Runtime/Transporting/NetworkReaderLoop.cs:28)
```

**Replicable Example**
[networktransformbug.zip](https://github.com/FirstGearGames/FishNet/files/13799144/networktransformbug.zip)

**Replication**
0 - Import the reproduction sample
1 - Load and Play SampleScene
2 - Click to fire a bullet. It should disappear and print a log confirming Cube (1) was hit.
3 - Click multiple times quickly until the error occurs.

**Comment by FirstGearGames** [comment]
Okay thank you for report.

**Comment by FirstGearGames** [comment]
I wasn't able to replicate this. Can you please update description to let me know how many editors I need open, which should be server only, host, etc.

**Comment by maxkratt** [comment]
Okay so I gave it another test in a new project with FishNet 4.0.7 and the package you posted above. With a single editor acting as server and client I received the error within a couple seconds of pressing space rapidly. It is even easier to change the Gun.cs script to use `GetKey` instead of `GetKeyDown` as the button can simply be held then.

**Comment by FirstGearGames** [comment]
I'll give this a shot, thanks max.

**Comment by FirstGearGames** [comment]
Still had a really hard time replicating until I set the speed to 10. Will have it resolved soon enough.

**Comment by FirstGearGames** [comment]
Fixed in 409.
