### ISSUE TITLE
Excessive performance hit on remote clients when running NetworkReaderLoop.Update()

### ISSUE THREAD

**Issue by lingonpaj** [FirstGearGames/FishNet#586]
# Important
If General, Description, and Replication are not completed the issue will be closed immediately.

**General**
Unity version: 2022.2.13f
Fish-Networking version:  4.0.7 pre release
Discord link:https://discord.com/channels/424284635074134018/1167060429051269200/1192829654000746536
** Above, post a link from our Discord where you troubleshot the issue (on Discord click the three dots next to the message, then Copy Message Link). Issue may be closed out if this is not included.

**Description**
After upgrading to 407 from 406 starting a second client now has significantly less performance, seemingly due to the NetworkReaderLoop.Update()

**Replication**
1. Implement CSP
2. Make a build, start one to act as a server, then start another.
3. Notice the performance decrease.

**Expected behavior**
No performance decrease.

[fishnet-repro.zip](https://github.com/FirstGearGames/FishNet/files/13847881/fishnet-repro.zip)

**Screenshots**
![image](https://github.com/FirstGearGames/FishNet/assets/23025179/c784febe-05c3-47fa-93e5-902ec06daf04)

**Comment by FirstGearGames** [comment]
I have not run the test project yet but I did some investigating and I found a couple impact points already. I'll try to have a new pre-release out with my findings fixed in the next day or two and hopefully they resolve your problem as well. If not I'll grab the project files and take a look.

**Comment by FirstGearGames** [comment]
Pinned in prerelease channel as _02

**Comment by lingonpaj** [comment]
Much improved! The only difference I notice currently from 4.0.6 is that it takes noticeably longer for the client to connect, with my computer almost freezing for a short while just as it connects, I have some pooled objects which might be the culprit, but this behaviour didn't happen on 4.0.6. Once connected it works splendidly though.

**Comment by FirstGearGames** [comment]
Fixed in 4.0.7 Pre-release 02
