### ISSUE TITLE
Connection.Disconnect(immediately: false); doesn't work.

### ISSUE THREAD

**Issue by maxgmer** [FirstGearGames/FishNet#588]
# Important
`Connection.Disconnect(immediately: false);` doesn't work as intended.
Broadcasts sent before the disconnect never reach client as if we did an immediate disconnect (reproducible only with a simulated latency, so FishNet Demos may trick you into thinking it's working).

**General**
Unity version: 2022.3.15f1
Fish-Networking version: 3.11.12
Discord link:
https://discord.com/channels/424284635074134018/1034477094731784302/1193563840793817178

**Description**
If we send broadcasts to a client connection and then do `connection.Disconnect(false);`, the broadcast will never reach client, as if it was `connection.Disconnect(true);`.

**Replication**
1. Open "FishNet/Demos/Authenticator/Authenticator.unity" scene.
2. There you will see a "NetworkManager" object. Add a "TransportManager" component to it.
3. Add some latency on the "TransportManager" component:
    - Expand "Latency Simulator"
    - Tick "Enabled".
    - Drag "Latency" to 300 ms (this bug is only reproducible with a non-zero latency, 300 ms is enough to reproduce the bug).
4. Open "FishNet/Demos/Authenticator/Scripts/PasswordAuthenticator.cs" file, on line 64 do: `Password = "wrongPass"`.
This will trigger sending a "ResponseBroadcast" from server + `connection.Disconnect(false);` due to incorrect password.
5. See the error! ("ResponseBroadcast" will not reach the client, "Authenitcation failed." will not appear in console).

**Expected behavior**
I expect broadcasts reaching clients when we do a non-immediate disconnect (`connection.Disconnect(false)`).
In the steps of reproduction, I expect seeing "Authenitcation failed." in the logs of the client, who entered a wrong password.

**Comment by FirstGearGames** [comment]
The latency simulator has limitations in this sense as it only holds
outgoing packets, not disconnects. Try using clumsy to see what happens.

**Comment by maxgmer** [comment]
@FirstGearGames I'm on MacOS, so couldn't use clumsy.
Tried multiple software options, but they don't throttle LAN/localhost connections for some reason :(
So will need some time to simulate throttling.

> One interesting observation though, I put a breakpoint before both broadcast and disconnect on the server, so that it waits 1 second before sending the broadcast/disconnection and the problem was reproduced.
> 
> ```
> Debug.Log(); <- breakpoint here
> Broadcast();
> Disconnect(false);
> ```
> 
> P.S. take the observation with a grain of salt, have only tested it in my environment, haven't tested in any of your demos.

**Comment by maxgmer** [comment]
By the way, a side question to understand `disconnect(immediately: false);`.

Why is latency simulation not enough here?
As I understand, the non-immediate disconnect fires only when the Broadcast reaches the client (<- am I right?).
And latency simulator does a good job at making sure that the broadcast reaches the client later.

**Comment by FirstGearGames** [comment]
In real environment the packet will almost always go through before the
disconnect, but with all things network it's not promised.

Eg: if packet is sent on reliable but drops and needs a resend it probably
won't get there in time.

If you absolutely need the client to get the packet you should let the
client disconnect when they receive it and have a fallback on the server to
boot after a short duration.

**Comment by maxgmer** [comment]
@FirstGearGames So I was able to add latency to localhost with 0 packet loss, yes, on your demo it's working perfectly.
Thanks for the tip! Yes, I need the packets to get to clients before disconnect, so I will probably need handle disconnection in a different way.
