### ISSUE TITLE
Graphical object offset when object is spawned while prediction v2 is enabled and jitter fix is used

### ISSUE THREAD

**Issue by lingonpaj** [FirstGearGames/FishNet#595]
**General**
Unity version: 2022.2.13f
Fish-Networking version: 4.0.7
Discord link: https://forum.unity.com/threads/fishnet-and-rigidbody-jitter.1536994/ (no discord troubleshooting for this one)

**Description**

Comment out _graphicalObject.SetLocalProperties(_gfxInitializedLocalValues); in BasicTickSmoother in order to fix jitter bug.

At game start and when an object is instantiated while using prediction v2 and rigidbodies, the graphical object is offset if the object if not spawned at origo and is applying forces in a script called from the move function. If gravity is disabled on the object or frozen in place until fully spawned this seems to not happen (gravity can then be manually toggled on). If no forces are applied while being spawned it also seems to function normally. Behaviour seemed to be exacerbated if the scene takes longer to load, after removing some fake lag the object is seen very slowly interpolating towards the correct position before stopping. If you wait for a while (5-7 seconds) the object eventually teleports to its proper position. I could only get this to happen in the repro project, in my own project where more stuff is going on the teleport never happens, it stays offset unless manually restored.

**Replication**
1. Create networked predicted object with a rigidbody, attach script that moves the object in the move function. Place the object a decent distance away from 0 in the Y axis, start the game. Easiest is to just use the attached repro package.

**Expected behavior**
The graphics object is synced with its physical representation.

**Screenshots**
https://streamable.com/nqxxt8
[fishnet_offset_repro.zip](https://github.com/FirstGearGames/FishNet/files/13988634/fishnet_offset_repro.zip)

**Comment by FirstGearGames** [comment]
Resolved, and will be in 409.

Open BasicTickSmoother and do the following...

Add
```cs
        /// <summary>
        /// True if a pretick occurred since last postTick.
        /// </summary>
        private bool _preticked;
```

Replace these two methods.
```cs

        /// <summary>
        /// Called when the TimeManager invokes OnPreTick.
        /// </summary>
        internal void OnPreTick()
        {
            if (!CanSmooth())
                return;

            _preticked = true;
            _nobPreSimulateWorldValues = _networkObject.transform.GetWorldProperties();
            _gfxPreSimulateWorldValues = _graphicalObject.GetWorldProperties();
        }

        /// <summary>
        /// Called when TimeManager invokes OnPostTick.
        /// </summary>
        internal void OnPostTick()
        {
            if (!CanSmooth())
                return;

            //If preticked then previous transform values are known.
            if (_preticked)
            {
                SetMoveRates(_nobPreSimulateWorldValues, _networkObject.transform);
                _graphicalObject.SetWorldProperties(_gfxPreSimulateWorldValues);
            }
            //If did not pretick then the only thing we can do is snap to instantiated values.
            else
            {
                _graphicalObject.SetLocalProperties(_gfxInitializedLocalValues);
            }
        }
```

**Comment by lingonpaj** [comment]
There is one more issue regarding objects with a scale smaller than 1. The graphics object eventually falls behind.
In the repro just shoot with "C", pause immediately after and check the newly spawned projectile to see the issue (by stepping frame by frame).

[fishnet_offset_projectiles_repro.zip](https://github.com/FirstGearGames/FishNet/files/13996193/fishnet_offset_projectiles_repro.zip)

**Comment by FirstGearGames** [comment]
I still cannot get this to replicate using your `fishnet_offset_repro.zip` project. The graphics align with the object seemingly when it bounces and stops.

**Comment by lingonpaj** [comment]
I'll have to have a look later tonight, in case I exported the wrong scene.

**Comment by lingonpaj** [comment]
Wait, are you using fishnet_offset_repro.zip? That's the repro for the camera jitter which you have already fixed I think? fishnet_offset_projectiles_repro.zip is the one I linked in a comment above, that one has the scale issue I mentioned. This repro however does not replicate the issue where moving the object while inactive causes the graphics object to be offset (the code snippet you posted in the v2 thread on discord does resolve that issue though).

**Comment by FirstGearGames** [comment]
I resolved the problem differently anyway. Neither should be an issue in 4.1.0.
