### ISSUE TITLE
Error on trying to connect as a client on Linux servers

### ISSUE THREAD

**Issue by Harsche** [FirstGearGames/FishNet#598]
**General**
Unity version: 2022.3.17
Fish-Networking version: 4.0.8
Discord link: https://discord.com/channels/424284635074134018/1129457538774073374/1198204402041892894

**Description**
Client throws an error when trying to connect to a Linux server and the player prefabs isn't spawned, although it works on Windows servers. I'm including the stack trace just below. Also, it always gives this warning along with the error: _ObjectId {object id} could not be found in Server spawned, nor Server pending despawn. This may occur as clientHost when objects are destroyed before the client receives a despawn packet. In most cases this may be ignored._

I have only tried connecting to remote linux servers, couldn't test with a local one to see if the issue persists.

<details>
<summary>Stack trace</summary>
<br>
Unable to lookup LocalConnection for 0 as host.
UnityEngine.Debug:LogError (object)
FishNet.Managing.Logging.LevelLoggingConfiguration:LogError (string) (at Assets/Plugins/FishNet/Runtime/Managing/Logging/LevelLoggingConfiguration.cs:128)
FishNet.Managing.NetworkManager:InternalLogError (string) (at Assets/Plugins/FishNet/Runtime/Managing/NetworkManager.Logging.cs:83)
FishNet.Managing.NetworkManagerExtensions:LogError (FishNet.Managing.NetworkManager,string) (at Assets/Plugins/FishNet/Runtime/Managing/NetworkManager.Logging.cs:146)
FishNet.Managing.Client.ClientManager:ParseAuthenticated (FishNet.Serializing.PooledReader) (at Assets/Plugins/FishNet/Runtime/Managing/Client/ClientManager.cs:579)
FishNet.Managing.Client.ClientManager:ParseReader (FishNet.Serializing.PooledReader,FishNet.Transporting.Channel,bool) (at Assets/Plugins/FishNet/Runtime/Managing/Client/ClientManager.cs:495)
FishNet.Managing.Client.ClientManager:ParseReceived (FishNet.Transporting.ClientReceivedDataArgs) (at Assets/Plugins/FishNet/Runtime/Managing/Client/ClientManager.cs:359)
FishNet.Managing.Client.ClientManager:Transport_OnClientReceivedData (FishNet.Transporting.ClientReceivedDataArgs) (at Assets/Plugins/FishNet/Runtime/Managing/Client/ClientManager.cs:322)
FishNet.Transporting.Tugboat.Tugboat:HandleClientReceivedDataArgs (FishNet.Transporting.ClientReceivedDataArgs) (at Assets/Plugins/FishNet/Runtime/Transporting/Transports/Tugboat/Tugboat.cs:231)
FishNet.Transporting.Tugboat.Client.ClientSocket:IterateIncoming () (at Assets/Plugins/FishNet/Runtime/Transporting/Transports/Tugboat/Core/ClientSocket.cs:289)
FishNet.Transporting.Tugboat.Tugboat:IterateIncoming (bool) (at Assets/Plugins/FishNet/Runtime/Transporting/Transports/Tugboat/Tugboat.cs:204)
FishNet.Managing.Transporting.TransportManager:IterateIncoming (bool) (at Assets/Plugins/FishNet/Runtime/Managing/Transporting/TransportManager.cs:718)
FishNet.Managing.Timing.TimeManager:TryIterateData (bool) (at Assets/Plugins/FishNet/Runtime/Managing/Timing/TimeManager.cs:1067)
FishNet.Managing.Timing.TimeManager:IncreaseTick () (at Assets/Plugins/FishNet/Runtime/Managing/Timing/TimeManager.cs:712)
FishNet.Managing.Timing.TimeManager:<TickUpdate>g__MethodLogic|97_0 () (at Assets/Plugins/FishNet/Runtime/Managing/Timing/TimeManager.cs:390)
FishNet.Managing.Timing.TimeManager:TickUpdate () (at Assets/Plugins/FishNet/Runtime/Managing/Timing/TimeManager.cs:380)
FishNet.Transporting.NetworkReaderLoop:Update () (at Assets/Plugins/FishNet/Runtime/Transporting/NetworkReaderLoop.cs:28)
</details>

**Replication**
1. Create a basic scene with a network manager.
2. Configure the client address so that you can connect remotely.
3. Build the linux server (I used the x86_64 architecture)
4. Launch the server
5. Try to connect to it from the unity editor

**Expected behavior**
Client successfully connects to server and player spawns in the scene.

**Screenshots**
![Sem título](https://github.com/FirstGearGames/FishNet/assets/19612688/f0e979ce-3c1d-45b5-baab-22dc0ca50c05)

**Comment by FirstGearGames** [comment]
This is most likely a prefab or build mismatch. EG: prefabs are not ordered correctly on server because server build is old, or not ordered correct on unity editor. I recommend trying a client build to see if that works, if so CHECK Refresh Default Prefabs on your NetworkManager and you should be okay.
