### ISSUE TITLE
A message of length 1030 requires the reliable channel but was sent on channel Unreliable

### ISSUE THREAD

**Issue by richGlumberland** [FirstGearGames/FishNet#599]
**General**
Unity version: 2022.3.14f1
Fish-Networking version: 4.0.8 Prediction V2

**Description**
A message of length 1030 requires the reliable channel but was sent on channel Unreliable. Please file this stack trace as a bug report.
UnityEngine.Debug:LogError (object)
FishNet.Managing.Logging.LevelLoggingConfiguration:LogError (string) (at Assets/FishNet/Runtime/Managing/Logging/LevelLoggingConfiguration.cs:128)
FishNet.Managing.NetworkManager:InternalLogError (string) (at Assets/FishNet/Runtime/Managing/NetworkManager.Logging.cs:83)
FishNet.Managing.NetworkManagerExtensions:LogError (FishNet.Managing.NetworkManager,string) (at Assets/FishNet/Runtime/Managing/NetworkManager.Logging.cs:146)
FishNet.Managing.Transporting.TransportManager:SplitRequired (byte,int,int&,int&) (at Assets/FishNet/Runtime/Managing/Transporting/TransportManager.cs:650)
FishNet.Managing.Transporting.TransportManager:SetSplitValues (byte,System.ArraySegment`1<byte>,bool,int&,int&) (at Assets/FishNet/Runtime/Managing/Transporting/TransportManager.cs:611)
FishNet.Managing.Transporting.TransportManager:SendToClient (byte,System.ArraySegment`1<byte>,FishNet.Connection.NetworkConnection,bool,FishNet.Object.DataOrderType) (at Assets/FishNet/Runtime/Managing/Transporting/TransportManager.cs:493)
FishNet.Managing.Predicting.PredictionManager:SendStateUpdate () (at Assets/FishNet/Runtime/Managing/Prediction/PredictionManager.cs:674)
FishNet.Managing.Timing.TimeManager:IncreaseTick () (at Assets/FishNet/Runtime/Managing/Timing/TimeManager.cs:734)
FishNet.Managing.Timing.TimeManager:<TickUpdate>g__MethodLogic|97_0 () (at Assets/FishNet/Runtime/Managing/Timing/TimeManager.cs:390)
FishNet.Managing.Timing.TimeManager:TickUpdate () (at Assets/FishNet/Runtime/Managing/Timing/TimeManager.cs:380)
FishNet.Transporting.NetworkReaderLoop:Update () (at Assets/FishNet/Runtime/Transporting/NetworkReaderLoop.cs:28)

**Replication**
1. Set up a script to spawn a prefab every 0.1 secs. Prefab is a predicted rigidbody object with the simple replicate, reconcile setup from the doc examples.
2. After 23 spawns this error occurs.

**Expected behavior**
Be able to have more predicted objects active at one time.

**Comment by FirstGearGames** [comment]
Hey, this has already been fixed pending release!

**Comment by FirstGearGames** [comment]
Resolved in 4.0.9
