### ISSUE TITLE
4.0.9. SyncVars do not call WriteDelta() after the first value change.

### ISSUE THREAD

**Issue by ooonush** [FirstGearGames/FishNet#600]
**General**
Unity version: 2021.3.19f1.
Fish-Networking version: 4.0.9

**Description**
c. I can do a Bug Report on GitHub, but this is easy to reproduce. You can see in the screenshot that OnChange is not triggered for clients because WriteDelta and ReadDelta do not occur.
![image](https://github.com/FirstGearGames/FishNet/assets/72870405/217f8148-83e1-4557-a644-7e76eaab8cb1)
The same bug happens if you start the server and connect to it from another editor as a client.

**Replication**

1. Add an object with these components to the scene:
```csharp
public class MyNetworkBehaviour : NetworkBehaviour
{
    public readonly SyncVar<int> MySyncVar = new SyncVar<int>();

    private void Awake()
    {
        MySyncVar.OnChange += (_, next, asServer) =>
        {
            Debug.Log("OnValueChange: " + next + " " + asServer);
        };
    }

    IEnumerator Start()
    {
        while (true)
        {
            yield return new WaitForSeconds(5);
            if (IsOffline) continue;
            MySyncVar.Value += 1;
        }
    }
}
```
2. Start as host.
3. Check the console:
![image](https://github.com/FirstGearGames/FishNet/assets/72870405/217f8148-83e1-4557-a644-7e76eaab8cb1)

**Comment by KeithSwanger** [comment]
Came here to report this. Thank you for the thorough description, I am experiencing the same thing.

**Comment by FirstGearGames** [comment]
Thanks for the find. The fix is to open NetworkBehaviour.SyncTypes and find this line...
```cs
return (writtenCount == dirtyCount);
```
Replace it with this...
```cs
                /* If the number written is the same as those which were dirty
                 * then no dirty rename. Return true if no dirty remain. */
                bool wroteAllDirty = (writtenCount == dirtyCount);
                if (wroteAllDirty)
                    SyncTypeDirty = false;
                return wroteAllDirty;
```
