### ISSUE TITLE
Scene load skipped due to bad handle match

### ISSUE THREAD

**Issue by CRG-Hans** [FirstGearGames/FishNet#602]
**General**
Unity version: 2022.3.17 LTS
Fish-Networking version: 4.0.6
Discord link: https://discord.com/channels/424284635074134018/1034477094731784302/1201806227525599243

**Description**
We're having issues when a connecting client handles the incoming SceneLoadData in `SceneManager.__LoadScenes()`. The incoming data blob has non-zero values for the scene handles. These handles are then matched against already loaded scenes using the Unity Scene.handle property (via `SceneManager.__LoadScenes() -> SceneLookupData.GetScene() -> SceneManager.GetScene() -> UnityEngine.SceneManager.GetSceneAt()` ). Causing a mismatch (the level scene is matched against the clients menu scene). In turn this causes the level scene to be skipped.

_**Note**_ that the non-zero scene handles only happens for the first client to connect to the server. If the client reconnects or another client connects after the initial issue, the received data blob has zero-value handles and the scenes are loaded as expected.

**Replication**
No exact replication. In our case, the second loaded scene tend to get the same handle value (-156) regardless of which scene that is.

**Expected behavior**
Scenes should load and handles should be a Fishnet internal and not rely in the unity scene handle (as it will almost never match between two instances of Unity).

**Comment by FirstGearGames** [comment]
Please update to 4.0.10 or higher and test again.

**Comment by CRG-Hans** [comment]
Updated to 4.1.0 and the issue is gone.
