### ISSUE TITLE
NetworkTransform being stripped on Windows client (Stripping Level High)

### ISSUE THREAD

**Issue by 01c** [FirstGearGames/FishNet#604]
**General**
Unity version: 2022.3.18f
Fish-Networking version: 4.0.10
Discord link: https://discord.com/channels/424284635074134018/1034477094731784302/1203281197610958890

**Description**
When building a windows client NetworkTransform+GoalData seems to be stripped out when **Stripping Level** is set to **High** in **Project Settings/Player**.

This results in one of the following errors:
Server: `Server encountered an error while parsing data for packetId ServerRpc from connectionId 1. Connection will be kicked immediately. Message: Default constructor not found for type FishNet.Component.Transforming.NetworkTransform+GoalData.`
Client: `Default constructor not found for type FishNet.Component.Transforming.NetworkTransform+GoalData.`

**Disabled** - OK
**Minimal** - OK
**Low** - OK
**Medium** - Error
**High** - Error

Setting **Stripping Level** to any option lower than **Medium** and rebuilding fixes it.

**Replication**
1. Set **Stripping Level** in **Project Settings/Player** to higher than **Low*
2. Create a prefab with NetworkTransform
3. Spawn it on the server
4. Join with a newly built Windows client (not editor)
5. Move the spawned prefab in step 1 using transform.position
6. See error.

**Expected behavior**
NetworkTransform+GoalData/NetworkTransform should not be stripped out when using Stripping Level High, if it is used in the project.

**Comment by FirstGearGames** [comment]
Resolved in 4.1.0. Thanks
