### ISSUE TITLE
RebuildSceneIds not considering inactive game objects.

### ISSUE THREAD

**Issue by nelstuff** [FirstGearGames/FishNet#607]
**General**
Unity version: 2022.3.17f1
Fish-Networking version: 3.11.14
Discord link: https://discord.com/channels/424284635074134018/1034477094731784302/1204792233178439740

**Description**
RebuildSceneIds is not considering inactive game objects. I'm duplicating inactive network objects, but the Scene IDs stay the same even when rebuilding, because it doesn't see inactive objects.
This line should have "true" in the argument:
https://github.com/FirstGearGames/FishNet/blob/e31141a804dcd5d7a6167a11036f31457a4177fa/Assets/FishNet/Runtime/Object/NetworkObject.ReferenceIds.cs#L179

**Replication**
1. Clone an inactive networked scene object.
2. Click Rebuilt Scene IDs
3. Both objects have the same scene ID

**Expected behavior**
Objects should have different scene IDs

**Comment by FirstGearGames** [comment]
Thanks for the report. Will get this resolved ASAP.

**Comment by FirstGearGames** [comment]
Resolved in 3.11.16 and 4.1.1
