### ISSUE TITLE
4.1.0 ClientManager.Connection may not be getting set as Authenticated

### ISSUE THREAD

**Issue by FirstGearGames** [FirstGearGames/FishNet#611]
FN 4.1.0

Start client separate, see if authenticated is set.

**Comment by sinfulspartan** [comment]
This line is the issue. The Network LOD is not enabled on the client, but is on the server.
`if (!nm.ObserverManager.GetEnableNetworkLod())
    return;`

**Comment by FirstGearGames** [comment]
Closing this out since we found the source of your problem had changed.
