### ISSUE TITLE
[CodeGen] Invaild IL instruction if compiled in Release mode.

### ISSUE THREAD

**Issue by TsFreddie** [FirstGearGames/FishNet#616]
**General**
Unity version: 2022.3.17
Fish-Networking version: 3.11.17R

**Description**
FishNet generated invalid IL. This particular case is only reproducible with debug mode disabled.
![image](https://github.com/FirstGearGames/FishNet/assets/3797859/97213299-69e5-46ca-9bdf-e71257ab2c54)

**Replication**
1. Get the reproducible test scripts [Scripts.zip](https://github.com/FirstGearGames/FishNet/files/14480641/Scripts.zip)

2. Make sure unity is in Release mode
3. Attach "ProblematicBehaviour" on a GameObject.
4. Run scene.

**Expected behavior**
No invalid instruction errors or crashing.

**Screenshots**
Here's a screenshot of dnSpy looking at the invalid method.
![image](https://github.com/FirstGearGames/FishNet/assets/3797859/812c9d2a-a46e-41d9-b58b-5a22c738b0b8)

**Comment by FirstGearGames** [comment]
Can you please narrow down what line specifically is causing the error? I noticed you had a bunch of fields were are presumably not needed?

Please remove anything not related to the error and re-upload.

**Comment by TsFreddie** [comment]
> Can you please narrow down what line specifically is causing the error? I noticed you had a bunch of fields were are presumably not needed?
> 
> Please remove anything not related to the error and re-upload.

I can try stripping it down a little bit more but I can't guarantee it I would be able to reproduce it. This is a piece of production code isolated out so it looks a bit messy. Removing any parts of the problematic method fixes it so I can't actually identify a single line that is causing this exact problem.

**Comment by TsFreddie** [comment]
```C#
using FishNet.Object;
using FishNet.Object.Synchronizing;

public class SomeReference
{
    public bool RefMethodReturningBool() => true;
    public void RefMethodTakingABool(bool arg) { }
}

public class ProblematicBehaviour : NetworkBehaviour
{
    private SomeReference _reference;
    private float _someFloat;
    private bool _someBool;
    [SyncVar] private float _someSyncVarFloat;

    private void Awake()
    {
        ProblematicMethod();
    }

    private void ProblematicMethod()
    {
        if (IsServer)
        {
            var returnedBool = _reference.RefMethodReturningBool();
            if (returnedBool) _someSyncVarFloat -= 1.0f;

            if (_someBool && _someSyncVarFloat <= _someFloat)
            {
                _someBool = false;
                _someSyncVarFloat += _someFloat;
            }

            if (_someSyncVarFloat < 0 && !_someBool)
            {
                _someBool = true;
                _reference.RefMethodTakingABool(false);
                MethodTakingABool(false);
            }
        }
    }

    private void MethodTakingABool(bool state) { }
}
```

This is as small as I can strip. Removing any line fixes the invalid IL.

**Comment by TsFreddie** [comment]
The above script plus a test scene already setup following the reproducing steps:

[Scripts.zip](https://github.com/FirstGearGames/FishNet/files/14669449/Scripts.zip)

**Comment by TsFreddie** [comment]
I don't want to spam issues, but we've ran into another set of code that behave similarly. But this time only in Debug mode. 

![image](https://github.com/FirstGearGames/FishNet/assets/3797859/be066934-e2b6-42b7-ba1a-f4d5cd58d6b5)
![image](https://github.com/FirstGearGames/FishNet/assets/3797859/e56137bb-bf2f-49a1-9b06-8632ac68db9f)

```C#
using System;
using System.Collections;
using System.Collections.Generic;
using FishNet.Object;
using FishNet.Object.Synchronizing;
using Random = UnityEngine.Random;

public enum SomeEnum { A, B }

[Serializable]
public struct SomeStruct
{
    public SomeEnum SomeEnum;
}

public class SomeReference
{
    public SomeStruct AStruct { get; }
    public void SomeMethod() { }
}

public class ProblematicBehaviour2 : NetworkBehaviour
{
    [SyncVar]
    private uint _someSyncVarUInt;
    private List<SomeReference> _someReferences;
    private SomeReference GetSomeOtherReference() => null;

    private IEnumerator SomeCoroutine()
    {
        yield break;
    }

    protected void Awake()
    {
        ProblematicOnChangedMethod(false, true, true);
    }

    private void ProblematicOnChangedMethod(bool prev, bool next, bool asServer)
    {
        if (next == prev) return;
        if (next)
        {
            if (asServer)
            {
                _someSyncVarUInt = 0;
                var i = Random.Range(0, _someReferences.Count);
                _someReferences[i].SomeMethod();
                return;
            }

            var player = GetSomeOtherReference();
            if (player.AStruct.SomeEnum != SomeEnum.B) return;
            StartCoroutine(SomeCoroutine());
        }
        else
        {
            if (asServer)
            {
                _someSyncVarUInt = 0;
                return;
            }
        }
    }
}
```

Scripts + Test Scene
[Scripts2.zip](https://github.com/FirstGearGames/FishNet/files/14721197/Scripts2.zip)

Again, I've try my best to minimize the code (that is, removing any line in the problematic method fixes itself again.)

**Comment by FirstGearGames** [comment]
I assume you mean release vs development(Debug)?
Thank you for the information I'll take a look at this asap.

**Comment by TsFreddie** [comment]
> I assume you mean release vs development(Debug)? Thank you for the information I'll take a look at this asap.

I mean in-editor debug toggle where you enable debugger connection as shown in the post screenshot (located at the bottom right corner of an editor window). Not development build vs regular build. Although, I didn't test any build behaviors. Build **might** be invalid anyway since IL2CPP need valid IL to begin with.

**Comment by FirstGearGames** [comment]
I took another run at this in V4 and was not able to reproduce. V4 doesn't use the old SyncVar codegen so that is probably why. 

There's no plans to provide more updates to V3 given V4 is in stable.

**Comment by TsFreddie** [comment]
Hi, do you do paid commissions for patching v3 by any chance? We are shipping a game in V3 in two weeks and the team has already been crunching and I'm afraid of switching to V4 would put additional pressure on the team at this exact moment.

We can workaround the bug for the time begin. so it is ok if it is not possible.
