### ISSUE TITLE
High tickrate NT rotation bug

### ISSUE THREAD

**Issue by SnaiperoG3D** [FirstGearGames/FishNet#619]
Unity version: 2022.3.16f1
Fish-Networking version: 4.1.2 Pro
Discord link: https://discord.com/channels/424284635074134018/1034477094731784302/1216771439286550588

**Description**
At high tickrate (128) NT rotation on client auth not sending correctly to clients. When player moving (position changed) rotation not syncing. When player stops or after some time, rotation insta setted to last value. Checked with parrelsync, on server instance rotation is correct, but on non owner clients its bugging. Network LOD disabled.

**Replication**
Set tickrate 128
Any 3d project with moving and rotating players.

**Expected behavior**
Normal rotation sync

**Screenshots**
[Video](https://drive.google.com/file/d/1M3p6NSCKnr7p4k6uymdQtDKn3agnkDeK/view?usp=sharing)

**Comment by FirstGearGames** [comment]
Does it have to be moving as well or will just rotating cause it?

**Comment by SnaiperoG3D** [comment]
It happens when player moving or jumping (position change), when hold still rotation sync works fine. My game need to have high physics tickrate, so i just change timemanager to unity physics, manual setup physics and set tickrate to 30. Its my workaround for this issue and i guess good for bandwidth.

**Comment by FirstGearGames** [comment]
Alright I'll take a look before the release of 4.2 (next version). Hopefully I can get it resolved then but bumping the prediction 2 release has priority. If not then, I will next.

**Comment by FirstGearGames** [comment]
Updating to let you know this will be post 4.2.

**Comment by FirstGearGames** [comment]
Issue reporter indicated bug could not be reproduced in new project, and issue went away in their project.
