### ISSUE TITLE
IEquatable, Custom comparer, code generation error. Think, not generate op_Equality method.

### ISSUE THREAD

**Issue by im-ikao** [FirstGearGames/FishNet#624]
**General**
Unity version: 2023.2.11f1
Fish-Networking version: 4.1.2r
Discord link: https://discordapp.com/channels/424284635074134018/1034477094731784302/1219792230995464222

**Description**
I try make custom comparer for IEquatable inherited struct, but unity throw error: (0,0): error  - Type NetworkGuid implements IEquatable but the comparer method could not be found.

**Replication**
1. Make struct inherited by IEquatable
2. Make custom comparer by attribute
3. Make CSP with reconcile and replicate with that struct

**Expected behavior**
Unity not throw error, Custom comparer created

**Screenshots**
![image](https://github.com/FirstGearGames/FishNet/assets/83168391/4e68759a-554b-4fb7-87e0-bbb06146ccee)

**Minds**
After a little code reverse I noticed the search method "op_Equality"
`MethodDefinition cMd = tr.CachedResolve(base.Session).GetMethod("op_Equality");`
but there it method don't can be founded, i try to see cache for this "tr" and I also didn’t find the generated method, i think it may'be not generated/not cached, because if i add method "op_Equality" manualy, unity not throw error.

**Comment by FirstGearGames** [comment]
Can you please post the code as text. Don't forget the code tag above this write box.

**Comment by FirstGearGames** [comment]
Queued to close in 2 weeks due to inactivity.
