### ISSUE TITLE
Prediction v1 Character Controller demo not smoothing

### ISSUE THREAD

**Issue by HuseyinAkay** [FirstGearGames/FishNet#626]
**General**
Unity version: Tested and got the same result with 2021.3.34f1 and 2022.20
Fish-Networking version: Tested and got the same result with 4.1.0 and 4.1.4
Discord link: https://discord.com/channels/424284635074134018/1034477094731784302/1220996852942635008

**Description**
Graphical object of the Predicted Character Controller (prediction v1) example doesn't get smoothed when moving...
However it starts the smoothing after i change the interpolation value and than change it back to 1 (which is the default value of the prefab). The demos for rigidbody prediction and transform prediction seem to be not having this behavior

**Replication**
1. Open an empty unity project
2. Import Fishnet
3. Open Character Control demo scene for prediction v1
4. Hit play
5. Move with wasd

**Expected behavior**
Graphical object to be smoothly moving when the PredictedObject component's interpolation value is greater than 0 and the Smooth Position, Smooth Rotation options are ticked...
As it does after i change the interpolation value and than change it back to 1 (which is the default value of the prefab).

**Screenshots**
https://github.com/FirstGearGames/FishNet/assets/86929654/b1bb05f2-5b6b-4901-b76f-702f33090d5f

**Comment by FirstGearGames** [comment]
Prediction 1 demos have been removed in 4.2 since they are obsolete upon the release. Prediction 1 scripts will still work.
