### ISSUE TITLE
AddConnectionToScene not making client observe initial scene

### ISSUE THREAD

**Issue by maxkratt** [FirstGearGames/FishNet#628]
**General**
Unity version: 2022.3.16f1
Fish-Networking version: 4.1.4R Pro and 3.11.18R Pro

**Description**
When using the `AddConnectionToScene` method in `SceneManager.OnClientLoadedStartScenes` to add the new client as an observer of the starting scene, it does not start observing objects in the scene.

**Replication**
1. Run the example as a host
2. The ObserverIndicator Cube GameObject does not become visible
3. The RPCTester does not run OnStartClient

**Expected behavior**
I would expect any clients to observe the scene correctly as this is similar to using the PlayerSpawner's "Add To Default Scene" option as far as I am aware.

**Example File**
[AddConnectionsTest.zip](https://github.com/FirstGearGames/FishNet/files/14756738/AddConnectionsTest.zip)

**Comment by FirstGearGames** [comment]
Checked out the project and this doesn't seem to be a bug.  The script is adding to the scene it exists as shown...
```cs
        private void OnClientLoadedStartScenes(NetworkConnection conn, bool asServer)
        {
            if (asServer)
                _networkManager.SceneManager.AddConnectionToScene(conn, gameObject.scene);
        }
```
and since it's on the NetworkManager it goes to the DDOL scene. The player is being added to the DDOL scene not the game scene.

**Comment by maxkratt** [comment]
Ooh, that makes a lot of sense, and I feel stupid now lol. Thanks for taking a look at it!
