### ISSUE TITLE
Setting a SyncVar's field and using Dirty doesn't correctly update the SyncVar

### ISSUE THREAD

**Issue by maxkratt** [FirstGearGames/FishNet#629]
**General**
Unity version: 2022.3.16f1
Fish-Networking version: 4.1.4R Pro
Discord link: https://discord.com/channels/424284635074134018/966848379298652200/1221825451786375172

**Description**
Setting a field on a class that is a SyncVar and then calling Dirty on the SyncVar does not invoke the OnChange method for the server, and it does not set that value for new observers.

**Replication**
1. Import the sample and open the scene
2. Press play and see how the OnChange method isn't invoked
3. Launch another client and see how the SyncVar isn't updated for the new observing client

**Expected behavior**
I would expect it to be synced properly when using `Dirty`

**Example**
[SyncVarBug.zip](https://github.com/FirstGearGames/FishNet/files/14758573/SyncVarBug.zip)

**Comment by FirstGearGames** [comment]
Resolved in 4.2
