### ISSUE TITLE
SyncList not syncing on reconnect

### ISSUE THREAD

**Issue by maxkratt** [FirstGearGames/FishNet#639]
**General**
Unity version: 2022.3.16f1
Fish-Networking version: 4.1.6
Discord link: https://discord.com/channels/424284635074134018/1224835279005683832/1224835279005683832

**Description**
A SyncList on a scene object is not being synced to a client that connected, disconnected, and then reconnected.

**Replication**
1. import example
2. run two parrel sync instances, one as host one as client
3. view the list in the inspector on the SyncListObject
4. press "a" to add items to the sync list and "r" to remove
5. add some items while the client is connected, disconnect the client
6. reconnect the client, the synclist doesn't update
7. add new items and those are synced

**Expected behavior**
The SyncList should be synced to rejoining clients.

**Example files**
[SyncListBug.zip](https://github.com/FirstGearGames/FishNet/files/14883254/SyncListBug.zip)

**Comment by FirstGearGames** [comment]
Resolved in 4.2.
