### ISSUE TITLE
Any plans for a Spawn Prediction like feature?

### ISSUE THREAD

**Issue by emrys90** [FirstGearGames/FishNet#64]
Photon Fusion has a Spawn Prediction system where the object is instantiated on the client at first, and then synced with the spawned object on the server:
https://doc.photonengine.com/en-us/fusion/current/manual/spawning#spawn_prediction

The benefits for this is that it helps reduce latency in a virtual reality game. For example, I have local objects that turn into networked objects when grabbed. In virtual reality its very bad to have that kind of latency between player interaction and the server spawning the object.

**Comment by FirstGearGames** [comment]
See photon notes: **Spawn Prediction is only available in Host / Server Mode **
Seems a bit pointless...

**Comment by emrys90** [comment]
It's not pointless at all. It allows the game to act like an object is spawned from the client to prevent any delay in the object appearing, but yet its still spawned from the server to be server authoritative.

**Comment by emrys90** [comment]
I'll give an example of an ideal functionality and use case.

On the client a network object is instantiated and initial SyncVar values set for it. The client then does an rpc to the server, the server does any validation logic needed, and then spawns the networked object for all players. On the first client instead of instantiating a new object, it reuses the predicted object instance and replaces its SyncVar values with what the server said they should be.

My use case for this would be a props menu. I can show 3d models of the props, a player grabs the prop, and its immediately visible in their hand without a delay waiting for the server to instantiate the networked object.

**Comment by FirstGearGames** [comment]
I'm a little thrown off by how this is only available on host. It seems a bit like a catch-22 and in reality not that useful because none of the other players can benefit from it.

BUT ... I think if I were to remove the ability to set server-side values I think it may be doable. I could make it possible for the client to spawn network objects preemptively and when the spawn packet does arrive, assign that value Ids and perform normal callbacks.

**Comment by emrys90** [comment]
I think their documentation is saying that its not available in peer to peer connections, not that it can only run on the host.

**Comment by FirstGearGames** [comment]
I added this under unsorted on the roadmap.
https://fish-networking.gitbook.io/docs/manual/general/road-map

**Comment by emrys90** [comment]
Thank you!
