### ISSUE TITLE
The iteration limit in the UpdateTimedObservers.

### ISSUE THREAD

**Issue by Jtree03** [FirstGearGames/FishNet#644]
**General**
Unity version: 2022.3.10f1
Fish-Networking version: 3.11.7R

**Description**
https://github.com/FirstGearGames/FishNet/blob/4f126df78c450ca44afa2c40372599f00f89a08e/Assets/FishNet/Runtime/Managing/Server/Object/ServerObjects.Observers.cs#L73

We're experiencing issues with the Distance Condition due to the iteration limit.

If there are too many network objects, there is a problem of spawning(or despawning) too late. (like MMO-RPG)

It would be helpful to have an option in the observer manager that affects the number of iterations per tick.

**Comment by FirstGearGames** [comment]
I realize you closed this out but in FishNet 4.2.0 I added a feature to adjust the max iteration time in the ObserverManager.
![image](https://github.com/FirstGearGames/FishNet/assets/27169134/a29fe953-2ab8-4e6b-91d7-8788a77b3210)

**Comment by Jtree03** [comment]
I was working around it myself, but thanks for adding it officially!
