### ISSUE TITLE
CreateWrite/Read: IntPtr is an unsupported type.

### ISSUE THREAD

**Issue by jonwsavage** [FirstGearGames/FishNet#65]
Hey,

I've set up a brand new project, imported Fishnet (2.0.0), HeathenEngineering Steamworks, and the FishySteamworks assets. However, when Unity attempts to compile, it gives me the following errors:

```
(0,0): error  - CreateWrite: IntPtr is an unsupported type. Mostly because we don't know what the heck it is. Please let us know so we can fix this.

(0,0): error  - Could not create serializer for System.IntPtr.

(0,0): error  - CreateRead: IntPtr is an unsupported type. Mostly because we don't know what the heck it is. Please let us know so we can fix this.

(0,0): error  - Could not create deserializer for System.IntPtr.

```

I'm on Unity 2021.3.1f1 with the URP pipeline.

**Comment by FirstGearGames** [comment]
IntPtrs use unsafe code which is likely why the generator won't pick them up. I don't want to force unsafe code onto users so I"m labeling this as *wontfix*.

Although you should be able to create a custom serializer for this without issue.

**Comment by RyanGarber** [comment]
I just received this error, but I don't use any IntPtrs or unsafe code at all. Interestingly, it seemed to happen while I left the Unity Project open in the background. I'm using Epic Online Services and its transport.

**Comment by FirstGearGames** [comment]
What FN version?

**Comment by RyanGarber** [comment]
Wow, insanely fast response! I realize I was mistaken. One of my structs contained an EpicAccountId, and one of its constructors takes an IntPtr. Thank you anyways.

**Comment by FirstGearGames** [comment]
Gotcha. Nps.
