### ISSUE TITLE
Prediction V1 Smoother not applied for host who is also a client

### ISSUE THREAD

**Issue by VitIhn** [FirstGearGames/FishNet#665]
**General**
Unity version: 2022.3.15f1
Fish-Networking version: 4.2.2
Discord link: https://discord.com/channels/424284635074134018/1167060429051269200/1235335222753624065

**Description**
InitializeSmoother does not run for a host who is also a client (Start Server, Start Client on same application on Tugboat, for example) 
This is happening because for this "client", in the lines 278-290 of PredictedObject.cs:

```cs
 public override void OnStartNetwork()
        {
            /* If host then initialize owner smoother.
             * Host will use owner smoothing settings for more
             * accurate results. */
            if (base.IsHostInitialized)
                InitializeSmoother(true);

            UpdateRigidbodiesCount(true);
            ConfigureRigidbodies();
            ConfigureNetworkTransform();
            base.TimeManager.OnPostTick += TimeManager_OnPostTick;
        }
```

base.IsHostInitialized will be false

**Replication**
Sorry, this one is a little long to implement, but here's a short sketch:
Start server and host on the same application. 
Use CSP with rotations for camera. 
Use predicted object with interpolation = 2
See the jitter of the camera on host = client and see a smooth movement on a standalone client.

Changing any of the parameters of the predicted object in the editor during the playmode with resent the smoother and client who is also a host will run smoothly as it supposed to. 

**Proposed solution**

Remove 
```cs
            if (base.IsHostInitialized)
                InitializeSmoother(true);
```

from OnStartNetwork

And change OnStartClient in lines 298-302 of PredictedObject.cs to be:

```cs
        public override void OnStartClient()
        {
            ChangeSubscriptions(true);
            Rigidbodies_OnStartClient();

            if (InstanceFinder.IsServerStarted)
                InitializeSmoother(true);
        }
```

**Comment by FirstGearGames** [comment]
I believe the intended change when updating this component was to use base.IsHostStarted. In OnStartNetwork Started will be true but Initialized will not since it will invoke on the server before client is initialized.

This has been fixed in 4.3.0
