### ISSUE TITLE
ObjectCaches.Retrieve cannot find the default constructor when Managed Stripping Level is High

### ISSUE THREAD

**Issue by ooonush** [FirstGearGames/FishNet#677]
**General**
Unity version: 6000.0.2f1
Fish-Networking version: 4.3.1

**Description**
In build not, when creating a NetworkObject using PredictionV2 cannot find a constructor for AdaptiveLocalTransformTickSmoother:

![image](https://github.com/FirstGearGames/FishNet/assets/72870405/1530b203-bfbb-4fda-928c-e31a79f270c9)

This happens when you call the Retrieve method in the ObjectCaches class:

![image](https://github.com/FirstGearGames/FishNet/assets/72870405/e5719a61-fde8-4762-8aa2-81084e374db4)

**Expected behavior**
I think you could add a [Preserve] attribute or make a Retrieve method, or add a new () constraint for T and get rid of reflection:

![image](https://github.com/FirstGearGames/FishNet/assets/72870405/299dcdd6-def5-4d01-88f4-237d59612a01)

![image](https://github.com/FirstGearGames/FishNet/assets/72870405/47d3cce8-a992-4008-b568-9b86f926c7b4)

**Comment by FirstGearGames** [comment]
Are you able to make a debug build to see what object is missing the ctor?

**Comment by FirstGearGames** [comment]
Closed due to inactivity.
