### ISSUE TITLE
Using generics with NetworkBehaviour classes throws at runtime.

### ISSUE THREAD

**Issue by FirstGearGames** [FirstGearGames/FishNet#68]
Reported by Khalos.

Using generics with NetworkBehaviour classes throws at runtime. Reproduced by adding the following to an object in the scene.
```

using FishNet.Object;

public class Base<T> : NetworkBehaviour 
{
}

public class GenericIssue : Base<string> 
{
}
```

Decompiler shows the generics are not being included when Awake is initializing. Codegen will need to be adjusted to check for generics in Awake calls, and NetworkInitialize calls.
```
//invalid generated code.
    if (((AA<>) this).NetworkInitializeEarly_AA`1_Assembly\u002DCSharp\u002Edll)
      return;
```

**Comment by lukechatton** [comment]
Just ran into this as well. Did anyone ever find a workaround?

**Comment by FirstGearGames** [comment]
This is currently being worked on. There is no ETA yet but everything is believed to be working except SyncVars in the generic types.

**Comment by FirstGearGames** [comment]
No reports of problems yet. We may have some rare instances down the road but until then this is considered working!
