### ISSUE TITLE
Short SyncTimer not detected on client when low tickrate

### ISSUE THREAD

**Issue by maxkratt** [FirstGearGames/FishNet#686]
**General**
Unity version: 2022.3.16f1
Fish-Networking version: 4.3.3
Discord link: https://discord.com/channels/424284635074134018/1245275775939383350

**Description**
When a SyncTimer is started with a short time such as 0.01 and the tickrate is not very high for example 30, then non-host clients can miss the Finished OnChange event.

**Replication**
1. Import example package and run two copies of the game
2. Click the "START TIMER SHORT" or "START TIMER LONG" buttons on the server to start sort and long timers.
3. The solo client will correctly print "The timer has completed!" for the long timer but not the short one.
4. If you max out the server tick rate then the solo client will receive the log for the short timer.

**Expected behavior**
The solo client should detect the timer finishing on any tickrate.

**Example Files**
[SyncTimerBug.zip](https://github.com/user-attachments/files/15533326/SyncTimerBug.zip)

**Comment by FirstGearGames** [comment]
Was hoping this would have resolved itself with one of the newer releases but the bug still seems to be present. Don't imagine it's much a problem to fix, thanks max.

**Comment by FirstGearGames** [comment]
Fixed in 4.4.8
