### ISSUE TITLE
SyncList / SyncDictionary OnChanged not called on OnStartClient

### ISSUE THREAD

**Issue by gresc574** [FirstGearGames/FishNet#69]
Using Fishnet 2.2.1

When joining game with SyncList hook set in OnStartClient -> Ops do not call on join. Currently have to hook in Awake

**Comment by DevFlash33** [comment]
That is intentional, in OnStartClient are all before synchronisations already done, so that you dont need to worry about. You should subscribe to the changes in Awake

**Comment by FirstGearGames** [comment]
Changes done in OnStartServer, or outside Awake really, should always invoke the callback.
SyncVars do, if SyncLIst are not then this is a bug.

Values will be synchronized by OnStartClient but the callbacks should occur **after.** This is so callbacks occur after all OnStartClients invoke, giving the developer a chance to initialize for the client on all scripts before receiving the callbacks.

**Comment by FirstGearGames** [comment]
Resolved in 2.2.2.
Other SyncObjects will be checked as well.
