### ISSUE TITLE
Unreliable buffered rpc corruption

### ISSUE THREAD

**Issue by avgarrison** [FirstGearGames/FishNet#697]
# Important
If General, Description, and Replication are not completed the issue will be closed immediately.

**General**
Unity version: 2022.3.27f1
Fish-Networking version: 4.3.5
Discord link: https://discord.com/channels/424284635074134018/1248402259499417640

**Description**
4.0.7 introduced a change in NetworkBehaviour.RPCs.cs that causes unreliable buffered rpc corruption. See the discord link above.

**Replication**
See Discord link above.

The changes made in this file seem to have fixed the issue for us.
[NetworkBehaviour.RPCs.cs.txt](https://github.com/user-attachments/files/15779591/NetworkBehaviour.RPCs.cs.txt)

**Comment by FirstGearGames** [comment]
Resolved in 4.3.6
