### ISSUE TITLE
DefaultPrefabObjects gets recreated even when disabled

### ISSUE THREAD

**Issue by maxkratt** [FirstGearGames/FishNet#699]
**General**
Unity version: 2022.3.16f1
Fish-Networking version: 4.3.5
Discord link: https://discord.com/channels/424284635074134018/1034477094731784302/1250078081482489916

**Description**
The DefaultPrefabObjects gets recreated even when it is disabled in the FishNet configuration.

**Replication**
1. Delete the DefaultPrefabObjects asset, it is recreated automatically.
2. Disable it in the FishNet configuration.
3. Delete the DefaultPrefabObjects asset, it is still recreated automatically.

**Expected behavior**
It shouldn't be recreated when it is disabled.

**Comment by FirstGearGames** [comment]
Resolved in 4.3.6
