### ISSUE TITLE
NetworkAnimator Syncs Animator Int Parameters Incorrectly

### ISSUE THREAD

**Issue by 0risin** [FirstGearGames/FishNet#7]
Fishnet: 1.1.4
Unity: 2021.2.7f1
Server: Headless, Editor
Client: Editor

**Server NetworkAnimator adds two 0's to int-Parameter**

Weapon parameter is 6 on client.
Weapon parameter is 600 on server.

Client:
![image](https://user-images.githubusercontent.com/7229990/148833753-5503b4be-905a-4a0b-ad64-5b23c50e7c21.png)
 Server:
 
![image](https://user-images.githubusercontent.com/7229990/148833762-1c2911a9-544c-48ae-985d-b1ea0a91200c.png)

_AND_

**After Moving Player NetworkAnimator sets int-Parameter to 0 and only updates it once it changed again**

Weapon parameter is 6 on client after changing scenes.
Weapon parameter is 0 on server after changing scenes.

**Comment by FirstGearGames** [comment]
Resolved in 1.1.4.Nightly.1

**Comment by 0risin** [comment]
NetworkAnimator resets int-Values on server side (When NA is ClientAuthoritative) after changing scenes with the scene manager.
ParrelSync is used. Clone is Server.
