### ISSUE TITLE
Networked Scene Objects not initializing Client across multi-scene setup

### ISSUE THREAD

**Issue by AustinEast** [FirstGearGames/FishNet#700]
**General**
Unity version: 2022.2.19
Fish-Networking version: 4.3.5.Pro
Discord link: https://discord.com/channels/424284635074134018/1248389964341710908

**Description**
When loading a client and multiple global scenes, networked scene objects across the opened scenes are not getting initialized correctly.  The following screenshot shows what happens when you start as host in the reproduction package: 
<img width="554" alt="global scene bug 1" src="https://github.com/FirstGearGames/FishNet/assets/9554269/0df9f600-ded1-4b98-9126-bb0d356bbf02">
As you can see in this screenshot (which is running as a Host client), various `Networked GameObject` and `Networked Prefab` objects are either only server initializing (in the `Boot` scene) or even not at all (in `TestSceneA`, which is the active scene). Oddly enough, in this current setup, the objects in `TestSceneB` initialize as client objects just fine!

**Replication**
1. Open scene `Global Scene Visibility Bug/Scenes/Boot`
2. Enter Playmode and start both server and client
3. Observe the different `Networked GameObject` and `Networked Prefab` objects and check whether they've been initialized on the client

**Expected behavior**
I would like a way for a client to initialize objects across multiple scenes successfully.

**Screenshots**

**Reproduction Package**
[Global Scene Visibility Bug.zip](https://github.com/user-attachments/files/15829710/Global.Scene.Visibility.Bug.zip)

**Comment by Canglangzi** [comment]
I also encountered this problem. I have absolutely no problems using 4.3.1R.Pro before the project I am developing now.

I have this problem when using FishNetworking.4.3.5R.Pro

Similar to
![01b93ee2668f6e32edbbf2fb0d347916](https://github.com/FirstGearGames/FishNet/assets/61041281/9b6a6ca8-a9b5-4e46-ad8a-05b3ff838b0f)

I ran multiple tests It seems that as long as there are multiple scenarios, it may not be initialized.
He may need a quick fix

![image](https://github.com/FirstGearGames/FishNet/assets/61041281/a2559710-db93-41fe-8bb1-67ee4e334113)

**Comment by Canglangzi** [comment]
I would like to add that the broadband component does not work, it seems that there is a problem with the event.

**Comment by AustinEast** [comment]
Update:

I looked at the repro project again and decided to try rebuilding the scene Ids for all the scenes (`Boot`, `TestSceneA`, and `TestSceneB`) and we made some progress! The clients are successfully being initialized for both `TestSceneA` and `TestSceneB`! Glad the fix was an easy one for those 😄

However, the objects in the `Boot` scene are still not initializing on the client, as you can see here: 
![Screenshot 2024-06-21 143246](https://github.com/FirstGearGames/FishNet/assets/9554269/96232f6b-2f31-42ab-bab4-5f20ec92cff7)

Why could these objects not be initializing on the client?

I've attached the updated Reproduction Package:
[Global Scene Visibility Bug 2.zip](https://github.com/user-attachments/files/15933947/Global.Scene.Visibility.Bug.2.zip)

**Comment by maxkratt** [comment]
The client isn't observing that scene, so it makes sense that it doesn't initialize the objects in it. FishNet will know if a client is loaded into a scene using one of the FishNet SceneManager events, but it won't if the scene isn't loaded using them. So in such a case you need to explicitly tell FishNet that it has been using the `SceneManager.AddConnectionToScenes`/`SceneManager.AddOwnerToScene` method. The PlayerSpawner component can do this for you if you use the "Add To Default Scene" option on it and the player object gets instantiated into that specific scene. (Which it isn't doing so in this example)

**Comment by FirstGearGames** [comment]
This appears to be resolved so I am closing it out. If the problem persist please comment here or even @mention me on Discord linking this issue to fast track resolution. Thanks!
