### ISSUE TITLE
Nullable DespawnType? can both be not null and have no value

### ISSUE THREAD

**Issue by dwal02** [FirstGearGames/FishNet#708]
# Important
If General, Description, and Replication are not completed the issue will be closed immediately.

**General**
Unity version: 2022.3.14f1
Fish-Networking version: Unsure. Directly pulled from GitHub. 4.3.5R ?
Discord link:
** Above, post a link from our Discord where you troubleshot the issue (on Discord click the three dots next to the message, then Copy Message Link). Issue may be closed out if this is not included.

**Description**

When calling Despawn, a missing despawnType parameter somewhere along the chain causes despawnType to both be not equal to null and have no value, causing a crash inside ServerManager.Despawn(NetworkObject, DespawnType).

**Replication**

Call Despawn(networkObject) on a non-server-owned object within a ServerRPC within a NetworkBehaviour, without the despawnType parameter.

**Expected behavior**

This is easily resolvable by replacing resolvedDespawnType = (despawnType == null) on line 147 of ServerManager.QOL.cs with resolvedDespawnType = (despawnType == null || !despawnType.HasValue) or resolvedDespawnType = (!despawnType.HasValue)

**Screenshots**

![DespawnTypeBug](https://github.com/FirstGearGames/FishNet/assets/18695173/2edd3879-26b4-4a52-b99f-2c8d901d8893)

**Comment by FirstGearGames** [comment]
Wondering if that's a Unity bug. The compiler is supposed to replace null
check with HasValue.

Making the change to only check HasValue should suffice either way.

**Comment by FirstGearGames** [comment]
Definitely a Unity bug. I'll get it resolved in 4.3.8.

**Comment by dwal02** [comment]
Cheers !


________________________________
