### ISSUE TITLE
Import warning in Unity

### ISSUE THREAD

**Issue by CRG-Viktor** [FirstGearGames/FishNet#710]
**General**
Unity version:  2022.3.35f1
Fish-Networking version: 4.3.6r-pro
Discord link: https://discord.com/channels/424284635074134018/1034477094731784302/1257627990565720065

**Description**
Hi, there is a broken meta file in the repository of fishnet right now

The file in question:
https://github.com/FirstGearGames/FishNet/blob/main/Assets/FishNet/Runtime/Managing/Prediction.meta

The warning:
The GUID inside 'FishNet/Runtime/Managing/Prediction.meta' cannot be extracted by the YAML Parser. Attempting to extract it via string matching instead. Please verify the file does not contain unexpected data.

**Replication**
1. Import fishnet in a new project

**Expected behavior**
No errors or warnings

**Screenshots**

**Comment by CRG-Viktor** [comment]
Also found that this file has the same issue https://github.com/FirstGearGames/FishNet/blob/main/Assets/FishNet/CodeGenerating/Processing/Prediction.meta

**Comment by FirstGearGames** [comment]
I'll delete the metas so they regenerate. Thanks!
Resolved in 4.3.8.

**Comment by FirstGearGames** [comment]
I've deleted the meta files and reimported all to test for warning, it did not appear. Let's hope that resolves it for the upcoming release.
