### ISSUE TITLE
[CodeGen Bug]: Certain function signatures will cause compilation errors.

### ISSUE THREAD

**Issue by aaronkwan** [FirstGearGames/FishNet#713]
**General**
Unity version: 2022.3.10f1
Fish-Networking version: 4.2.0R
Discord link: [link](https://discord.com/channels/424284635074134018/1258619066164187177/1258619066164187177)

**Description**
When a public static function with signature: (GameObject prefab, Transform parent) is included in a monobehavior class, it causes fishnet codegen errors.

See text file for the errors.
[fishneterror.txt](https://github.com/user-attachments/files/16104373/fishneterror.txt)

**Replication**
1. Create a monobehavior script (and use it somewhere)
2. Make a function with the signature
3. Compile code

**Expected behavior**
See discord link
**Screenshots**
See discord link

**Comment by FirstGearGames** [comment]
Most likely Unity issue. Try updating to the latest to see if the issue is resolved. If not you may need to clear your Unity caches (Library, obj, temp)

**Comment by FirstGearGames** [comment]
Closed due to inactivity.
