### ISSUE TITLE
Network Animator doesn't work correctly when disabling client-authorative

### ISSUE THREAD

**Issue by erdopfi** [FirstGearGames/FishNet#716]
**General**
Unity version: 2022.3.20f1
Fish-Networking version: 4.3.5R
Discord link: https://discord.com/channels/424284635074134018/1034477094731784302/1260879798293757952

**Description**
The Network animator doesn't work correctly, when disabling client-authorative - setting booleans on the Animator causes the Network Animator to continiously set the boolean to true or false.

**Replication**
1. Create an Animator Controller and add it to a GameObject
2. Add a Network Animator component and disable client-authorative
3. Start client and server on the same build
4. Instantiate the GameObject
5. Set the bool to true on the first update function cycle

**Expected behavior**
The bool should switch between true and false every update cycle, even though only a single SetBool command has been made.

**Comment by LeThaiThinh18021228** [comment]
does it only with bool? or even float? I have error with float value on clienthost too.

**Comment by erdopfi** [comment]
> does it only with bool? or even float? I have error with float value on clienthost too. it constantly changing value randomly. I think it maybe related to conciliation error

I haven't tested it, but it probably is the same for all value types, I guess.

**Comment by FirstGearGames** [comment]
This was resolved in 4.3.6
