### ISSUE TITLE
"Send rate updated to" Log

### ISSUE THREAD

**Issue by TheoLemoine** [FirstGearGames/FishNet#722]
**General**
Unity version: 2021.3.28f1
Fish-Networking version: 4.3.7R.Pro

**Description**
`Debug.LogError($"Send rate updated to {sendRate}");` in `SyncBase.cs` line 152
The log does not have a condition, it seems like a forgotten debug, it spams in PredictedOwner.Awake()

**Comment by FirstGearGames** [comment]
Resolved in 4.3.8 ty again.
