### ISSUE TITLE
The OnTrySpawnServer() Method in PredictedSpawn.cs is never called in the FishNet Codebase

### ISSUE THREAD

**Issue by R0N222** [FirstGearGames/FishNet#725]
**General**
Unity version: 2021.3.34
Fish-Networking version: 4.3.8
Discord link:https://discord.com/channels/424284635074134018/1034477094731784302/1263999447117860864

**Description**
OnTrySpawnServer() in PredictedSpawn.cs is never called in the FishNet codebase.
In Comparison, the OnTryDespawnServer() Method is called in ManagedObjects.Spawning.cs.
![image](https://github.com/user-attachments/assets/db9106a0-d16a-4a8f-9b2f-542697679b3d)

OnTrySpawnClient(), OnTryDespawnServer(), and OnTryDespawnServer() work as intended.
But even returning false in OnTrySpawnServer() does not affect the client spawning objects.

**Replication**
I also tested the methods in a simple unity setup by overriding the PredictedSpawn.cs and Debug.log() if they get called.
It's just a simple spawner script that spawns and despawns objects, on keyboard input.
I attached a unity package with the scene, prefabs, and scripts.
If anything else is needed feel free to ask.
[SpawnIssueFishNetProject.zip](https://github.com/user-attachments/files/16322036/SpawnIssueFishNetProject.zip)

**Expected behavior**
OnTrySpawnServer() should be called when a client tries to Spawn an object and asks the server to verify the spawning.

**Comment by FirstGearGames** [comment]
I need to run a few tests on the changes but it will be resolved in 4.4.0

**Comment by R0N222** [comment]
Thx, sounds great.
