### ISSUE TITLE
Misleading method description

### ISSUE THREAD

**Issue by JohnyBro** [FirstGearGames/FishNet#726]
# Important
If General, Description, and Replication are not completed the issue will be closed immediately.

**General**
Unity version: Unity 6 Preview
Fish-Networking version: 4.3.8R

**Description**
The description of NetworkObject.SetParent() say that we can pass null to remove parenting but when doing so it produce a NullReferenceException.

**Replication**
Call SetParent(null) on a NetworkObject.

**Expected behavior**
The description should say to use the UnsetParent() method instead.

**Comment by FirstGearGames** [comment]
Resolved in 4.3.9.

Now properly unsets.
