### ISSUE TITLE
Disabled nested NetworkObjects are automatically spawned and enabled when the parent is spawned (FN 2.3.0)

### ISSUE THREAD

**Issue by Pegorari** [FirstGearGames/FishNet#73]
Would be nice if the intentionally disabled objects are spawned and activated only after their Spawn call

**Comment by FirstGearGames** [comment]
As in ones you deactivate after instantiating, or ones deactivated on the prefab? The latter can be done very easily.

**Comment by FirstGearGames** [comment]
Added in 2.3.8.
You will be able to activate or deactivate NetworkObjects before network spawning them and those changes will carry over.

**Comment by Pegorari** [comment]
Thank you. I love this project. I wish you success!
