### ISSUE TITLE
NetworkObject GraphicalObject not interpolated correctly for proxy owned objects

### ISSUE THREAD

**Issue by SimEof** [FirstGearGames/FishNet#734]
General
Unity version: 2022.3.21f1
Fish-Networking version: 4.3.8R PRO
Discord link: https://discordapp.com/channels/424284635074134018/1034477094731784302/1265321796102525024

Description
Since upgrading from 4.3.5R PRO, npc controlled by the server lost their interpolation. Now their movement is visibly updated on ticks, where in 4.3.5 they moved smoothly. None of the network behaviours settings were changed when updating the FishNet version.

Replication
	Create a basic scene with a NetworkManager that has the same settings as the NetworkManager in the screenshot;
	Add a networkObject with shown components and their settings;
	Create a simple script that moves this object linearly(here we move this object only on server side in OnPostTick);
	Now when playing this test scene with client and host/server, on host its moving smoothly, while on the client side its stuttering.

Expected behavior
Npcs without local ownership are interpoalted and move smoothly on client side.

Screenshots
![Screenshot 2024-07-23 174702](https://github.com/user-attachments/assets/5955f1cc-6bfb-4dcb-9528-637e27655850)

![Screenshot 2024-07-23 174538](https://github.com/user-attachments/assets/019363fc-73d1-40f6-9ad0-fc3225785168)

**Comment by FirstGearGames** [comment]
Reviewing this.

**Comment by FirstGearGames** [comment]
Confirmed bug.

**Comment by FirstGearGames** [comment]
Resolved in 4.4.0
