### ISSUE TITLE
Proxy players for local client stutter/teleport/lag and overall look very delayed

### ISSUE THREAD

**Issue by SimEof** [FirstGearGames/FishNet#735]
General
Unity version: 2022.3.21f1
Fish-Networking version: 4.3.8R PRO
Discord link: https://discordapp.com/channels/424284635074134018/1034477094731784302/1265321796102525024

Description
Since upgrading from 4.3.5R PRO, non locally owned proxy players stutter/teleport/lag and overall look very delayed.

Replication
	Create a basic scene with a NetworkManager that has the same settings as the NetworkManager in the screenshot;
	Create a basic player prefab with same components as shown in the Player object screenshot with same settings(also basic controls and movement);
	Add a capsule mesh to Graphical object;
	In play mode with host and client or server and two clients one player should see another proxy player behaving as explained in the description.

Expected behavior
Proxy players move smoothly

Screenshots
![Screenshot 2024-07-23 174602](https://github.com/user-attachments/assets/57bf5892-dd55-4c32-ac15-c4f4a8bd672a)

![Screenshot 2024-07-23 174702](https://github.com/user-attachments/assets/5df4be63-e52a-47a9-9208-2cefffcdc999)

**Comment by FirstGearGames** [comment]
Your object might be configured wrong. See this...
https://fish-networking.gitbook.io/docs/manual/guides/prediction/version-2/configuring-networkobject#state-forwarding

**Comment by SimEof** [comment]
I will test some time later and report back

**Comment by SimEof** [comment]
Disabling the State Forwarding negates these issues for proxy Players, but we did intend to use it. I dont see where we could have incorrect configuration. Our movement logic is written following the example code in Prediction V2 guide

**Comment by SimEof** [comment]
I also updated the screenshots as I sent an irrelevant screenshot previously

**Comment by FirstGearGames** [comment]
Re-examining your feedback and content provided here this does not seem like it is a bug, at least that is my initial impressions. I'm going to close this out and troubleshoot this with you on Discord.
