### ISSUE TITLE
TimeManager TickToLocalTick and LocalTickToTick uint overflow bug

### ISSUE THREAD

**Issue by SimEof** [FirstGearGames/FishNet#736]
General
Unity version: 2022.3.21f1
Fish-Networking version: 4.3.8R PRO
Discord link: https://discordapp.com/channels/424284635074134018/1034477094731784302/1257643529841152162

Description
TimeManager TickToLocalTick and LocalTickToTick has a uint overflow bug when passing future ticks

Replication
	Use any of demo scenes;
	Create and add new test script on player network object;
	In OnStartNetwork event Try to use TickToLocalTick(TimeManager.Tick + 1) or LocalTickToTick(TimeManager.LocalTick + 1)
	The calculated difference in these methods are never negative and 0 is returned

Expected behavior
Future tick should be returned or the should be informed with either exception or in methods description

Screenshots
![image](https://github.com/user-attachments/assets/50c3f12e-b102-4c50-8497-bcf7ed5111b1)

**Comment by FirstGearGames** [comment]
Shouldn't be possible to overflow given the checks but it would return current localTick rather than localTick + correct-difference.
I meant to make this change in 4.3.8 but didn't get around to it, it's even in my todo. I'll make sure it's added in right now.

**Comment by SimEof** [comment]
I understand. Thanks

**Comment by FirstGearGames** [comment]
Methods can now return future ticks in 4.4.0.
