### ISSUE TITLE
SceneID error on FN 2.2.6hf0

### ISSUE THREAD

**Issue by Toshito90** [FirstGearGames/FishNet#75]
Hello, I am having trouble to move my character to another scene after I spawn it (Instantiate, then Spawn), it will always give me this error:

"SceneId of 12428356674046895244 not found in SceneObjects. This may occur if your scene differs between client and server, if client does not have the scene loaded, or if networked scene objects do not have a SceneCondition. See ObserverManager in the documentation for more on conditions."

Tried to rebuild the Scene IDs, remake the prefabs object and reapply to the network manager GameObject, also I tried to remove the observers component on the network manager and also on the player's gameobject aswell and re-add to each one, re-applied the Scene Condition object to that Observers manager component, etc.. Always giving me the same error at the end.

The function I use to teleport my character is this one:

```
[Server]
void Server_LoadScene(string sceneName)
{
	SceneLoadData sld;
	SceneLookupData lookup;
	if (sceneStack)
	{
		if (stackedSceneHandle != 0)
			lookup = new SceneLookupData(stackedSceneHandle);
		else
			lookup = new SceneLookupData(sceneName);

		sld = new SceneLoadData(lookup);
		sld.Options.AllowStacking = true;
	}
	else
	{
		sld = new SceneLoadData(sceneName);
		sld.Options.AllowStacking = false;
	}

	sld.MovedNetworkObjects = new NetworkObject[] { currentConnection.FirstObject, NetworkObject };
	sld.ReplaceScenes = ReplaceOption.None;
	InstanceFinder.SceneManager.LoadConnectionScenes(currentConnection, sld);
}
```

And to spawn I use the same function on the original PlayerSpawn script that comes with FN.

For the teleport script I will give you the full one, as you might need to reproduce the issue.

[Warp.zip](https://github.com/FirstGearGames/FishNet/files/9126847/Warp.zip)

And this is my screenshot

![Screenshot 2022-07-17 013917](https://user-images.githubusercontent.com/22123842/179379267-791b5c48-6623-467d-8596-70946e99b5e5.jpg)

**Comment by FirstGearGames** [comment]
Resolved in 2.2.7, and 2.3.1.
