### ISSUE TITLE
Getting error: "Multipass connectionId could not be found for transportIndex 1, transportId of 0." when connecting using custom authenticator on Multipass with Bayou.

### ISSUE THREAD

**Issue by gabe39** [FirstGearGames/FishNet#751]
**General**
Unity version: 2022.3.21f1
Fish-Networking version: 4.3.8R
Discord link: https://discord.com/channels/424284635074134018/1034477094731784302/1270783262641492030

**Description**
I'm currently working on a custom authenticator and everytime when `OnAuthenticationResult` is invoked and is false I get this error in the console on the server:
```
Multipass connectionId could not be found for transportIndex 1, transportId of 0.
UnityEngine.Debug:LogError (object)
FishNet.Managing.Logging.LevelLoggingConfiguration:LogError (string) (at Assets/Other Assets/FishNet/Runtime/Managing/Logging/LevelLoggingConfiguration.cs:129)
FishNet.Managing.NetworkManager:InternalLogError (string) (at Assets/Other Assets/FishNet/Runtime/Managing/NetworkManager.Logging.cs:83)
FishNet.Transporting.Multipass.Multipass:Multipass_OnRemoteConnectionState (FishNet.Transporting.RemoteConnectionStateArgs) (at Assets/Other Assets/FishNet/Runtime/Transporting/Transports/Multipass/Multipass.cs:396)
FishNet.Transporting.Bayou.Bayou:HandleRemoteConnectionState (FishNet.Transporting.RemoteConnectionStateArgs) (at Assets/Other Assets/FishNet/Plugins/Bayou/Bayou.cs:160)
FishNet.Transporting.Bayou.Server.ServerSocket:StopConnection (int,bool) (at Assets/Other Assets/FishNet/Plugins/Bayou/Core/ServerSocket.cs:223)
FishNet.Transporting.Bayou.Server.ServerSocket:_server_onDisconnect (int) (at Assets/Other Assets/FishNet/Plugins/Bayou/Core/ServerSocket.cs:154)
JamesFrowen.SimpleWeb.SimpleWebServer:ProcessMessageQueue () (at Assets/Other Assets/FishNet/Plugins/Bayou/SimpleWebTransport/Server/SimpleWebServer.cs:109)
FishNet.Transporting.Bayou.Bayou:IterateIncoming (bool) (at Assets/Other Assets/FishNet/Plugins/Bayou/Bayou.cs:172)
FishNet.Transporting.Multipass.Multipass:IterateIncoming (bool) (at Assets/Other Assets/FishNet/Runtime/Transporting/Transports/Multipass/Multipass.cs:427)
FishNet.Managing.Transporting.TransportManager:IterateIncoming (bool) (at Assets/Other Assets/FishNet/Runtime/Managing/Transporting/TransportManager.cs:705)
FishNet.Managing.Timing.TimeManager:TryIterateData (bool) (at Assets/Other Assets/FishNet/Runtime/Managing/Timing/TimeManager.cs:1017)
FishNet.Managing.Timing.TimeManager:IncreaseTick () (at Assets/Other Assets/FishNet/Runtime/Managing/Timing/TimeManager.cs:675)
FishNet.Managing.Timing.TimeManager:<TickUpdate>g__MethodLogic|100_0 () (at Assets/Other Assets/FishNet/Runtime/Managing/Timing/TimeManager.cs:346)
FishNet.Managing.Timing.TimeManager:TickUpdate () (at Assets/Other Assets/FishNet/Runtime/Managing/Timing/TimeManager.cs:336)
FishNet.Transporting.NetworkReaderLoop:Update () (at Assets/Other Assets/FishNet/Runtime/Transporting/NetworkReaderLoop.cs:28)
```
The error happens only when I connect on Bayou and `OnAuthenticationResult` is false.

Here is the code that I used:
https://gist.github.com/gabe39/935d27ee248846237a95add0d5d8d994
**Replication**
1) Create a scene with a basic ui for hosting/connecting
2) Use the _CustomAuthenticator_ script
3) Set `useBayou` to true on _NetworkPortTest_
4) Set `isInGame` to true on _HostConnectionManager_
5) Run and test

**Expected behavior**
It should only show that the client has disconnected in the console without showing the error.

**Screenshots**
### **1)** 
![image](https://github.com/user-attachments/assets/69340468-1752-4269-97af-7ba2923f6c56)
### **2)**
![image](https://github.com/user-attachments/assets/a5087322-9723-47f1-b457-c243aeb2c98e)
### **3)**
![image](https://github.com/user-attachments/assets/47a5f652-a859-4640-91a5-8e43f4ac3310)
### **4)**
![image](https://github.com/user-attachments/assets/50a6ca4e-daa7-412a-83cd-b0a71c003bf5)

Does this happen because I'm doing something wrong or because this is a bug ?

**Comment by FirstGearGames** [comment]
Can you please export the test code as a package(then zip) and upload.

https://fish-networking.gitbook.io/docs/manual/guides/creating-bug-reports#guidelines

**Comment by gabe39** [comment]
Sorry, but I forgot to mention that I'm using ParrelSync for testing. Not sure if it helps, but I mentioned it in case of anything.
Also, I would like to know if this affects me in any way or I can continue working on my project and just ignore the error for now.
Here's the zip file with the package:
[TestCode.zip](https://github.com/user-attachments/files/16620902/TestCode.zip)

**Comment by gabe39** [comment]
Any news on this ?

**Comment by FirstGearGames** [comment]
If nothing is breaking probably not hurting anything. I've not had a chance to review this issue specifically yet though, sorry. Hopefully soon.

**Comment by gabe39** [comment]
Thanks for reassuring! 
And don't worry, it's not a hurry, for me at least. :D 
I already decided to just ignore the error and mind my own business.

**Comment by FirstGearGames** [comment]
After looking into it the bug is indeed harmless. It's isolated to Bayou so will be resolved in a Bayou update.

To fix find the lines inside Bayou ServerSocket.cs
```cs
            else
            {
                _server.KickClient(connectionId);
                _clients.Remove(connectionId);
                base.Transport.HandleRemoteConnectionState(new RemoteConnectionStateArgs(RemoteConnectionState.Stopped, connectionId, base.Transport.Index));
            }
```

and replace with this...
```cs
            else
            {
                _server.KickClient(connectionId);
                
                //Wait for the disconnect callback instead.
                //_clients.Remove(connectionId);
                //base.Transport.HandleRemoteConnectionState(new RemoteConnectionStateArgs(RemoteConnectionState.Stopped, connectionId, base.Transport.Index));
            }
```

The issue arises from the manual callback when you call stop connection, and then the automatic callback when the socket confirms the disconnect. The connection is disconnected before the first callback so it does not exist on the second, hence the error.

**Comment by FirstGearGames** [comment]
Looks like a few other changes were needed as well. Replace these methods with the content below...
```cs

        private void _server_onDisconnect(int connectionId)
        {
            ConnectionStoppedOnSocket(connectionId);
        }

        private void _server_onError(int connectionId, Exception arg2)
        {
            ConnectionStoppedOnSocket(connectionId);
        }
        
        internal bool StopConnection(int connectionId, bool immediately)
        {
            if (_server == null || base.GetConnectionState() != LocalConnectionState.Started)
                return false;

            //Don't disconnect immediately, wait until next command iteration.
            if (!immediately)
                _disconnectingNext.Add(connectionId);
            //Disconnect immediately.
            else
                _server.KickClient(connectionId);

            return true;
        }
```

Add this one...
```cs
        private void ConnectionStoppedOnSocket(int connectionId) 
        {
            if (_clients.Remove(connectionId))
                base.Transport.HandleRemoteConnectionState(new RemoteConnectionStateArgs(RemoteConnectionState.Stopped, connectionId, base.Transport.Index));
        }
```
