### ISSUE TITLE
SnycType not syncing to clients/Not initializing.

### ISSUE THREAD

**Issue by Sonicboomcolt** [FirstGearGames/FishNet#753]
**General**
Unity version: Unity 6
Fish-Networking version: 4.4.1 Pro (Also happens on 4.3.8)
Discord link: https://discord.com/channels/424284635074134018/1034477094731784302/1272067964753150003

**Description**
The player is spawned and then after the server has init the object, we spawn the weapon object and parent it to the spawned player. So far everything works perfectly but the syncVars is not showing to the clients.

**Replication**
1. Host game
2. Connect with client
3. Have an object spawn nested via server (an object with syncVars).
4. Change the syncVars over the server only (Not using RPCs as all server-side).

**Expected behavior**
SyncVars values should update correctly on nested objects for the observers.

**Screenshots**
Hierarchy View (Weapon is the nested NOB):
![image](https://github.com/user-attachments/assets/10edc1db-d9ce-4608-af23-38a5a03ee365)

Server/Host:
![image](https://github.com/user-attachments/assets/37bf779c-2693-451c-9684-e097eae72545)
Client:
![image](https://github.com/user-attachments/assets/b025c09a-03e7-44a5-ae2d-8f99506825ea)

Network Object Script:
Server/Host:
![image](https://github.com/user-attachments/assets/bb4359b4-171f-4570-a298-713c8798266a)
Client:
![image](https://github.com/user-attachments/assets/f13d0eb2-d024-4e93-b0e5-cced2915e414)

**Comment by Sonicboomcolt** [comment]
Did some more testing in 4.3.8 and 4.4.1. After spawning the weapon, the SyncVars never get set as `Is Initialized`.

Here is the spawning code. It pulls from a prefab on the player within a prefab folder.
It seems nested or not, SyncTypes just don't want to initialize

The code that sets up the players inventories:
```cs
       [Server]
        public virtual IEnumerator WaitForServerInitialized(Pawn newPawn, Controller controller) //This is needed as we can't give ownership to objects that are not init on the network yet - COLT.
        {
            // Wait until the server has initialized the pawn.
            yield return new WaitUntil(() => newPawn.IsServerInitialized);

            newPawn.Possess(controller); //Give ownership to client.
            AddDefaultInventory(newPawn); //Give them weapons.
        }
```

How the inventory setup gets called:
```cs
        [Server]
        public virtual void AddDefaultInventory(Pawn aPawn)
        {
            if(aPawn.GetInventoryManager() != null)
            {
                aPawn.GetInventoryManager().SetupInventoryWithDefaults();
            }
        }
```

Spawning of the weapon over the server:
```cs
        /// <summary>
        /// Give this pawn their default items. Only items that don't exist yet in play.
        /// </summary>
        [Server]
        public virtual void SetupInventoryWithDefaults()
        {
            //If we don't have any default items, don't do anything.
            if(defaultInventory.Count == 0)
            {
                Debug.LogWarning($"InvManager {gameObject.name} does not have defaults added");
                return;
            }

            foreach (var item in defaultInventory)
            {
                //Make sure we don't already have the items. - Sanity check.
                if(FindInventoryType(item) == null)
                {
                    //Copy the item.
                    Inventory copyOfItem = Instantiate(item, GetPawn().transform);

                    //Spawn it over the network.
                    ServerManager.Spawn(copyOfItem.gameObject);

                    //Give it to this pawn.
                    copyOfItem.GiveTo(GetPawn());
                }
            }
        }
```

**Comment by NaolShow** [comment]
That might be the issue that I've encountered, sync vars are not synced for scene networked objects. But working fine on dynamically spawned ones.

**Comment by Sonicboomcolt** [comment]
I sadly have it the opposite. My scene objects are fine. But dynamic objects don't want to sync.

**Comment by Sonicboomcolt** [comment]
Alright, it seems it could be due to the inheritance, I have all of my network classes inheriting a base class with stuff in it.
So it looks like this 

BaseClass -> Inventory -> Weapon -> WeaponTesting
BaseClass is a NetworkBehavior base.

Any ideas on how to solve this issue and why SyncTypes don't like the way I'm doing this???

**Comment by Sonicboomcolt** [comment]
FIXED. Don't have SyncTypes in a sterilized class in a class. it does not like it.
