### ISSUE TITLE
Hashgrid issues with NetworkTransform

### ISSUE THREAD

**Issue by TrentSterling** [FirstGearGames/FishNet#758]
**General**
Unity version: 
2023.2.0f1
Fish-Networking version: 
4.3.8R
Discord link:
https://discord.com/channels/424284635074134018/1034477094731784302/1275102354571788350
** Above, post a link from our Discord where you troubleshot the issue (on Discord click the three dots next to the message, then Copy Message Link). Issue may be closed out if this is not included.

**Description**
Hashgrid condition eventually causes NetworkTransform to freak out.

**Replication**
New Project.
Install Fishnet from asset store/packagemanager.
Install Parallelsync.
Open the Hashgrid test demo scene. Run as server.
Open 2nd client, run as client.
Wait a minute. In just a little bit of time, errors show up, and things get weird.

**Expected behavior**
We expect the scene to just keep running, and keep showing different grid areas. Instead, we get NetworkTransform errors, and eventually the sync breaks down.

**Screenshots**

![Unity_MDT3JJYRlC](https://github.com/user-attachments/assets/ea3bb454-8252-4d9c-91d8-574ff12393d1)

**Comment by FirstGearGames** [comment]
It looks like the server needs to run as Host for the error to occurs on the second client. I do see in your screenshot that is the case, just updating to note this.

**Comment by FirstGearGames** [comment]
I was able to simplify the test process a bit. I changed the packing type to unpacked for position to make sure it wasn't a compression/incorrect packing flag.

Removed the observermanager.

Started clientHost, started client, all is fine.
Stop clientHost(not server), start clientHost and the positions are very wrong.

**Comment by TrentSterling** [comment]
Ah you're right, I should've mentioned cleint-host! I actually plan to use EOS in the end, so I am always using a client-host. 

Glad to see you are able to repro!

**Comment by FirstGearGames** [comment]
This appears to be resolved but there's some other unrelated quirks slowing down the release. Version 4.4.5 was planned for today but looks like perhaps tomorrow instead since I'm out of time to investigate.
