### ISSUE TITLE
PredictedObject smoothing is wonky at 60Hz.

### ISSUE THREAD

**Issue by FirstGearGames** [FirstGearGames/FishNet#77]
Movement is not smooth under certain conditions.
Replicate in CharacterControllerPrediction example.

- Set tick rate to 10.
- Enable VSync in the game window.
- Set monitor refresh rate to 60Hz.
- Start as host and move around.

Jitter can also be seen at higher tick rates with 60Hz.

**Comment by FGGTesting** [comment]
[PredictedObject_20220812.zip](https://github.com/FirstGearGames/FishNet/files/9324711/PredictedObject_20220812.zip)
Patch anyone is welcome to try.

**Comment by FirstGearGames** [comment]
Patch anyone is welcome to try.
[PredictedObject_20220812.zip](https://github.com/FirstGearGames/FishNet/files/9324715/PredictedObject_20220812.zip)

**Comment by FirstGearGames** [comment]
Resolved in 2.3.14.
