### ISSUE TITLE
Prediction always uses Spectator Smoothing settings, even for Owner

### ISSUE THREAD

**Issue by gusky651** [FirstGearGames/FishNet#770]
**General**
Unity version: 2022.3.42f1
Fish-Networking version: 4.4.5
Discord link: https://discord.com/channels/424284635074134018/1034477094731784302/1282787187561070633.

**Description**
In the NetworkObject Prediction section, when Prediction is enabled, the "Owner Smoothed Properties" are not used. Instead the Smoothed Properties are also used for the owner.

**Replication**
1. Enable Prediction with State Forwarding on Network Object
2. Change Owner Smoothed properties 

**Expected behavior**
The Owner Smoothed properties are used for prediction when client is Owner

**Actual behavior**
The Spectator Smoothed properties are used for prediction when client is Owner

**Screenshots**
https://github.com/user-attachments/assets/4245b095-6768-46ea-9123-55d75110542e

**Note**
When debugging I noticed line 623 of `ChildTransformTickSmoother` is where it's decided which Smoothed Properties setting to use

`TransformPropertiesFlag smoothedProperties = (_ownerOnPretick) ? _ownerSmoothedProperties : _spectatorSmoothedProperties;`

however `_ownerOnPretick` isn't being set anywhere, so it always has the default value of `false`.

**Comment by FirstGearGames** [comment]
Resolved in 4.4.6
