### ISSUE TITLE
Host client stops observing scene when new client joins new stacked scene

### ISSUE THREAD

**Issue by maxkratt** [FirstGearGames/FishNet#772]
**General**
Unity version: 6000.0.15f1
Fish-Networking version: 4.4.5
Discord link: https://discord.com/channels/424284635074134018/1282870155831021710/1283408287756456017

**Description**
If the host is loaded into a stacked scene and then a new client is loaded into a new instance of that stacked scene then the host stops observing objects in their scene. This only happens to the host client.

**Replication**
1. Import example
2. Add both example scenes to build profile
3. Make a build or open a cloned editor
4. Run one as a client host and the other as a client
5. The client host will start in the scene seeing a cube and their player capsule
6. When the solo client joins the host will incorrectly stop observing those objects

**Expected behavior**
The host shouldn't be affected by another client joining a different scene instance.

**Example File**
[SimpleStackedScenes.zip](https://github.com/user-attachments/files/16963882/SimpleStackedScenes.zip)

**Comment by FirstGearGames** [comment]
The code doesn't compile.
![image](https://github.com/user-attachments/assets/c061457a-ab6e-491e-b54c-2a5c1caaf8d2)

**Comment by FirstGearGames** [comment]
Replicated.

**Comment by maxkratt** [comment]
> The code doesn't compile. ![image](https://private-user-images.githubusercontent.com/27169134/369150862-c061457a-ab6e-491e-b54c-2a5c1caaf8d2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3Nzg4MTMsIm5iZiI6MTcyNjc3ODUxMywicGF0aCI6Ii8yNzE2OTEzNC8zNjkxNTA4NjItYzA2MTQ1N2EtYWI2ZS00OTFlLWI1NGMtMmE1YzFjYWFmOGQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE5VDIwNDE1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY5MWY5MjYxMmVjMzEzZDM2N2QyNWYwMmVkZjc0ZTk1ZDg2NjE1MTZkOGY2N2Y5ZmI0N2YzMjc1NDM3ODE1YzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.0C2BQzfLDTWDQZVS6Y2VAXqiNUDb-3PX9uRjopHGp0I)
> 
> I'll try without this method.

Whoops, sorry about that. I must have forgotten to save that file when exporting or something

**Comment by FirstGearGames** [comment]
Resolved in 4.4.6
