### ISSUE TITLE
PrefabId 65535 is out of range when spawning nested prefab network objects

### ISSUE THREAD

**Issue by Rob-Kilgore** [FirstGearGames/FishNet#778]
**General**
Unity version: 2022.3.30f1
Fish-Networking version: 4.4.5 Pro
Discord link: https://discord.com/channels/424284635074134018/1279073515139502112/1279073515139502112
(Discord Username is markclark, please let me know if I can provide further info)

**Description**
When spawning a prefab with nested network objects, I get 2 exceptions with messages "PrefabId 65535 is out of range." and "NullReferenceException: Object reference not set to an instance of an object".

I have reproduced this with a function as simple as the following in OnStartServer on a script in my online scene where toSpawn is my nested network object:

```
public override void OnStartServer()
{
    NetworkObject go = Instantiate(toSpawn);
    Spawn(go);
}
```

If I switch the prefab to a flat Game Object (No nested network objects), then there is no exception

**Replication**
1. Create a Game object with a network object script on it
2. Add a child Game Object with another network object script on it
3. Save the Game Object from (1) as a Prefab
4. Create a script on a scene object to spawn the network object from (3) in OnStartServer 
5. Run the game and load the scene

**Expected behavior**
The object should spawn without error

**Actual behavior**
The object causes 2 exceptions on spawn

**Screenshots**
![image](https://github.com/user-attachments/assets/3f7e9854-32a6-4bb6-b4af-058d75cf3553)
[stacktrace2.txt](https://github.com/user-attachments/files/17068482/stacktrace2.txt)
[stacktrace1.txt](https://github.com/user-attachments/files/17068483/stacktrace1.txt)

**Comment by FirstGearGames** [comment]
I was not able to reproduce this. Please provide a project doing so and this will be looked into. https://fish-networking.gitbook.io/docs/manual/guides/creating-bug-reports#guidelines

**Comment by Rob-Kilgore** [comment]
[PrefabBugReport.zip](https://github.com/user-attachments/files/17078359/PrefabBugReport.zip)

**Comment by Eonasdan** [comment]
This is happening to me too, with this same prefab ID.

I'm just using the NetworkManager and dropping a prefab on to the "Player Prefab" field.

The `po` here has a single prefab with an ID of 0. There are a couple of calls to this where the code is looking for id of 0 and that works just fine. Then there's a call looking for ID 65535, which doesn't exist.

```cs
 PrefabObjects po = NetworkManager.GetPrefabObjects<PrefabObjects>(nob.SpawnableCollectionId, false);
                tpf = nob.GetTransformChanges(po.GetObject(asServer: true, nob.PrefabId)
```

 I also tried creating my own spawnables SO, but that didn't resolve it. Strangely, I had it working with a different spawn prefab.

**Comment by Eonasdan** [comment]
@Rob-Kilgore I think I figured it out. I had a prefab like this `RootObject`. I added some debugging to the FishNet code where it was breaking and discovered that 65535 is just `public const int UNSET_PREFABID_VALUE = ushort.MaxValue;` when the `PrefabId` wasn't set. I logged the name of the game objects to find that the problem was on `Child`. Once I removed the `NetworkObject` component from `Child` (see `Child2`). It looks like the problem went away.

```mermaid
classDiagram
    RootObject <|-- Child
    RootObject2 <|-- Child2
    class RootObject{
      NetworkObject
    }
    class Child{
      NetworkObject
      NetworkAnimator
      NetworkTransform
    }
    class RootObject2{
      NetworkObject
    }
    class Child2{
      NetworkAnimator
      NetworkTransform
    }
```

**Comment by FREEZX** [comment]
This prevents me from upgrading to the latest version, breaks my game.

**Comment by FirstGearGames** [comment]
> Here's a unitypackage with what I used to reproduce this issue. The project had only these files & a stock FishNet installation. Note the difference between setting the toSpawn parameter of the Object Spawner component in OnlineScene to NestedPrefab or NormalPrefab. [PrefabBugReport.zip](https://github.com/user-attachments/files/17078359/PrefabBugReport.zip)

This does not seem to replicate. I assume you open two editors, hit start on each? No errors though.

**Comment by FirstGearGames** [comment]
Max supplied me with a repo project and the issue has been isolated and resolved.

Find method `protected void WriteChangedTransformProperties(NetworkObject nob, bool sceneObject, Writer headerWriter)`

Replace this block...
```cs
            if (sceneObject)
            {
                tpf = nob.GetTransformChanges(nob.SerializedTransformProperties);
            }
            else
            {
                PrefabObjects po = NetworkManager.GetPrefabObjects<PrefabObjects>(nob.SpawnableCollectionId, false);
                tpf = nob.GetTransformChanges(po.GetObject(asServer: true, nob.PrefabId).gameObject);
            }
```

With this...
```cs
            if (sceneObject || nob.InitializedParentNetworkBehaviour != null)
            {
                tpf = nob.GetTransformChanges(nob.SerializedTransformProperties);
            }
            else
            {
                //This should not be possible when spawning non-nested.
                if (nob.PrefabId == NetworkObject.UNSET_PREFABID_VALUE)
                {
                    NetworkManager.LogWarning($"NetworkObject {nob.ToString()} unexpectedly has an unset PrefabId while it's not nested. Please report this warning.");
                    tpf = TransformPropertiesFlag.Everything;
                }
                else
                {
                    PrefabObjects po = NetworkManager.GetPrefabObjects<PrefabObjects>(nob.SpawnableCollectionId, false);
                    tpf = nob.GetTransformChanges(po.GetObject(asServer: true, nob.PrefabId).gameObject);
                }
            }
```

**Comment by Rob-Kilgore** [comment]
This seems to have fixed it for me
