### ISSUE TITLE
The `DirtAll` function of `SyncVar` doesn't work correctly with `primitive types`

### ISSUE THREAD

**Issue by MikeMuorte** [FirstGearGames/FishNet#779]
**General**
Unity version: 2022.3.5f1
Fish-Networking version: 4.4.6R.Pro
Discord link: https://discord.com/channels/424284635074134018/1034477094731784302/1287160189753229378

**Description**
When using DirtAll on a SyncVar with a primitive data type to force a call to the OnChange callback when the value hasn't changed, the callback only executes on the server side but never on the client side.

**Replication**
1. Steps to reproduce the behavior: 
2. Create a `NetworkBehavior` with a `SyncVar<int>` variable.
3. Create a suitable `IntChange` method to subscribe it to the `OnChange` callback of `SyncVar<int>` within the `OnEnable` method.
4. In the `OnStartServer` method of the `NetworkBehavior`, add the call to the `DirtAll` method of `SyncVar<int>`.
5. In the `IntChange` method subscribed to the `OnChange` callback, add a simple message with `Debug.Log("Value Changed")`.
6. Create a new prefab and add the component created.
7. Assign the created prefab to the `PlayerSpawner` of the `NetworkManager` in a basic FishNet scene.
8. Start two instances of the game (server and client) and check the Log messages.
9. The "Value Changed" log message only appears in the game instance acting as the server.

**Expected behavior**
The "Value Changed" log message should appear in both game instances, client and server, whenever the `DirtAll` method is used, even if the value of the `SyncVar` hasn't changed.

**Comment by FirstGearGames** [comment]
I was not able to reproduce using the following. Please review the attachment and let me know what might be different. Modify and re-upload as well with changes please.
[SV_Dirty All.zip](https://github.com/user-attachments/files/17151923/SV_Dirty.All.zip)

**Comment by FirstGearGames** [comment]
Ahhh. Might be a bug in the SyncTypes before the rework. I did find another
small unrelated issue looking into this though, so there's that.
