### ISSUE TITLE
PredictedObject for RigidBody

### ISSUE THREAD

**Issue by ymkim50** [FirstGearGames/FishNet#78]
Hi, there,

PredictedObject has a problem on client.
I toggle kinematic in rigidbody, which is not working client.

It seems to RigidbodyState must contain a variable for kinematic.
A reference code is 

```
public struct RigidbodyState
{
    ...
    public bool isKinematic;
}
```

```
 private void ResetRigidbodyToData()
{
   ...
    _rigidbody.isKinematic = _receivedRigidbodyState.Value.isKinematic;
    _lastKinematic = _rigidbody.isKinematic;
}
```
I think this should be added, so please review it.

**Comment by FirstGearGames** [comment]
I can add that in.

**Comment by FirstGearGames** [comment]
Added in 2.3.11
