### ISSUE TITLE
SyncVar OnChange callback gives the same value for 'prev' and 'next' on clients

### ISSUE THREAD

**Issue by Tyex** [FirstGearGames/FishNet#780]
**General**
Unity version: Unity 6000.0.18f1
Fish-Networking version: 4.4.6R
Discord link: https://discord.com/channels/424284635074134018/1034477094731784302/1287734649766023230

**Description**
The clients receive the same value for 'prev' and 'next' of a SyncVar OnChange callback.

**Replication**
1. Add this Test.cs script to a GameObject in a scene:
```C#
using FishNet.Object;
using FishNet.Object.Synchronizing;
using UnityEngine;

public class Test : NetworkBehaviour {

    private readonly SyncVar<int> _syncVar = new SyncVar<int>();

    private void Awake() {
        _syncVar.OnChange += OnSyncVarOnChange;
    }

    private void OnSyncVarOnChange(int prev, int next, bool asServer) {
        Debug.Log($"prev {prev}, next {next}, asServer {asServer}");
    }

    private void Update() {
        if(IsServerStarted) {
            if (Input.anyKeyDown) {
                _syncVar.Value++;
            }
        }
    }
}
```
2. Start as a host in one editor, and as a client in another
3. Press any key on the host to increment the _syncVar

**Expected behavior**
The client should get a different value for 'prev' and 'next'.

**Current behavior**
![SyncVar client bug](https://github.com/user-attachments/assets/45a38888-a1fb-4275-9dbc-6c884f5415fb)

**Comment by FirstGearGames** [comment]
This is part of a recent, intentional change. The old SyncTypes are available if you switch to 'stable' in the menu. Eventually though, the beta SyncTypes will be default.

**Comment by Tyex** [comment]
How will we be able to know the 'prev' value with the beta SyncTypes then?

**Comment by FirstGearGames** [comment]
This change only affects clientHost. Overtime were going to be dropping
some features like this to reduce complex scenarios and code clutter.

There's other reasons as well involving far greater features not yet
discussed.

**Comment by paprik** [comment]
Should we not be developing client hosted games if there are plans to drop/lower their support? The only two things you need a sync var to do is update a value and announce the change properly, if that doesn't work sync vars become useless.

**Comment by PepperyIcecream** [comment]
@FirstGearGames follow up on this one, could you answer to @paprik?
