### ISSUE TITLE
ServerManager Timeout Error

### ISSUE THREAD

**Issue by NickM13** [FirstGearGames/FishNet#782]
# Important
If General, Description, and Replication are not completed the issue will be closed immediately.

**General**
Unity version: 6000.0.20f1
Fish-Networking version: 4.4.6
Discord link: https://discord.com/channels/424284635074134018/1034477094731784302/1288959066613350482
** Above, post a link from our Discord where you troubleshot the issue (on Discord click the three dots next to the message, then Copy Message Link). Issue may be closed out if this is not included.

**Description**
After starting+connecting, stopping, then starting, ServerManager tries to timeout null client from the original server startup.

The reason is because ServerManager._clientList is added and removed to from in Transport_OnRemoteConnectionState, but the list should probably be cleared either on server start or stop.

Fixed for myself by adding:

`public bool StopConnection(bool sendDisconnectMessage)
{
    if (sendDisconnectMessage)
        SendDisconnectMessages(Clients.Values.ToList(), true);
    
    _clientsList.Clear(); // <-- Added this line

    //Return stop connection result.
    return NetworkManager.TransportManager.Transport.StopConnection(true);
}`

**Replication**
1. Call ServerManager.StartConnection() and ClientManager.StartConnection()
2. Call ServerManager.StopConnection(true), do NOT call client stop connection
3. ServerManager.StartConnection()
4. After ServerManager.timeout period has passed, see errors in log.

**Expected behavior**
Timeout shouldn't be trying to kick null client

**Screenshots**
Not applicable

**Comment by FirstGearGames** [comment]
Find this code in ServerManager.cs
```cs
            if (!Started)
            {
                MatchCondition.StoreCollections(NetworkManager);
                //Despawn without synchronizing network objects.
                Objects.DespawnWithoutSynchronization(true);
            }
```
and add clear clients to the end like so. Should resolve the problem.
```cs
            if (!Started)
            {
                MatchCondition.StoreCollections(NetworkManager);
                //Despawn without synchronizing network objects.
                Objects.DespawnWithoutSynchronization(true);
                //Clear all clients.
                Clients.Clear();
            }
```
