### ISSUE TITLE
Network transform client authoratative issue with snap/jitter

### ISSUE THREAD

**Issue by superrafyYT** [FirstGearGames/FishNet#787]
# Important
Otehr clients see the player jittery, or snappy, and sometimes the server aswell.

**General**
Unity version: 2022.3.36f1
Fish-Networking version: 4.4.5 pro, 4.4.7 pro, 4.3.8 pro
Discord link:
https://discord.com/channels/424284635074134018/1291761516114350254

**Description**
sometimes the server does that aswell, even with no packet loss and 1 of ping on an edgegap deployment, im using time manager physics mode with a tickrate of 50, which is supposed to be the reccomended

**Replication**
1. Make client authoratative movement script
2. assign network transform, test out interpolation, as far as i know it didnt change anything
3. see results

**Expected behavior**
The player shouldnt jitter or lag

**Screenshots**
No screens but scrolling down the post there's a video showing the issue

**Comment by FirstGearGames** [comment]
Likely not a bug. Will help you out in priority help.

**Comment by superrafyYT** [comment]
Im gonna re open the issue since i didnt get any support in the discord server for 2 days

**Comment by FirstGearGames** [comment]
Confirmed bug

**Comment by FirstGearGames** [comment]
Resolved in 4.4.8.

Going to look at improving the variance detection in the NT as well to try and pick up on those wonky frame rate clients better.
