### ISSUE TITLE
Nested NetworkObject spawns under scene root on remote client

### ISSUE THREAD

**Issue by bremea** [FirstGearGames/FishNet#788]
Unity version: **2022.3.48f1**
Fish-Networking version: **4.4.7R Pro**
Discord link: https://discord.com/channels/424284635074134018/1291917480633040916/1291917480633040916

**Description**
When spawning in a child NetworkObject with the NetworkBehaviour.Spawn method, the object spawns in on the remote client under the scene root, but spawns normally on the host. Note that I am not using predicted spawning - although some objects in my scene have it, this object does not.

**Code**
```cs
[ServerRpc]
public void EquipItem(ItemData itemData)
{
    GameObject newTool = Instantiate(itemData.prefab, toolsContainer.transform);
    newTool.transform.localPosition = new Vector3(0f, 0f, 0f);
    newTool.transform.localRotation = itemData.prefab.transform.localRotation;

    Spawn(newTool, Owner);

    // ...
}
```

**Replication**
1. Open up a 2nd Unity instance to act as remote client
2. Use code above to spawn the `itemData.prefab` as a child of `toolsContainer.transform`
3. Observe correct spawning behavior on host, but incorrect behavior on remote client.

**Expected behavior**
The spawned NetworkObject should be instantiated as a child of `toolsContainer.transform` on both the host and remote client.

**Video:** https://b.tixte.com/OQdxLhNlKG.mp4

Screenshot of the prefab in question:
![Unity_Owzf6yXwnI](https://github.com/user-attachments/assets/4b425c9f-de4f-4d24-a53d-76c59ea77fa7)

toolsContainer settings:
![Unity_5TYhTeNZgb](https://github.com/user-attachments/assets/8e21e293-7fd5-4232-8989-9b25660146bc)

**Comment by FREEZX** [comment]
This is expected behavior, if you want it to synchronize parents, you need to add a NetworkTransform on the instantiated prefab, and check Synchronize parent (And you will also need to have any NetworkBehaviour on the parent, which you apparently do have in this case.)

**Comment by FirstGearGames** [comment]
It should work on spawn messages if you call `nob.SetParent(otherNob/Nb)` before calling network spawn on it.

**Comment by bremea** [comment]
This solved the issue - I was mistaking the `SetParent` function on NetworkObject for `SetParent` on the Transform. Thanks!
