### ISSUE TITLE
Some NetworkObjects disable at start after upgrading to FishNet 4.5.0

### ISSUE THREAD

**Issue by bremea** [FirstGearGames/FishNet#791]
Unity version: **2022.3.48f1**
Fish-Networking version: **4.5.0R**
Discord link: https://discord.com/channels/424284635074134018/1293374787032191008

**Description**
After upgrading my project from 4.4.7R to 4.5.0R, I noticed some scene NetworkObjects and some spawned NetworkObjects are having their gameobjects set to inactive right after they start. I believe this is caused by the `TryStartDeactivation` method; for whatever reason, these NetworkObjects are starting with NetworkManager set to null, which leads to them being set as inactive.

Screenshot (I added a debug statement on `TryStartDeactivation`):
![image](https://github.com/user-attachments/assets/b3c204c3-258e-4152-838b-4cf3c5bd54b3)

Video of a GameObject disabling after I add a NetworkObject component: https://b.tixte.com/Unity_lgNL2TX87v.mp4

**Replication**
1. Upgrade your project with Scene NetworkObjects from 4.4.7 to 4.5.0
2. Press play
3. Observe some NetworkObjects disabling

**Expected behavior**
These NetworkObjects are enabled at runtime.

**Demo Scene:** https://b.tixte.com/DebugScene.unitypackage

**Comment by FREEZX** [comment]
Issue appears to happen because SetupWithoutSynchronization never actually re-enables child NetworkObjects.

**Comment by FirstGearGames** [comment]
Hey everyone, sorry for this. Looks like a boolean got flipped.

Code in 4.5.0
```cs
        private void OrderNestedByInitializationOrder(List<NetworkObject> cache)
        {
            //After everything is sorted by root only insert children.
            for (int i = 0; i < cache.Count; i++)
            {
                NetworkObject nob = cache[i];
                //Skip root.
                if (!nob.IsNested)
                    continue;
```

The very last bit **should** be
```cs
if (nob.IsNested)
     continue;```

**Comment by FirstGearGames** [comment]
Issue has been found. Notes were incorrectly interpreted which resulted in a boolean check being flipped.

The whole method is going to get reworked but the fix is rather simple in the mean time.

in `ServerObjects.Observers.cs` find these lines...
```cs
        private void OrderNestedByInitializationOrder(List<NetworkObject> cache)
        {
            //After everything is sorted by root only insert children.
            for (int i = 0; i < cache.Count; i++)
            {
                NetworkObject nob = cache[i];
                //Skip root.
                if (!nob.IsNested)
                    continue;
```

Simply flip the boolean check.
```cs
                if (nob.IsNested)
                    continue;
```

**Comment by FirstGearGames** [comment]
Attached rework of the method with added feat of being able to sort nested by initialize order as well, where previously it was only root. Hopefully this works out because it's getting a bit stormy!
[ServerObjects_00.zip](https://github.com/user-attachments/files/17311964/ServerObjects_00.zip)

**Comment by f2069** [comment]
> Attached rework of the method with added feat of being able to sort nested by initialize order as well, where previously it was only root. Hopefully this works out because it's getting a bit stormy! [ServerObjects_00.zip](https://github.com/user-attachments/files/17311964/ServerObjects_00.zip)

I applied the patch and now when I try to load into the scene, I get an error on the server when connecting the client.

```
InvalidOperationException: Collection was modified; enumeration operation may not execute.
System.Collections.Generic.List`1+Enumerator[T].MoveNextRare () (at <801a4b5b9f964ad7bbc7574456774626>:0)
System.Collections.Generic.List`1+Enumerator[T].MoveNext () (at <801a4b5b9f964ad7bbc7574456774626>:0)
FishNet.Managing.Server.ServerObjects.SortRootAndNestedByInitializeOrder (System.Collections.Generic.List`1[T] nobs) (at Assets/FishNet/Runtime/Managing/Server/Object/ServerObjects.Observers.cs:199)
FishNet.Managing.Server.ServerObjects.RetrieveOrderedSpawnedObjects () (at Assets/FishNet/Runtime/Managing/Server/Object/ServerObjects.Observers.cs:168)
FishNet.Managing.Server.ServerObjects.RebuildObservers (FishNet.Connection.NetworkConnection connection, System.Boolean timedOnly) (at Assets/FishNet/Runtime/Managing/Server/Object/ServerObjects.Observers.cs:286)
FishNet.Managing.Scened.SceneManager.RebuildObservers (System.Collections.Generic.IList`1[T] connections) (at Assets/FishNet/Runtime/Managing/Scened/SceneManager.cs:1953)
FishNet.Managing.Scened.SceneManager.AddConnectionToScene (FishNet.Connection.NetworkConnection conn, UnityEngine.SceneManagement.Scene scene) (at Assets/FishNet/Runtime/Managing/Scened/SceneManager.cs:1740)
FishNet.Managing.Scened.SceneManager.OnClientLoadedScenes (FishNet.Connection.NetworkConnection conn, FishNet.Managing.Scened.ClientScenesLoadedBroadcast msg, FishNet.Transporting.Channel channel) (at Assets/FishNet/Runtime/Managing/Scened/SceneManager.cs:460)
FishNet.Broadcast.Helping.ClientBroadcastHandler`1[T].InvokeHandlers (FishNet.Connection.NetworkConnection conn, FishNet.Serializing.PooledReader reader, FishNet.Transporting.Channel channel) (at Assets/FishNet/Runtime/Serializing/Helping/Broadcasts.cs:100)
FishNet.Managing.Server.ServerManager.ParseBroadcast (FishNet.Serializing.PooledReader reader, FishNet.Connection.NetworkConnection conn, FishNet.Transporting.Channel channel) (at Assets/FishNet/Runtime/Managing/Server/ServerManager.Broadcast.cs:85)
FishNet.Managing.Server.ServerManager.ParseReceived (FishNet.Transporting.ServerReceivedDataArgs args) (at Assets/FishNet/Runtime/Managing/Server/ServerManager.cs:798)
FishNet.Managing.Server.ServerManager.Transport_OnServerReceivedData (FishNet.Transporting.ServerReceivedDataArgs args) (at Assets/FishNet/Runtime/Managing/Server/ServerManager.cs:660)
FishNet.Transporting.Tugboat.Tugboat.HandleServerReceivedDataArgs (FishNet.Transporting.ServerReceivedDataArgs receivedDataArgs) (at Assets/FishNet/Runtime/Transporting/Transports/Tugboat/Tugboat.cs:257)
FishNet.Transporting.Tugboat.Server.ServerSocket.IterateIncoming () (at Assets/FishNet/Runtime/Transporting/Transports/Tugboat/Core/ServerSocket.cs:518)
FishNet.Transporting.Tugboat.Tugboat.IterateIncoming (System.Boolean server) (at Assets/FishNet/Runtime/Transporting/Transports/Tugboat/Tugboat.cs:216)
FishNet.Managing.Transporting.TransportManager.IterateIncoming (System.Boolean server) (at Assets/FishNet/Runtime/Managing/Transporting/TransportManager.cs:705)
FishNet.Managing.Timing.TimeManager.TryIterateData (System.Boolean incoming) (at Assets/FishNet/Runtime/Managing/Timing/TimeManager.cs:1063)
FishNet.Managing.Timing.TimeManager.IncreaseTick () (at Assets/FishNet/Runtime/Managing/Timing/TimeManager.cs:708)
FishNet.Managing.Timing.TimeManager.<TickUpdate>g__MethodLogic|100_0 () (at Assets/FishNet/Runtime/Managing/Timing/TimeManager.cs:376)
FishNet.Managing.Timing.TimeManager.TickUpdate () (at Assets/FishNet/Runtime/Managing/Timing/TimeManager.cs:366)
FishNet.Transporting.NetworkReaderLoop.Update () (at Assets/FishNet/Runtime/Transporting/NetworkReaderLoop.cs:28)
```

**Comment by FirstGearGames** [comment]
> > Attached rework of the method with added feat of being able to sort nested by initialize order as well, where previously it was only root. Hopefully this works out because it's getting a bit stormy! [ServerObjects_00.zip](https://github.com/user-attachments/files/17311964/ServerObjects_00.zip)
> 
> I applied the patch and now when I try to load into the scene, I get an error on the server when connecting the client.
> 
> ```
> InvalidOperationException: Collection was modified; enumeration operation may not execute.
> System.Collections.Generic.List`1+Enumerator[T].MoveNextRare () (at <801a4b5b9f964ad7bbc7574456774626>:0)
> System.Collections.Generic.List`1+Enumerator[T].MoveNext () (at <801a4b5b9f964ad7bbc7574456774626>:0)
> FishNet.Managing.Server.ServerObjects.SortRootAndNestedByInitializeOrder (System.Collections.Generic.List`1[T] nobs) (at Assets/FishNet/Runtime/Managing/Server/Object/ServerObjects.Observers.cs:199)
> FishNet.Managing.Server.ServerObjects.RetrieveOrderedSpawnedObjects () (at Assets/FishNet/Runtime/Managing/Server/Object/ServerObjects.Observers.cs:168)
> FishNet.Managing.Server.ServerObjects.RebuildObservers (FishNet.Connection.NetworkConnection connection, System.Boolean timedOnly) (at Assets/FishNet/Runtime/Managing/Server/Object/ServerObjects.Observers.cs:286)
> FishNet.Managing.Scened.SceneManager.RebuildObservers (System.Collections.Generic.IList`1[T] connections) (at Assets/FishNet/Runtime/Managing/Scened/SceneManager.cs:1953)
> FishNet.Managing.Scened.SceneManager.AddConnectionToScene (FishNet.Connection.NetworkConnection conn, UnityEngine.SceneManagement.Scene scene) (at Assets/FishNet/Runtime/Managing/Scened/SceneManager.cs:1740)
> FishNet.Managing.Scened.SceneManager.OnClientLoadedScenes (FishNet.Connection.NetworkConnection conn, FishNet.Managing.Scened.ClientScenesLoadedBroadcast msg, FishNet.Transporting.Channel channel) (at Assets/FishNet/Runtime/Managing/Scened/SceneManager.cs:460)
> FishNet.Broadcast.Helping.ClientBroadcastHandler`1[T].InvokeHandlers (FishNet.Connection.NetworkConnection conn, FishNet.Serializing.PooledReader reader, FishNet.Transporting.Channel channel) (at Assets/FishNet/Runtime/Serializing/Helping/Broadcasts.cs:100)
> FishNet.Managing.Server.ServerManager.ParseBroadcast (FishNet.Serializing.PooledReader reader, FishNet.Connection.NetworkConnection conn, FishNet.Transporting.Channel channel) (at Assets/FishNet/Runtime/Managing/Server/ServerManager.Broadcast.cs:85)
> FishNet.Managing.Server.ServerManager.ParseReceived (FishNet.Transporting.ServerReceivedDataArgs args) (at Assets/FishNet/Runtime/Managing/Server/ServerManager.cs:798)
> FishNet.Managing.Server.ServerManager.Transport_OnServerReceivedData (FishNet.Transporting.ServerReceivedDataArgs args) (at Assets/FishNet/Runtime/Managing/Server/ServerManager.cs:660)
> FishNet.Transporting.Tugboat.Tugboat.HandleServerReceivedDataArgs (FishNet.Transporting.ServerReceivedDataArgs receivedDataArgs) (at Assets/FishNet/Runtime/Transporting/Transports/Tugboat/Tugboat.cs:257)
> FishNet.Transporting.Tugboat.Server.ServerSocket.IterateIncoming () (at Assets/FishNet/Runtime/Transporting/Transports/Tugboat/Core/ServerSocket.cs:518)
> FishNet.Transporting.Tugboat.Tugboat.IterateIncoming (System.Boolean server) (at Assets/FishNet/Runtime/Transporting/Transports/Tugboat/Tugboat.cs:216)
> FishNet.Managing.Transporting.TransportManager.IterateIncoming (System.Boolean server) (at Assets/FishNet/Runtime/Managing/Transporting/TransportManager.cs:705)
> FishNet.Managing.Timing.TimeManager.TryIterateData (System.Boolean incoming) (at Assets/FishNet/Runtime/Managing/Timing/TimeManager.cs:1063)
> FishNet.Managing.Timing.TimeManager.IncreaseTick () (at Assets/FishNet/Runtime/Managing/Timing/TimeManager.cs:708)
> FishNet.Managing.Timing.TimeManager.<TickUpdate>g__MethodLogic|100_0 () (at Assets/FishNet/Runtime/Managing/Timing/TimeManager.cs:376)
> FishNet.Managing.Timing.TimeManager.TickUpdate () (at Assets/FishNet/Runtime/Managing/Timing/TimeManager.cs:366)
> FishNet.Transporting.NetworkReaderLoop.Update () (at Assets/FishNet/Runtime/Transporting/NetworkReaderLoop.cs:28)
> ```

That does look like it could be a bug of the patch, but should be very easy to resolve. In the mean time, if you like, simply revert the patch and make the boolean switch I mentioned above.

**Comment by FirstGearGames** [comment]
> > 

Can I get your Discord please.

**Comment by FirstGearGames** [comment]
> > Attached rework of the method with added feat of being able to sort nested by initialize order as well, where previously it was only root. Hopefully this works out because it's getting a bit stormy! [ServerObjects_00.zip](https://github.com/user-attachments/files/17311964/ServerObjects_00.zip)
> 
> I applied the patch and now when I try to load into the scene, I get an error on the server when connecting the client.
> 
> ```
> InvalidOperationException: Collection was modified; enumeration operation may not execute.
> System.Collections.Generic.List`1+Enumerator[T].MoveNextRare () (at <801a4b5b9f964ad7bbc7574456774626>:0)
> System.Collections.Generic.List`1+Enumerator[T].MoveNext () (at <801a4b5b9f964ad7bbc7574456774626>:0)
> FishNet.Managing.Server.ServerObjects.SortRootAndNestedByInitializeOrder (System.Collections.Generic.List`1[T] nobs) (at Assets/FishNet/Runtime/Managing/Server/Object/ServerObjects.Observers.cs:199)
> FishNet.Managing.Server.ServerObjects.RetrieveOrderedSpawnedObjects () (at Assets/FishNet/Runtime/Managing/Server/Object/ServerObjects.Observers.cs:168)
> FishNet.Managing.Server.ServerObjects.RebuildObservers (FishNet.Connection.NetworkConnection connection, System.Boolean timedOnly) (at Assets/FishNet/Runtime/Managing/Server/Object/ServerObjects.Observers.cs:286)
> FishNet.Managing.Scened.SceneManager.RebuildObservers (System.Collections.Generic.IList`1[T] connections) (at Assets/FishNet/Runtime/Managing/Scened/SceneManager.cs:1953)
> FishNet.Managing.Scened.SceneManager.AddConnectionToScene (FishNet.Connection.NetworkConnection conn, UnityEngine.SceneManagement.Scene scene) (at Assets/FishNet/Runtime/Managing/Scened/SceneManager.cs:1740)
> FishNet.Managing.Scened.SceneManager.OnClientLoadedScenes (FishNet.Connection.NetworkConnection conn, FishNet.Managing.Scened.ClientScenesLoadedBroadcast msg, FishNet.Transporting.Channel channel) (at Assets/FishNet/Runtime/Managing/Scened/SceneManager.cs:460)
> FishNet.Broadcast.Helping.ClientBroadcastHandler`1[T].InvokeHandlers (FishNet.Connection.NetworkConnection conn, FishNet.Serializing.PooledReader reader, FishNet.Transporting.Channel channel) (at Assets/FishNet/Runtime/Serializing/Helping/Broadcasts.cs:100)
> FishNet.Managing.Server.ServerManager.ParseBroadcast (FishNet.Serializing.PooledReader reader, FishNet.Connection.NetworkConnection conn, FishNet.Transporting.Channel channel) (at Assets/FishNet/Runtime/Managing/Server/ServerManager.Broadcast.cs:85)
> FishNet.Managing.Server.ServerManager.ParseReceived (FishNet.Transporting.ServerReceivedDataArgs args) (at Assets/FishNet/Runtime/Managing/Server/ServerManager.cs:798)
> FishNet.Managing.Server.ServerManager.Transport_OnServerReceivedData (FishNet.Transporting.ServerReceivedDataArgs args) (at Assets/FishNet/Runtime/Managing/Server/ServerManager.cs:660)
> FishNet.Transporting.Tugboat.Tugboat.HandleServerReceivedDataArgs (FishNet.Transporting.ServerReceivedDataArgs receivedDataArgs) (at Assets/FishNet/Runtime/Transporting/Transports/Tugboat/Tugboat.cs:257)
> FishNet.Transporting.Tugboat.Server.ServerSocket.IterateIncoming () (at Assets/FishNet/Runtime/Transporting/Transports/Tugboat/Core/ServerSocket.cs:518)
> FishNet.Transporting.Tugboat.Tugboat.IterateIncoming (System.Boolean server) (at Assets/FishNet/Runtime/Transporting/Transports/Tugboat/Tugboat.cs:216)
> FishNet.Managing.Transporting.TransportManager.IterateIncoming (System.Boolean server) (at Assets/FishNet/Runtime/Managing/Transporting/TransportManager.cs:705)
> FishNet.Managing.Timing.TimeManager.TryIterateData (System.Boolean incoming) (at Assets/FishNet/Runtime/Managing/Timing/TimeManager.cs:1063)
> FishNet.Managing.Timing.TimeManager.IncreaseTick () (at Assets/FishNet/Runtime/Managing/Timing/TimeManager.cs:708)
> FishNet.Managing.Timing.TimeManager.<TickUpdate>g__MethodLogic|100_0 () (at Assets/FishNet/Runtime/Managing/Timing/TimeManager.cs:376)
> FishNet.Managing.Timing.TimeManager.TickUpdate () (at Assets/FishNet/Runtime/Managing/Timing/TimeManager.cs:366)
> FishNet.Transporting.NetworkReaderLoop.Update () (at Assets/FishNet/Runtime/Transporting/NetworkReaderLoop.cs:28)
> ```

Can I get your Discord please? Or DM me on Discord.

**Comment by FirstGearGames** [comment]
Disregard.

Issue was this line ```cs
CollectionCaches<NetworkObject>.Store(sceneNobs);
```
In method ```cs
private void SetupSceneObjects(List<NetworkObject> sceneNobs)
```
This was causing the collection to be stored twice. Simply delete the line from the specified method and you should be good.
