### ISSUE TITLE
Server doesn't clear Port when closed in Unity Editor, regularly.

### ISSUE THREAD

**Issue by 0risin** [FirstGearGames/FishNet#8]
Fishnet: 1.1.4
Unity: 2021.2.7f1
Server: Headless, Editor
Client: Editor

**Server doesn't clear Port when closed in Editor, regularly.**

Happened to me 5 Times today and yesterday.
On different devices in different Home Networks. Port is only cleared when exiting the editor.

```cs
[B]Bind exception: System.Net.Sockets.SocketException (0x80004005): Only one usage of each socket address (protocol/network address/port) is normally permitted.

UnityEngine.Debug:Log (object)
LiteNetLib.NetDebug:WriteLogic (LiteNetLib.NetLogLevel,string,object[]) (at Assets/FishNet/Runtime/Transporting/Transports/Tugboat/LiteNetLib/NetDebug.cs:51)
LiteNetLib.NetDebug:WriteError (string,object[]) (at Assets/FishNet/Runtime/Transporting/Transports/Tugboat/LiteNetLib/NetDebug.cs:89)
LiteNetLib.NetSocket:BindSocket (System.Net.Sockets.Socket,System.Net.IPEndPoint,bool,LiteNetLib.IPv6Mode) (at Assets/FishNet/Runtime/Transporting/Transports/Tugboat/LiteNetLib/NetSocket.cs:439)
LiteNetLib.NetSocket:Bind (System.Net.IPAddress,System.Net.IPAddress,int,bool,LiteNetLib.IPv6Mode,bool) (at Assets/FishNet/Runtime/Transporting/Transports/Tugboat/LiteNetLib/NetSocket.cs:248)
LiteNetLib.NetManager:Start (System.Net.IPAddress,System.Net.IPAddress,int) (at Assets/FishNet/Runtime/Transporting/Transports/Tugboat/LiteNetLib/NetManager.cs:1345)
LiteNetLib.NetManager:Start (int) (at Assets/FishNet/Runtime/Transporting/Transports/Tugboat/LiteNetLib/NetManager.cs:1371)
FishNet.Tugboat.Server.ServerSocket:ThreadedSocket (System.Threading.CancellationToken) (at Assets/FishNet/Runtime/Transporting/Transports/Tugboat/Core/ServerSocket.cs:125)
FishNet.Tugboat.Server.ServerSocket:<StartConnection>b__22_0 () (at Assets/FishNet/Runtime/Transporting/Transports/Tugboat/Core/ServerSocket.cs:227)
System.Threading._ThreadPoolWaitCallback:PerformWaitCallback ()
```

**Comment by FirstGearGames** [comment]
Tugboat does close the port after it's de-initialized. I've seen this happen before but only when the socket is suddenly dropped such as if the application freeze.

Was unsuccessful in reproducing with the following:
- rapidly starting/stopping server.
- starting/stopping play mode while server is active.

Able to reproduce by:
- starting server and crashing editor. Port released itself after a moment. This is however normal behavior.

Tugboat hasn't been updated for awhile and I've not had anyone else with this problem as of yet. I suspect something in your project is causing the socket to not de-initialize properly.

You can see if this method is calling: `private void StopSocketOnThread()` in `ServerSocket.cs`.

**Comment by 0risin** [comment]
Ports defeinitely stay unavailable after regular closing in Editor Mode, until the editor is closed on top of that. 

Also using ParrelSync and the clone is the server.

**Comment by FirstGearGames** [comment]
Try what I mentioned above, add debug to the StopSocketOnThread() (within the lock) to see if it's calling.

**Comment by 0risin** [comment]
Port blockage happens more frequently when Server in Editor is in Debug Mode and closed with the Play/Stop button.

**Comment by FirstGearGames** [comment]
I made some changes to tugboat which may help with this problem. Let me know if it still occurs in 1.1.5.Nightly.2

**Comment by FirstGearGames** [comment]
Closed due to inactivity.

**Comment by SoylentGraham** [comment]
Getting this quite frequently on mac.

Port is still bound. (I'm debugging a lot... though not sure that makes much difference, as stopping in rider just un-plays unity)
