### ISSUE TITLE
2.2.7 pro - spawn random Network Object from the defaultPrefabObjects.asset

### ISSUE THREAD

**Issue by EcoEditor** [FirstGearGames/FishNet#80]
The issue is that after upgrading to 2.2.7 pro, running the same scene which was version 2.2.4 pro behaves differently - it spawns different objects.

example on 2.2.4 - windows standalone:
Client and Server - show same spawned prefabs:
The server is connected, once the client is connected the server spawns object "Chair" and gives ownership to client, the server also spawns player prefab "PlayerA". The client can see the "Chair"

example on 2.2.7 - windows standalone:
Client and Server - show different same spawned prefabs:
On the server: 
The server is connected, once the client is connected the server spawns object "Chair" and gives ownership to client, the server also spawns player prefab "PlayerA". The client can see the "Chair"

On the client:
The server is connected, once the client is connected the server spawns object "Cube" and gives ownership to the client, the server also spawns player prefab "PlayerC". The client can see the "Cube"

Errors in the log printed on the server build:

- The last 2 packets to arrive are: 
262
ServerRpc

- The last parsed NetworkObject is Id 2 on gameObject PlayerAvatar(Clone), and NetworkBehaviour PlayerTransformSyncronizer.

- ServerRpc not found for hash 2 on object PlayerAvatar(Clone) [id 2]. Remainder of packet may become corrupt.

-Server received an unhandled PacketId of 262 from connectionId 0. Remaining data has been purged.

Errors on the Client log printed on build:
- endless null reference.

I'd like to upgrade to 2.2.7 to be able to use NetworkObject.IsGlobal

**Comment by FirstGearGames** [comment]
This does occur sometimes but should never be a stopping issue. I responded how to resolve this in chat earlier, it probably went unnoticed. Use the Fish-Networking menu and Refresh Default Prefabs. You can also tick 'Refresh Default Prefabs' on the NetworkManager.

I've made several changes to the default prefabs in 2.3.8 to hopefully alleviate or at the very least drastically reduce the odds of this problem occurring. If you don't mind trying it out, the download is available in the usual spot.

Please consider using the help channels first before posting issues. Common problems are generally well known and may already have an issue with them, and others will typically have an answer when a bug is not the cause.

**Comment by FirstGearGames** [comment]
At this time the latest versions are 23x and only those will be troubleshot. One thing I have been made aware of recently is some issues with Playflow not actually rebuilding the executable properly before uploading, but it doesn't sound like you're using Playflow. For anyone finding this late, I'm certain the Playflow developer will have this resolved soon as well.

**Comment by EcoEditor** [comment]
Hey, I switched to 2.3.8 pro experimental and still experience this bug. 
I think it may be important to delete the previous plugin version before switching to the new one... 
Do you have another solution, apart from Refreshing Default Prefabs?
