### ISSUE TITLE
Jitter when using prediction on 2 or more owned objects

### ISSUE THREAD

**Issue by DylanKontos** [FirstGearGames/FishNet#801]
Jitter when using prediction on 2 or more owned objects

Krint and AlphaLul discord thread - 'Predicted Rigid Body Projectiles'

**Comment by FirstGearGames** [comment]
This issue is resolved when disabling object pooling on the predicted spawned objects.

Keeping this open as this is still definitely a bug, but updating the priority to Low.

**Comment by FirstGearGames** [comment]
Resolved in 4.5.6
