### ISSUE TITLE
4.5.3R Pro NullRef in NetworkObjectEditor.cs:94

### ISSUE THREAD

**Issue by EvgenNechyporuk** [FirstGearGames/FishNet#804]
# Important
NullReferenceException: Object reference not set to an instance of an object
UnityEditor.EditorGUILayout.IsChildrenIncluded (UnityEditor.SerializedProperty prop) (at <5d5fdc1eeb2a4f39b26caadc7b79ec7e>:0)
UnityEditor.EditorGUILayout.PropertyField (UnityEditor.SerializedProperty property, UnityEngine.GUILayoutOption[] options) (at <5d5fdc1eeb2a4f39b26caadc7b79ec7e>:0)
FishNet.Object.Editing.NetworkObjectEditor.<OnInspectorGUI>g__ShowSettingsTab|21_0 () (at Assets/FishNet/Runtime/Object/Editor/NetworkObjectEditor.cs:94)
FishNet.Object.Editing.NetworkObjectEditor.OnInspectorGUI () (at Assets/FishNet/Runtime/Object/Editor/NetworkObjectEditor.cs:77)
UnityEditor.UIElements.InspectorElement+<>c__DisplayClass79_0.<CreateInspectorElementUsingIMGUI>b__0 () (at <5d5fdc1eeb2a4f39b26caadc7b79ec7e>:0)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr, Boolean&)

**General**
Unity version: 6000.0.24
Fish-Networking version: 4.5.3R Pro

**Replication**
1. Select any network object prefab

**Comment by FirstGearGames** [comment]
Ah yeah I renamed that new feature last minute and did not update the editor script. I'll push an update and close this out once complete.

**Comment by FirstGearGames** [comment]
Resolved, thank you!
