### ISSUE TITLE
Server (migh be client too) side SetPort doesnt work

### ISSUE THREAD

**Issue by SnaiperoG3D** [FirstGearGames/FishNet#811]
**General**
Unity version: 2022.3.29f1
Fish-Networking version: 4.5.2Pro, 4.5.4hf0R Pro

**Description**
symptoms: won't connect to server
2nd server hosted on same machine but with different port throw an error that port already in use

I believe SetPort or something inside doesnt work, cuz only one logical result in this issue that both servers trying to hosts on default port. as a result client trying to connect to custom port, but it doesnt work, no logs or errors on server. might be client SetPort doesnt work too. Tried to connect to server from Unity Editor, same issue. Port inside Tugboat inspector changed well, but still no connection. So there are 2 variants, server SetPort doesnt work or server and client SetPort doesnt work

Server port setted via this code:
```c#
networkManager.TransportManager.Transport.SetPort(serverConfig.serverPort);
```

**Replication**
Try to host 2 servers on different ports on Linux

**Expected behavior**
Servers hosts on different ports. Client connects well to both servers.

**Screenshots**
![image](https://github.com/user-attachments/assets/1c9d22bd-cf8d-4296-947a-d0da791bc647)

**Comment by FirstGearGames** [comment]
Tested working. You are probably trying to set the port after the server or client already started.

**Comment by SnaiperoG3D** [comment]
My bad. for some reason the toggle start on headless turned on by itself after the update to latest fish version. i have a perforce as vc and all files are read-only by default. that's why I couldn't even think that this toggle would switch itself for some reason. anyway all good. sorry
