### ISSUE TITLE
 Predicted Spawned object owner not receiving BufferLast ObserverRpc

### ISSUE THREAD

**Issue by maxkratt** [FirstGearGames/FishNet#815]
**General**
Unity version: 6000.0.23f1
Fish-Networking version: 4.5.5
Discord link: https://discord.com/channels/424284635074134018/1034477094731784302/1306138937248583744

**Description**
When a client predicted spawns an object and that object calls an ObserversRpc with BufferLast in its OnStartServer, the client who spawned it will not receive the ObserversRpc.

**Replication**
1. Download and import example
2. Open example scene in two editors
3. Run the example, it should start as a host in one and a client in the other.
4. The host will get two ObserversRpc messages, the client will only get the one from the host's created object.

**Expected behavior**
ObserversRpc should correctly be sent to clients that predicted spawn the object.

**Screenshots**
Host getting both messages:
![Screenshot 2024-11-13 114450](https://github.com/user-attachments/assets/2d8cb6d6-0d2f-4af3-9f18-e495b136aeec)

Client only getting the host's message:
![Screenshot 2024-11-13 114459](https://github.com/user-attachments/assets/1ee7a64c-0b1a-4b42-b935-010f1b00afae)

**Example**
[PredictedSpawnedObserverIssue.zip](https://github.com/user-attachments/files/17730249/PredictedSpawnedObserverIssue.zip)

**Comment by FirstGearGames** [comment]
Resolved pending release.
