### ISSUE TITLE
Weird Ragdoll / Physics behavior when AllowTickDropping is disabled on TimeManager

### ISSUE THREAD

**Issue by mifozski** [FirstGearGames/FishNet#820]
[AllowTickDroppingRagdollIssue.zip](https://github.com/user-attachments/files/17845936/AllowTickDroppingRagdollIssue.zip)

**General**
Unity version: 2022.3.46f
Fish-Networking version: 4.5.5
Discord link: https://discord.com/channels/424284635074134018/1034477094731784302/1308896162937569391

**Description**

**Replication**
1. Import AllowTickDroppingRagdollIssue.unitypackage from the zip
2. Open Ragdoll scene from the package
3. Click on Network Manager, disable Allow Tick Dropping on TimeManager component
4. Enter Play Mode
5. Select 'Ragdoll Test' object in the scene, right-click on the RagdollTest component, click 'Activate Ragdoll' option.

**Expected behavior**
The Ragdoll should fall normally, but it almost snaps to the ground.
If you enable Allow Tick Dropping the ragdoll falls normally.

**Screenshots**
I've posted a video in Discord with the steps provided above and that also shows that enabling the option fixes the problem: https://discord.com/channels/424284635074134018/1034477094731784302/1308897186947403776

**Comment by mifozski** [comment]
Additional note: the force with which the ragdoll "snaps" to the ground depends on how long I wait before activating it after entering the play mode - the more I wait, the stronger it snaps. I.e the effect is accumulated over time.

**Comment by mifozski** [comment]
After some testing I can reproduce the issue even with Allow Tick Dropping enabled - but now on the client side. To fix it I have to set Physics Mode to Unity instead of Time Manager.

**Comment by mifozski** [comment]
Thanks for the answer but I'm a little confused. I don't have anything Fishnet/Network related on the Ragdoll itself. It's just a set of game objects with rigidbodies connected with joints. So I'm not sure if what you said is applicable here as it's not clear where to find preReconcile and postReconcile. Can you please clarify?

**Comment by mifozski** [comment]
It turned out that I had to skip a frame after disabling the animator before disabling the `isKinematic` flag for it to work properly when using Time Manager Physics Mode.
This is probably related to the difference between how Unity operates when simulating physics manually and when Unity is allowed to do it automatically.
In my case, I'll implement the workaround and close this ticket.

**Comment by FirstGearGames** [comment]
You can force an animator to update it's state as well, so you may not need to do the frame skip. I do not recall the exact API but it's possible.
