### ISSUE TITLE
FishNet Pro Networking Evolved 4.5.5R Pro Go wrong

### ISSUE THREAD

**Issue by liugoudanzi** [FirstGearGames/FishNet#824]
![微信截图_20241203165330](https://github.com/user-attachments/assets/2fe482aa-1163-486a-bd09-9b1f8c1b4447)

After I tried to start the server, there was an issue with the client connection, which I haven't solved yet

**Comment by FirstGearGames** [comment]
Please follow the template. If you've not troubleshot this issue with our helpers yet on our Discord do that first please.

**Comment by liugoudanzi** [comment]
I've already figured it out on my own and just started a new project

**Comment by liugoudanzi** [comment]
> 请遵循模板。如果您还没有在我们的 Discord 上与我们的助手一起解决这个问题，请先这样做。
I've already figured it out on my own and just started a new project

**Comment by FirstGearGames** [comment]
Good to know ty. If you want to post your findings here that might help others as well our helpers. We could also add this to our FAQ.
