### ISSUE TITLE
"Default Prefab Objects" sometimes randomly removing a prefab or clearing right after setting it

### ISSUE THREAD

**Issue by Playeroth** [FirstGearGames/FishNet#825]
**General**
Unity version: 6
Fish-Networking version: 4.5.5
Discord link:

**Description**
On Setting a prefab to Default Prefab Objects, upon SAVING, the prefab will be gone on the list, needing to re add again atleast a second time. Not only that, sometimes on saving(?), after it stays in the DPO, it will randomly be removed after some time -- however this happens when im changing some object related to the networkbehavior it seems. Its not a issue i came across everytime i save but more specifically when working non directly in the object

**Replication**
Add a network object prefab to DPO,
Save Unity,
Done; prefab will be removed
![sometimes](https://github.com/user-attachments/assets/a37537e3-8c06-48fe-9a45-4ab0a7251788)

**Expected behavior**
I Expected it to stay in the DPO

**Comment by FirstGearGames** [comment]
DefaultPrefabObjects is populated automatically. If your object does not have a NetworkObject or has script errors it will not be added to the list. You should never attempt to manage the list manually. If you wish to manually manage networked prefabs make a SinglePrefabCOllection scriptable object and use that as your prefabs in the NetworkManager inspector.

**Comment by Playeroth** [comment]
discovered what was happening today.. :  (posting if anyone gets similar 'issue' )
![image](https://github.com/user-attachments/assets/0d8a29d5-86a6-4686-b4cc-8ff14f341aaf)
the setting from "entire project" was specific folder. setting back to entire project now properly gets all network objects.
