### ISSUE TITLE
Prediction V2 Jitter on Collision (Fishnet 4.5.5R)

### ISSUE THREAD

**Issue by BONDZ7** [FirstGearGames/FishNet#826]
**General**
Unity version:  2022.3.25f1
Fish-Networking version: 4.5.5R
Discord link: https://discord.com/channels/424284635074134018/1167060429051269200/1312060065003470900
Github project link: https://github.com/BONDZ7/Prediction_Rigidbody

**Description**
Visible jitter on client side when two rigidbodies collide with each other using Prediction v2's Prediction Rigidbody class.

**Replication**

1. Download the project from provided github link 
2. Build the game
3. Run the game on the server and client in separate windows
4. Press W or up arrow in client view and collide with the cube in front of it
5. See lag/jitter on collision.

**Expected behavior**
Smooth collision when rigidbodies hit each other instead of going into one another.

**Screenshots**
Images/Videos are provided in discord (see link above)

https://github.com/user-attachments/assets/c0c1d4dc-5876-43e0-8afd-942e0138b0e7

**Comment by FirstGearGames** [comment]
Can you please open a new issue following the bug report guidelines. Be sure to strip anything not related to the issue. Remove models and use placeholders.

https://fish-networking.gitbook.io/docs/manual/guides/creating-bug-reports
