### ISSUE TITLE
SyncVar.OnChange - desync on host

### ISSUE THREAD

**Issue by funnymanwin** [FirstGearGames/FishNet#833]
# Important
If General, Description, and Replication are not completed the issue will be closed immediately.

**General**
Unity version: 2022.3.22f1
Fish-Networking version: 4.5.6
Discord link: ---
** Above, post a link from our Discord where you troubleshot the issue (on Discord click the three dots next to the message, then Copy Message Link). Issue may be closed out if this is not included.

**Description**
Client receives incorrect `oldValue` value from SyncVar.OnChange event.

I started local server and then connected to it with local client. If I write this code:
```
private void Start()
{
    TurnedOn.OnChange += OnChange;
    RefreshLights();
}

[Server]
private void Server_Trigger()
{
    TurnedOn.Value = !TurnedOn.Value;
}

private void OnChange(bool oldValue, bool newValue, bool asServer)
{
    print($"OnChange() oldValue: {oldValue}, newValue: {newValue}, asServer: {asServer}");
}
```

And then try to call Server_Trigger() what I expect to see in console:

> OnChange() oldValue: False, newValue: True, asServer: true
> OnChange() oldValue: False, newValue: True, asServer: false

But what actually appears:

> OnChange() oldValue: False, newValue: True, asServer: true
> OnChange() oldValue: True, newValue: True, asServer: false

The problem here is in the second line where `oldValue` contains the new value on a client for some reason.

**Expected behavior**
> OnChange() oldValue: False, newValue: True, asServer: true
> OnChange() oldValue: False, newValue: True, asServer: false
- results in console in previous FishNet version 3.7.11 which I used in the game before update. And yes, i deleted all FishNet files before importing the new package v4.5.6

**Screenshots**
![Fishnet Bug report](https://github.com/user-attachments/assets/30807f73-da2f-4c85-9f5a-73ccf685d3cf)

**Comment by FirstGearGames** [comment]
Intentional. This will be the new behavior of host syncvars. You can switch to Stable to get the old ones back but they will be removed in V5.
