### ISSUE TITLE
Expose packetlayerbase of LiteNetLib.

### ISSUE THREAD

**Issue by FirstGearGames** [FirstGearGames/FishNet#86]
@mariusr#7821
"Exposing for PacketLayerBase from LiteNetLib so that we are able to create a PacketLayerBase or use the existing ones from LiteNetLib for encryption purposes(could also use crc for verify). The PacketLayerBase must be provided with the creating of the NetManager of LiteNetLib."

**Comment by FirstGearGames** [comment]
Added in 2.3.12

**Comment by mariusrubo** [comment]
Awesome!
