### ISSUE TITLE
Host mode - conn.Disconnect(false) other client corrupts your own client

### ISSUE THREAD

**Issue by valorware** [FirstGearGames/FishNet#87]
95% sure i found a severe bug in Host mode when server calls conn.Disconect(false) on a differenct client (to allow host to kick unwanted clients). was able to replicate in example scene. Basically, after kicking the other client, your own client becomes kinda corrupted - you no longer receive sync var changes - and in the CharacterControllerPrediction example scene all sorts of weird stuff happens too (other client doesn't disappear, if other client tries to connect again, lots of horrible desync)

2.3.10 Pro and was happening on 2.1 aswell i think

To replicate:
1) Open CharacterControllerPrediction example scene
2) Create an empty object and attach below script to it
3) Run 1 editor as Server and Client (host)
4) Press "Up arrow" a few times to observe you receive  the SyncVar's OnChange for both Server and Client
5) Join the game with another client.
6) On host, press spacebar to disconnect that client
7) Press "Up Arrow" some more and observe that you NO LONGER receieve the SyncVar's OnChange on your own client, only asServer
![unknown](https://user-images.githubusercontent.com/21067368/183939684-11e60a6b-1c0b-47b1-a1e3-2aabef7239c5.png)

```
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

using FishNet;
using FishNet.Object;
using FishNet.Object.Prediction;
using FishNet.Object.Synchronizing;
using FishNet.Connection;
using FishNet.Transporting;

public class testscript : NetworkBehaviour
{
    [SyncVar(OnChange = nameof(on_SyncVarChanged))] int testVar = 2;    

    private void on_SyncVarChanged(int prev, int next, bool asServer)
    {
        Debug.Log("on_SyncVarChanged. asServer=" + asServer);
    }

    // Update is called once per frame
    void Update()
    {
        if (Input.GetKeyDown(KeyCode.UpArrow))
        {
            if (InstanceFinder.IsServer) testVar++;
        }
        if (Input.GetKeyDown(KeyCode.Space))
        {
            if (InstanceFinder.IsServer)
            {
                // Find client that isn't mine
                var myClient = InstanceFinder.ClientManager.Connection;
                var srv = InstanceFinder.ServerManager;
                foreach (NetworkConnection conn in srv.Clients.Values)
                {
                    if (conn != myClient && conn != null)
                    {
                        // disconnect
                        Debug.Log("Disconnecting clientID=" + conn.ClientId);
                        conn.Disconnect(false);
                        
                    }
                }

            }
        }
    }
}
```

**Comment by FirstGearGames** [comment]
Fixed in 2.4.1
