### ISSUE TITLE
Custom (de)serializers can't be used across assemblies

### ISSUE THREAD

**Issue by AlexejheroYTB** [FirstGearGames/FishNet#88]
A custom serializer/deserializer (Read/Write extension method) in an assembly can only be used within that assembly, and does not work in other assemblies even if they have a reference to the one containing the methods. 

TO REPRODUCE:
1. Make custom serializer and deserializer for type X in assembly A
2. Make rpc method with type X in assembly B
3. 🔥 even though B references A

**Comment by FirstGearGames** [comment]
I'll have to look into this further but it might have to be a limitation given how codegen works. I'll let you know when I have more information.

**Comment by FirstGearGames** [comment]
Unfortunately as I suspected I cannot do anything about this.

Codegen processes one module (assembly) at a time, and after it's done being processed it's gone from memory. As result I cannot pull the serializer from your second assembly into the first.

**Comment by ooonush** [comment]
Would you consider adding the ability to create custom serializers using interfaces rather than extension methods? That way there would be no technical limitations.
For example, for a class to be serializable, it must inherit the required interface.
