### ISSUE TITLE
FishNet.Upgrading doesn't have an asmdef and compiles into Assembly-CSharp

### ISSUE THREAD

**Issue by AlexejheroYTB** [FirstGearGames/FishNet#91]
What the title says. There should be an asmdef for FishNet.Upgrading, probably only for the Editor platform.

**Comment by FirstGearGames** [comment]
Resolved in 2.4.0

**Comment by FirstGearGames** [comment]
I had previously added an assembly definition but decided to remove it.

If I were to keep the asmdef it would need to reference the Mirror asmdef, and if they changed that in any way would break my project.

I believe the current release has them as editor only, and maybe development builds. I've double checked the scripts though and made sure they now only exist in editor.
