### ISSUE TITLE
Using the Bayou/WebSocket transport, game object positions can get out of sync

### ISSUE THREAD

**Issue by colbyj** [FirstGearGames/FishNet#97]
So I made a small demo project using the FirstPerson starter template and added FishNet to the project, then set it up to sync the player capsules using Bayou (https://github.com/FirstGearGames/Bayou). Built a WebGL build, and used the editor as a server+client and Chrome as a client. Generally it works, but if I switch to a different Chrome tab, move around on the editor, then switch back, it's pretty clear that not all the messages were received on the Chrome client, as the editor client's capsule shows up in the wrong location in the WebGL client. Is there anything I can do about this? 

This is using Unity 2021.3.6f1.

**Comment by FirstGearGames** [comment]
I'm not sure this can be resolved. The NT does use eventual consistency but if packets become ignored when the window is out of focus, even reliable ones, I cannot do anything about that.
